#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to copy a VM image (SRC) to the image repository as DST
# Several SRC types are supported
###############################################################################

# ------------------------------------------------------------------------------
#  Set up Environment and transfer arguments
# ------------------------------------------------------------------------------
#
#  vmfs.conf: includes default TMP_DIR
#  libfs.sh a& scripts_common.sh: includes tools and lib calls
# ------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
    VMWARERC=/etc/one/vmwarerc
else
    LIB_LOCATION=$ONE_LOCATION/lib
    VMWARERC=$ONE_LOCATION/etc/vmwarerc
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/vmfs.conf

# -------- Get clone and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/ID \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TYPE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/CLONE_FSTYPE)

BASE_PATH="${XPATH_ELEMENTS[j++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
DS_ID="${XPATH_ELEMENTS[j++]}"
SRC="${XPATH_ELEMENTS[j++]}"
IMAGE_TYPE="${XPATH_ELEMENTS[j++]}"
CLONE_FSTYPE="${XPATH_ELEMENTS[j++]}"


# ------------------------------------------------------------------------------
#  Set up datastore
# ------------------------------------------------------------------------------
#
#  DST is the final generated image SOURCE, e.g. /vmfs/volumes/104/834efd1/
#  SRC/DST_FOLDER is the image folder name, e.g. 834efd1
#  DST_HOST is the host to make the transfers (from BRIDGE_LIST)
# ------------------------------------------------------------------------------

DST=`generate_image_path`

SRC_FOLDER=`basename $SRC`
DST_FOLDER=`basename $DST`

DST_HOST=`get_destination_host $ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"


# ------------------------------------------------------------------------------
#  Copy the image to the repository
# ------------------------------------------------------------------------------

log "Copying local image $SRC to the image repository"

if ! is_cdrom; then
    exec_and_log "ssh_make_path $DST_HOST $DST" \
                 "Cannot create $DST in $DST_HOST"

    if [ ! -z $CLONE_FSTYPE ]; then
        CLONE_FSTYPE="-d $CLONE_FSTYPE"
    fi

    ssh_exec_and_log $DST_HOST "$VMKFSTOOLS $CLONE_FSTYPE -i $SRC/disk.vmdk $DST/disk.vmdk" \
                 "Error copying $SRC/disk.vmdk to $DST/disk.vmdk"
else
    ssh_exec_and_log $DST_HOST "cp $SRC $DST" \
                     "Error copying $SRC $DST in $DST_HOST"
fi

# ------------------------------------------------------------------------------
#  Send SOURCE to OpenNebula core
# ------------------------------------------------------------------------------

echo "$DST"
