#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to copy a VM image (SRC) to the image repository as DST
# Several SRC types are supported
###############################################################################

# -------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
    VMWARERC=/etc/one/vmwarerc
else
    LIB_LOCATION=$ONE_LOCATION/lib
    VMWARERC=$ONE_LOCATION/etc/vmwarerc
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/vmfs.conf

# -------- Get cp and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/DS_USE_SSH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/ID \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH \
                    /DS_DRIVER_ACTION_DATA/IMAGE/ID \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TYPE)

BASE_PATH="${XPATH_ELEMENTS[0]}"
BRIDGE_LIST="${XPATH_ELEMENTS[1]}"
USE_SSH="${XPATH_ELEMENTS[2]:-$DS_USE_SSH}"
DS_ID="${XPATH_ELEMENTS[3]}"
SRC="${XPATH_ELEMENTS[4]}"
IMAGE_ID="${XPATH_ELEMENTS[5]}"
IMAGE_TYPE="${XPATH_ELEMENTS[6]}"

SRC_FOLDER=`basename $SRC`
DST=`generate_image_path`
DST_FOLDER=`basename $DST`
DST_HOST=`get_destination_host $IMAGE_ID`

# ------------ Set up datastore  -------------

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"

vmfs_set_up

# ------------ Copy the image to the repository -------------

log "Copying local image $SRC to the image repository"

if [ "$USE_SSH" == "yes" ]; then
    if ! is_cdrom; then
        ssh_make_path $DST_HOST /vmfs/volumes/$DS_ID/$DST_FOLDER
        ssh_exec_and_log $DST_HOST "$VMKFSTOOLS $VI_PARAMS -i /vmfs/volumes/$DS_ID/$SRC_FOLDER/disk.vmdk /vmfs/volumes/$DS_ID/$DST_FOLDER/disk.vmdk" "Error copying /vmfs/volumes/$DS_ID/$SRC_FOLDER/disk.vmdk to /vmfs/volumes/$DS_ID/$DST_FOLDER/disk.vmdk"
    else
        ssh_exec_and_log $DST_HOST "cp /vmfs/volumes/$DS_ID/$SRC_FOLDER /vmfs/volumes/$DS_ID/$DST_FOLDER" "Error copying /vmfs/volumes/$DS_ID/$SRC_FOLDER to /vmfs/volumes/$DS_ID/$DST_FOLDER in $DST_HOST"
    fi
else
    exec_and_log "vifs $VI_PARAMS --copy [$DS_ID]$SRC_FOLDER [$DS_ID]$DST_FOLDER" \
                 "Error copying $SRC to $DST"
fi

echo "$DST"
