#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
# ------------------------------------------------------------------------------
#  Set up Environment and transfer arguments
# ------------------------------------------------------------------------------
#
#  vmfs.conf: includes default TMP_DIR
#  libfs.sh a& scripts_common.sh: includes tools and lib calls
# ------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
    VMWARERC=/etc/one/vmwarerc
else
    LIB_LOCATION=$ONE_LOCATION/lib
    VMWARERC=$ONE_LOCATION/etc/vmwarerc
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/vmfs.conf

# -------- Get rm and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/ID \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST)

SRC="${XPATH_ELEMENTS[j++]}"
DS_ID="${XPATH_ELEMENTS[j++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"

# ------------------------------------------------------------------------------
#  Set up datastore
# ------------------------------------------------------------------------------
#
#  SRC is the image SOURCE to remove, e.g. /vmfs/volumes/104/834efd1/
#  SRC_FOLDER is the image folder name, e.g. 834efd1
#  DST_HOST is the host to make the transfers (from BRIDGE_LIST)
# ------------------------------------------------------------------------------

DST_HOST=`get_destination_host $ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

SRC_FOLDER=`basename $SRC`

# ------------------------------------------------------------------------------
#  Remove the image from the repository
# ------------------------------------------------------------------------------

if [ -n $SRC -a -n $DST_HOST ]; then
    log "Removing $SRC from the image repository"

    ssh_exec_and_log $DST_HOST "rm -rf $SRC" "Error deleting $SRC on $DST_HOST"
fi

exit 0
