#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_NAME=`basename $1 | cut -d. -f1`

if [ -z "${ONE_LOCATION}" ]; then
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one
    TMRC=/etc/one/tmrc
else
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var
    TMRC=$ONE_LOCATION/etc/tmrc
fi

. $MADCOMMON

export_rc_vars $TMRC

# Go to ONE_LOCATION

cd $VAR_LOCATION

LOG_FILE=$DRIVER_NAME

# Execute the actual MAD
execute_mad $*
