#!/bin/bash

DRIVER_NAME=`basename $1 | cut -d. -f1`

if [ -z "${ONE_LOCATION}" ]; then
    DRIVERRC=/etc/one/${DRIVER_NAME}/${DRIVER_NAME}rc
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one
else
    DRIVERRC=$ONE_LOCATION/etc/${DRIVER_NAME}/${DRIVER_NAME}rc
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var
fi

. $MADCOMMON

# Export the im_mad specific rc

export_rc_vars $DRIVERRC

# Go to ONE_LOCATION

cd $VAR_LOCATION

LOG_FILE=$DRIVER_NAME

# Execute the actual MAD
execute_mad $*
