# -------------------------------------------------------------------------- #
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

import os
import sys
import shutil
sys.path.append("../../../../../share/scons")

# This is the absolute path where the project is located
cwd=os.getcwd()

# Environment that will be applied to each scons child
main_env=Environment()
main_env['ENV']['PATH']=os.environ['PATH']

# Include dirs
main_env.Append(CPPPATH=[
    cwd+'/../../../include',
    cwd+'/../../../../../include',
    '/usr/include/cppunit/'
])

# Library dirs
main_env.Append(LIBPATH=[
    cwd+'/..',
    cwd+'/../../xml',
    cwd+'/../../../../log',
    cwd+'/../../../../common'
])

# Compile flags
main_env.Append(CPPFLAGS=[
    "-g",
    "-Wall"
])

# Linking flags
main_env.Append(LDFLAGS=["-g"])

# Libraries
main_env.Append(LIBS=[
    'cppunit',
    'scheduler_xml',
    'scheduler_pool',
    'nebula_log',
    'nebula_common'
])

main_env.Program('test_vm','VirtualMachineXMLTest.cc')
main_env.Program('test_host','HostXMLTest.cc')

################################################################################
#                               EXTRA CONFIGURATION
################################################################################

#-------------------------------------------------------------------------------
# xmlrpc
#-------------------------------------------------------------------------------

xmlrpc_dir=ARGUMENTS.get('xmlrpc', 'none')

if xmlrpc_dir!='none':
    main_env.Append(LIBPATH=[xmlrpc_dir+"/lib"])
    main_env.Append(CPPPATH=[xmlrpc_dir+"/include"])

main_env.ParseConfig('../../../../../share/scons/get_xmlrpc_config client')

#-------------------------------------------------------------------------------
# build lex/bison
#-------------------------------------------------------------------------------

build_parsers=ARGUMENTS.get('parsers', 'no')

if build_parsers=='yes':
    main_env.Append(parsers='yes')
else:
    main_env.Append(parsers='no')

#-------------------------------------------------------------------------------
# libxml2
#-------------------------------------------------------------------------------

main_env.ParseConfig('xml2-config --libs --cflags')
