# SConstruct for src/vm

# -------------------------------------------------------------------------- #
# Copyright 2002-2023, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('env')

lib_name='nebula_vm'

# Sources to generate the library
source_files=[
    'History.cc',
    'VirtualMachine.cc',
    'VirtualMachinePool.cc',
    'VirtualMachineTemplate.cc',
    'VirtualMachineAttribute.cc',
    'VirtualMachineDisk.cc',
    'VirtualMachineNic.cc',
    'VirtualMachineSystemSnapshot.cc',
    'VirtualMachineParser.cc',
    'VirtualMachineContext.cc',
    'VirtualMachineMonitorInfo.cc',
    'VMActions.cc',
    'Snapshots.cc',
    'Backups.cc',
    'BackupJob.cc',
    'BackupJobPool.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)
