#!/usr/bin/env ruby

# ---------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                  #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

###############################################################################
# This script is used retrieve the file size of a disk
###############################################################################

ONE_LOCATION ||= ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION ||= '/usr/lib/one/ruby'
    GEMS_LOCATION     ||= '/usr/share/one/gems'
else
    RUBY_LIB_LOCATION ||= ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     ||= ONE_LOCATION + '/share/gems'
end

# %%RUBYGEMS_SETUP_BEGIN%%
if File.directory?(GEMS_LOCATION)
    real_gems_path = File.realpath(GEMS_LOCATION)
    if !defined?(Gem) || Gem.path != [real_gems_path]
        $LOAD_PATH.reject! {|l| l =~ /vendor_ruby/ }

        # Suppress warnings from Rubygems
        # https://github.com/OpenNebula/one/issues/5379
        begin
            verb = $VERBOSE
            $VERBOSE = nil
            require 'rubygems'
            Gem.use_paths(real_gems_path)
        ensure
            $VERBOSE = verb
        end
    end
end
# %%RUBYGEMS_SETUP_END%%

$LOAD_PATH << RUBY_LIB_LOCATION
$LOAD_PATH << File.dirname(__FILE__)

require 'vcenter_driver'
require 'open3'

drv_action_enc = STDIN.read

drv_action =OpenNebula::XMLElement.new
drv_action.initialize_xml(Base64.decode64(drv_action_enc),
                          'DS_DRIVER_ACTION_DATA')

ds_ref  = drv_action['/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/VCENTER_DS_REF']
ds_id   = drv_action['/DS_DRIVER_ACTION_DATA/DATASTORE/ID']
img_path = drv_action['/DS_DRIVER_ACTION_DATA/IMAGE/PATH']

check_valid ds_ref, 'ds_ref'
check_valid img_path, 'img_path'

if img_path.start_with? 'vcenter://'
    begin
        vi_client = VCenterDriver::VIClient.new_from_datastore(ds_id)
        ds = VCenterDriver::Datastore.new_from_ref(ds_ref, vi_client)

        puts ds.stat(img_path.sub('vcenter://', ''))
    rescue StandardError => e
        message = "Error calculating image #{img_path} size."\
                  " Reason: \"#{e.message}\"."
        OpenNebula.log_error(message)
        if VCenterDriver::CONFIG[:debug_information]
            STDERR.puts "#{message} #{e.backtrace}"
        end
        exit(-1)
    ensure
        vi_client.close_connection if vi_client
    end
else
    cmd = "#{File.dirname(__FILE__)}/../fs/stat"
    stdin, stdout, = Open3.popen3(cmd)
    stdin.puts(drv_action_enc)
    stdin.close
    puts stdout.read
end
