# Number of days of inactivity before an issue becomes stale
daysUntilStale: 365
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - Security
  - Sponsored
  - "Status: Accepted"
# Label to use when marking an issue as stale
staleLabel: "Status: Abandoned"
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
  The OpenNebula Dev Team
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to lack of activity/feedback.
  Please reopen if you have further input or need to bump this.
  The OpenNebula Dev Team
