# This file describes which Sunstone views are available according to the
# primary group a user belongs to

# Specify the filename for a custom logo to be used in the UI.
# Acceptable formats include: .jpg, .jpeg, .png.
# Ensure the filename adheres to the pattern: [a-zA-Z0-9-_]+.(jpg|jpeg|png)
# Example:
#
# logo: custom_logo.png

groups:
    oneadmin:
        - admin
        - groupadmin
        - user
        - cloud
default:
    - user
    - cloud

# Name and description of each view.
#
# More views could be added creating a new object under views attribute.
# Example:
#   customview:
#     name: Name of the custom view
#     description: Description of the custom view

views:
  admin:
    name: groups.view.admin.name
    description: groups.view.admin.description
  cloud:
    name: groups.view.cloud.name
    description: groups.view.cloud.description
  groupadmin:
    name: groups.view.groupadmin.name
    description: groups.view.groupadmin.description
  user:
    name: groups.view.user.name
    description: groups.view.user.description
