# Deep VM search configuration
:vm_deep_search:
  enabled: true
  attributes:
    - key: "TEMPLATE/OS/ARCH"
      regex: ".*"
    - key: "TEMPLATE/DISK/SIZE"
      regex: "^[0-9]+$"
    - key: "USER_TEMPLATE/DEPARTMENT"
      regex: ".*"
    - key: "TEMPLATE/CONTEXT/SSH_PUBLIC_KEY"
      regex: ".*"
    - key: "TEMPLATE/NIC/IP"
      regex: "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"