#!/usr/bin/env ruby

# ---------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                  #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
end

$: << File.dirname(__FILE__)
$: << RUBY_LIB_LOCATION

require 'packet_driver'
require 'opennebula'

deploy_id = ARGV[0]
host      = ARGV[1]
vm_id     = ARGV[2]

begin
    one = OpenNebula::Client.new()
    vm = OpenNebula::VirtualMachine.new_with_id(vm_id, one)
    vm.info

    packet_drv = PacketDriver.new(host)
    packet_drv.shutdown(deploy_id, vm.lcm_state_str)

rescue Exception => e
    STDERR.puts error_message(<<EOT)
Shutdown of VM #{vm_id} on Packet host #{host} failed due to "#{e.message}"
#{e.backtrace}"
EOT

    exit(-1)
end
