#!/usr/bin/env ruby

require 'pp'
require 'rexml/document'
 
VM_NAME=ARGV[0]
 
def activate(rule)
    system "sudo ebtables -A #{rule}"
end
 
nets=`virsh dumpxml one-#{VM_NAME}`

doc=REXML::Document.new(nets).root
 
doc.elements.each('/domain/devices/interface') {|net|
    iface_mac=net.elements['mac'].attributes['address']
 
    mac=iface_mac.split(':')
    mac[-1]='00'
    net_mac=mac.join(':')
 
    tap=net.elements['target'].attributes['dev']

    in_rule="FORWARD -s ! #{net_mac}/ff:ff:ff:ff:ff:00 -o #{tap} -j DROP"
    out_rule="FORWARD -s ! #{iface_mac} -i #{tap} -j DROP"
 
    activate(in_rule)
    activate(out_rule)
}

