# SConstruct for src/rm

# -------------------------------------------------------------------------- #
# Copyright 2002-2011, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('env')

lib_name='nebula_rm'

#Sources to generate the library
source_files=[
    'RequestManager.cc',
    'RequestManagerAction.cc',
    'RequestManagerAllocate.cc',
    'RequestManagerDeploy.cc',
    'RequestManagerMigrate.cc',
    'RequestManagerSaveDisk.cc',
    'RequestManagerInfo.cc',
    'RequestManagerPoolInfo.cc',
    'RequestManagerHostAllocate.cc',
    'RequestManagerHostDelete.cc',
    'RequestManagerHostInfo.cc',
    'RequestManagerHostPoolInfo.cc',
    'RequestManagerHostEnable.cc',
    'RequestManagerImageAllocate.cc',
    'RequestManagerImageDelete.cc',
    'RequestManagerImageInfo.cc',
    'RequestManagerImageUpdate.cc',
    'RequestManagerImageRemoveAttribute.cc',
    'RequestManagerImagePublish.cc',
    'RequestManagerImagePersistent.cc',
    'RequestManagerImageEnable.cc',
    'RequestManagerImagePoolInfo.cc',
    'RequestManagerClusterAdd.cc',
    'RequestManagerClusterAllocate.cc',
    'RequestManagerClusterDelete.cc',
    'RequestManagerClusterInfo.cc',
    'RequestManagerClusterPoolInfo.cc',
    'RequestManagerClusterRemove.cc',
    'RequestManagerGroupAllocate.cc',
    'RequestManagerGroupDelete.cc',
    'RequestManagerGroupInfo.cc',
    'RequestManagerGroupPoolInfo.cc',
    'RequestManagerVirtualNetworkAllocate.cc',
    'RequestManagerVirtualNetworkInfo.cc',
    'RequestManagerVirtualNetworkPoolInfo.cc',
    'RequestManagerVirtualNetworkPublish.cc',
    'RequestManagerVirtualNetworkDelete.cc',
    'RequestManagerVirtualNetworkAddLeases.cc',
    'RequestManagerVirtualNetworkRemoveLeases.cc',
    'RequestManagerUserAllocate.cc',
    'RequestManagerUserDelete.cc',
    'RequestManagerUserChangePassword.cc',
    'RequestManagerUserInfo.cc',
    'RequestManagerUserPoolInfo.cc',
    'RequestManagerTemplateAllocate.cc',
    'RequestManagerTemplateDelete.cc',
    'RequestManagerTemplateInfo.cc',
    'RequestManagerTemplateUpdate.cc',
    'RequestManagerTemplateRemoveAttribute.cc',
    'RequestManagerTemplatePublish.cc',
    'RequestManagerTemplatePoolInfo.cc',
    'RequestManagerChown.cc',
    'RequestManagerAddDelGroup.cc',
]

# Build library
env.StaticLibrary(lib_name, source_files)
