---

- name: Clean APT metadata
  command: apt-get clean
  when: ansible_os_family == "Debian"
  listen: "clean repository metadata"

- name: Clean YUM metadata
  command: yum clean metadata
  args:
    warn: no
  when: ansible_os_family == "RedHat"
  listen: "clean repository metadata"
