#!/usr/bin/env ruby

$: << File.dirname(__FILE__)

require 'base64'
require 'OpenNebulaVLAN'

template    = ARGV[0]
vm_xml =  Base64::decode64(template)

onevlan = OpenvSwitchVLAN.new(vm_xml)
onevlan.activate
