#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i size
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/lvm/lvm.conf

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

#-------------------------------------------------------------------------------
# Get other LVM related fields
#-------------------------------------------------------------------------------

LV_NAME=`echo $SRC_PATH|cut -d. -f2`
VG_NAME=`echo $SRC_PATH|cut -d. -f1`
DEV="/dev/${VG_NAME}/${LV_NAME}"

DISK_ID=$(echo $DST_PATH|awk -F. '{print $NF}')

TARGET_DEV="/dev/$VG_NAME/$LV_NAME"
LV_CLONE="$LV_NAME-$VM_ID-$DISK_ID"
LV_CLONE_DEV="/dev/$VG_NAME/$LV_CLONE"

#-------------------------------------------------------------------------------
# Create the snapshot and link it
#-------------------------------------------------------------------------------

CLONE_CMD=$(cat <<EOF
    set -e
    mkdir -p $DST_DIR
    SIZE=\$($SUDO $LVS $DEV --noheadings --nosuffix --units m -o lv_size \
            | tr -d ' ')
    $SUDO $LVCREATE -L\${SIZE}M -n $LV_CLONE $VG_NAME
    $SUDO $DD if=$TARGET_DEV of=$LV_CLONE_DEV bs=64k
    rm -f "$DST_PATH"
    ln -s "$LV_CLONE_DEV" "$DST_PATH"
EOF
)

ssh_exec_and_log "$DST_HOST" "$CLONE_CMD" \
        "Error cloning $TARGET_DEV to $LV_CLONE_DEV"
exit 0
