#! /bin/sh
### BEGIN INIT INFO
# Provides:          opennebula-sunstone
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sunstone init script
# Description:       OpenNebula Sunstone web interface cloud initialisation script
### END INIT INFO

# Author: Jaime Melis <jmelis@opennebula.org>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Sunstone Web interface"
NAME=sunstone-server
DAEMON=/usr/bin/$NAME
DAEMON_ARGS=""
SCRIPTNAME=/etc/init.d/opennebula-sunstone
PID_FILE=/var/run/one/sunstone.pid

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
    service opennebula-novnc start
    mkdir -p /var/run/one /var/lock/one /var/log/one
    chown oneadmin /var/run/one /var/lock/one /var/log/one
    su oneadmin -s /bin/sh -c "$DAEMON start-sunstone"
}

#
# Function that stops the daemon/service
#
do_stop()
{
    su oneadmin -s /bin/sh -c "$DAEMON stop-sunstone"
    service opennebula-novnc stop
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  status)
    SUNSTONE_PID=`cat $PID_FILE`
    kill -0 $SUNSTONE_PID > /dev/null 2>&1
    if [ "$?" -eq "0" ]; then
      log_daemon_msg "$NAME is running"
      log_end_msg 0
    else
      log_daemon_msg "$NAME is not running"
      log_end_msg 1
    fi
    ;;
  restart|force-reload)
    #
    # If the "reload" option is implemented then remove the
    # 'force-reload' alias
    #
    log_daemon_msg "Restarting $DESC" "$NAME"
    do_stop
    case "$?" in
      0|1)
        do_start
        case "$?" in
            0) log_end_msg 0 ;;
            1) log_end_msg 1 ;; # Old process is still running
            *) log_end_msg 1 ;; # Failed to start
        esac
        ;;
      *)
          # Failed to stop
        log_end_msg 1
        ;;
    esac
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 3
    ;;
esac

