#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

t0 = Time.now
require_relative 'lib/lxd_driver'

LXDriver.log_init

vm_id = ARGV[2]

client = LXDClient.new
container = Container.get('one-' + vm_id, client)

container.stop

begin
    # TODO: mappers data parsing from xml
    # TODO: mapper for datablocks
    # TODO: mapper for context

    # TODO: mapper for rootfs
    st_driver = 'qcow2'

    mapper = "#{__dir__}/mapper/#{st_driver}.rb"
    dir = (LXDriver::CONTAINERS + container.name).to_s

    unmapped = system("#{mapper} unmap #{dir}")

    raise StandardError, 'unmapped failed' unless unmapped
rescue StandardError => e
    container.start
    raise e
end

container.delete

LXDriver.log_end(t0)
