#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

require_relative 'lib/lxd_driver'

OpenNebula.log_info('Begin ' + LXDdriver::SEP)

vm_name = ARGV[0]
host = ARGV[1]
vm_id = ARGV[2]

client = LXDClient.new
container = Container.get(vm_name, client)

container.stop
raise LXDError unless system('sudo umount /home/dann1/one-0.img')

container.delete

OpenNebula.log_info('End ' + LXDdriver::SEP)
