UtilsModule:
  name: UtilsModule
  entry: __HOST__/fireedge/modules/UtilsModule/remoteEntry.js
ConstantsModule:
  name: ConstantsModule
  entry: __HOST__/fireedge/modules/ConstantsModule/remoteEntry.js
ContainersModule:
  name: ContainersModule
  entry: __HOST__/fireedge/modules/ContainersModule/remoteEntry.js
ResourcesModule:
  name: ResourcesModule
  entry: __HOST__/fireedge/modules/ResourcesModule/remoteEntry.js
ComponentsV2Module:
  name: ComponentsV2Module
  entry: __HOST__/fireedge/modules/ComponentsV2Module/remoteEntry.js
FeaturesModule:
  name: FeaturesModule
  entry: __HOST__/fireedge/modules/FeaturesModule/remoteEntry.js
ProvidersModule:
  name: ProvidersModule
  entry: __HOST__/fireedge/modules/ProvidersModule/remoteEntry.js
StylesModule:
  name: StylesModule
  entry: __HOST__/fireedge/modules/StylesModule/remoteEntry.js
ModelsModule:
  name: ModelsModule
  entry: __HOST__/fireedge/modules/ModelsModule/remoteEntry.js
HooksModule:
  name: HooksModule
  entry: __HOST__/fireedge/modules/HooksModule/remoteEntry.js
