################################################################################
# Server Configuration
################################################################################

# Host and port where OneBEX server will run
:host: 0.0.0.0
:port: 13014

################################################################################
# Log
################################################################################

# Log debug level
#   0 = ERROR, 1 = WARNING, 2 = INFO, 3 = DEBUG
#
# System
#   - file: log to log file
#   - syslog: log to syslog
:log:
  :level: 2
  :system: file

################################################################################
# Puma
################################################################################

# Puma thread pool limits for concurrent OneBEX HTTP requests.
:puma:
  :min_threads: 1
  :max_threads: 4
