# SConstruct for src/pool

Import('env')

lib_name='nebula_pool'

# Sources to generate the library
source_files=[
	'PoolSQL.cc',
	'ObjectSQL.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)
