# SConstruct for src/pool

# -------------------------------------------------------------------------- #
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('sched_env')

lib_name='scheduler_xml'

if sched_env['parsers']=='yes':
    # LEX
    parser=sched_env.Lex(
        source='expr_parser.l'
    )
    sched_env.NoClean(parser)

    # BISON
    parser=sched_env.Bison(
        source='expr_arith.y'
    )
    sched_env.NoClean(parser)

    parser=sched_env.Bison(
        source='expr_bool.y'
    )
    sched_env.NoClean(parser)

source_files=['ObjectXML.cc',
              'Client.cc',
              'expr_parser.c',
              'expr_bool.cc',
              'expr_arith.cc']

# Build library
sched_env.StaticLibrary(lib_name, source_files)
