---

###############################################################################
# Valid defaults
###############################################################################

ceph_opennebula_osd_libvirt_enabled: True
