# Deep VM search configuration
:vm_deep_search:
  :keys:
    - :key: "TEMPLATE/LOGO"
      :pattern: ".*%s.*"
      :label: "Logo"
    - :key: "TEMPLATE/CONTEXT/TOKEN"
      :pattern: "^%s"
      :label: "Context Token"
    - :key: "TEMPLATE/NAME"
      :pattern: "^%s$"
      :label: "Name"
