# -------------------------------------------------------------------------- 
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)            
#                                                                          
# Licensed under the Apache License, Version 2.0 (the "License"); you may 
# not use this file except in compliance with the License. You may obtain   
# a copy of the License at                                               
#                                                                          
# http://www.apache.org/licenses/LICENSE-2.0                              
#                                                                           
# Unless required by applicable law or agreed to in writing, software      
# distributed under the License is distributed on an "AS IS" BASIS,       
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and    
# limitations under the License.                                        
# -------------------------------------------------------------------------- 

Import('env')

env.Prepend(LIBS=[
    'nebula_core_test',
    'nebula_lcm',
    'nebula_tm',
    'nebula_vmm',
    'nebula_im',
    'nebula_rm',
    'nebula_dm',
    'nebula_um',
    'nebula_vm',
    'nebula_hm',
    'nebula_vnm',
    'nebula_authm',
    'nebula_acl',
    'nebula_group',
    'nebula_template',
    'nebula_pool',
    'nebula_host',
    'nebula_vmtemplate',
    'nebula_xml',
    'nebula_image',
    'nebula_datastore',
    'nebula_cluster',
    'nebula_um',
    'nebula_mad',
    'nebula_common',
    'nebula_log',
    'nebula_core',
    'nebula_sql',
    'crypto'
])

nt = env.Object('NebulaTemplateTest.o', '../../nebula/NebulaTemplate.cc')

env.Program('test',[nt,'VirtualMachinePoolTest.cc'])
