#!/usr/bin/ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

STDERR.puts "#{__FILE__}: Operation not supported"
exit 1

# TODO: test
# require_relative 'container'

# vm_name    = ARGV[0]
# image_path = ARGV[1]
# target     = ARGV[2]
# disk_index = ARGV[3]

# xml = STDIN.read

# client    = LXCClient.new
# container = Container.new_from_xml(xml, client)

# exit(-1) unless container.detach_disk
