---

- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: 'Create datastore on ONE_LOCATION'
  file:
    state: directory
    path: "{{ one_location }}/var/datastores"
    owner: oneadmin
    group: oneadmin
  when: one_location is defined
