#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mvds host:remote_system_ds/disk.i SOURCE
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source ${DRIVER_PATH}/../../etc/tm/fs_lvm/fs_lvm.conf
source ${DRIVER_PATH}/../../datastore/libfs.sh

source $TMCOMMON

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------
SRC_PATH=$(arg_path "$SRC")
SRC_HOST=$(arg_host "$SRC")

DST_PATH=$(arg_path "$DST")

DISK_ID=$(echo "$SRC_PATH"|$AWK -F. '{print $NF}')
DS_SYS_ID=$(echo "$SRC_PATH"|$AWK -F/ '{print $(NF-2)}')

LV_NAME="lv-one-$VM_ID-$DISK_ID"
VG_NAME="vg-one-$DS_SYS_ID"

DEV="/dev/${VG_NAME}/${LV_NAME}"

if is_undeployed "$VM_ID" "$SRC_HOST"; then

    # get BRIDGE_LIST from datastore
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
    IFS= read -r -d '' BRIDGE_LIST < <(onedatastore show -x "$DS_SYS_ID" \
        | $XPATH /DATASTORE/TEMPLATE/BRIDGE_LIST )

    if [ -n "$BRIDGE_LIST" ]; then
        SRC_HOST=$(get_destination_host)
    fi
    # else we assume that FE have access to LVM storage

    ACTIVATE="$SUDO $LVCHANGE -ay $DEV > /dev/null 2>&1"
    DEACTIVATE="$SUDO $LVCHANGE -an $DEV > /dev/null 2>&1"
fi

#-------------------------------------------------------------------------------
# Move the image back to the datastore
#-------------------------------------------------------------------------------
log "Dumping $SRC to $DST"

if [ -n "$ACTIVATE" ]; then
    DUMP_CMD=$(cat <<EOF
        $SSH "$SRC_HOST" "$ACTIVATE; $DD if=\"$DEV\" bs=${DD_BLOCK_SIZE:-64k} conv=sparse; $DEACTIVATE" | \
            cat - > "$DST_PATH"
EOF
)
else
    DUMP_CMD=$(cat <<EOF
        $SSH "$SRC_HOST" "$DD if=\"$DEV\" bs=${DD_BLOCK_SIZE:-64k} conv=sparse" | cat - > "$DST_PATH"
EOF
)
fi

multiline_exec_and_log "$DUMP_CMD" "Error dumping $SRC to $DST"

DELETE_CMD=$(cat <<EOF
    set -e -o pipefail
    $SUDO $LVREMOVE -f $DEV
EOF
)

LOCK="tm-fs_lvm-${DS_SYS_ID}.lock"
exclusive "${LOCK}" 120 ssh_exec_and_log "$SRC_HOST" "$DELETE_CMD" \
    "Error dumping $SRC to $DST"

exit 0
