#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# POSTMIGRATE SOURCE DST remote_system_dir vmid dsid template
#  - SOURCE is the host where the VM is running
#  - DST is the host where the VM is to be migrated
#  - remote_system_dir is the path for the VM home in the system datastore
#  - vmid is the id of the VM
#  - dsid is the target datastore
#  - template is the template of the VM in XML and base64 encoded

SRC_HOST=$1
DST_HOST=$2

DST_PATH=$3

VMID=$4
DSID=$5

TEMPLATE_64=$(cat)

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

POOL_NAME="lv-one-$VMID-pool"
VG_NAME="vg-one-$DSID"

#--------------------------------------------------------------------------------
# Obtain original system directory (srcpath) for system DS migrations
DRIVER_PATH=$(dirname $0)
XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
unset i j XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
    /VM/HISTORY_RECORDS/HISTORY[last\(\)-1]/DS_ID)

ORIG_DS_ID="${XPATH_ELEMENTS[j++]}"
#--------------------------------------------------------------------------------

if [ "$ORIG_DS_ID" != "$DSID" ]; then
    SRC_PATH="${DST_PATH}/../../${ORIG_DS_ID}/${VMID}"

    CMD=$(cat <<EOF
        set -ex -o pipefail
        $SYNC
        $SUDO $LVSCAN

        for disk in \$(ls ${SRC_PATH}/disk.*); do
            if [ -L "\$disk" ]; then
                DEVICE=\$(readlink "\$disk")

                if echo "\$DEVICE" | grep -q '^/dev/vg-one'; then
                    FDS_RAW=\$($SUDO $LVS --noheadings -o vg_name,pool_lv \$DEVICE)
                    FDS=(\$FDS_RAW)
                    OLD_VG_NAME="\${FDS[0]}"
                    POOL_NAME="\${FDS[1]}"

                    # Remove LV on origin host
                    $SUDO $LVREMOVE -y \$DEVICE

                    # Remove pool on origin host (if it exists and is empty)
                    if [ -n "\$($SUDO $LVS --noheading -S "vg_name = \$OLD_VG_NAME && lv_name = \$POOL_NAME")" ] &&
                        [ -z "\$($SUDO $LVS --noheading -S "vg_name = \$OLD_VG_NAME && pool_lv = \$POOL_NAME")" ]; then
                        $SUDO $LVREMOVE -y "\$OLD_VG_NAME/\$POOL_NAME"
                    fi
                fi
            fi
        done

        # Remove origin VM folder
        rm -rf "${SRC_PATH}"
EOF
)
else
    CMD=$(cat <<EOF
        set -ex -o pipefail
        $SYNC
        $SUDO $LVSCAN

        for disk in \$(ls ${DST_PATH}/disk.*); do
            if [ -L "\$disk" ]; then
                DEVICE=\$(readlink "\$disk")

                if echo "\$DEVICE" | grep -q '^/dev/vg-one'; then
                    # Deactivate LV on origin host
                    $SUDO $LVCHANGE -an \$DEVICE
                fi
            fi
        done

        # Deactivate pool on origin host (if it exists)
        if [ -n "\$($SUDO $LVS --noheading -S "vg_name = $VG_NAME && lv_name = $POOL_NAME")" ]; then
            $SUDO $LVCHANGE -an "$VG_NAME/${POOL_NAME}"
            $SUDO $LVCHANGE -an "$VG_NAME/${POOL_NAME}_tmeta"
            $SUDO $LVCHANGE -an "$VG_NAME/${POOL_NAME}_tdata"
        fi

        # Remove VM folder from origin host
        rm -rf "${DST_PATH}"
EOF
)
fi

ssh_exec_and_log "$SRC_HOST" "$CMD" \
    "Error running fs_lvm postmigrate"

ssh_exec_and_log "${DST_HOST}" \
    "hostname -f >\"${DST_PATH}/.host\" || :"
    "Error modifying .host after fs_lvm postmigrate"

migrate_other "$@"
