#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# snap_create host:parent_image snap_id vmid ds_id

SRC=$1
SNAP_ID=$2
VM_ID=$3
DS_ID=$4

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    LIB_LOCATION=/usr/lib/one
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    LIB_LOCATION=$ONE_LOCATION/lib
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`
SRC_DIR=`dirname $SRC_PATH`
DS_SYS_ID=$(echo $SRC_DIR | $AWK -F '/' '{print $(NF-1)}')

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VM_ID| $XPATH \
                    /VM/DEPLOY_ID \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE )

DEPLOY_ID="${XPATH_ELEMENTS[j++]}"
SIZE="${XPATH_ELEMENTS[j++]}"
CLONE="${XPATH_ELEMENTS[j++]}"

#-------------------------------------------------------------------------------
# Create snapshots (stored in the current volume)
#-------------------------------------------------------------------------------

POOL_NAME="lv-one-$VM_ID-pool"
LV_NAME="lv-one-$VM_ID-$DISK_ID"
VG_NAME="vg-one-$DS_SYS_ID"
SNAP_NAME="${LV_NAME}_s$SNAP_ID"

SNAP_CREATE_CMD=$(cat <<EOF
    set -e -o pipefail

    if timeout ${VIRSH_TIMEOUT:-60} virsh -c $LIBVIRT_URI domfsfreeze $DEPLOY_ID ; then
        trap "virsh -c $LIBVIRT_URI domfsthaw $DEPLOY_ID || true" EXIT
        ${SYNC}
        ${SUDO} ${LVSCAN}

        $SUDO $LVCREATE -s -n $SNAP_NAME $VG_NAME/$LV_NAME

        # Extend the pool as needed
        pool_size="\$($SUDO $LVS --nosuffix --noheadings --units B -o lv_size $VG_NAME/$POOL_NAME)"
        lvs_size=0
        for lv in \$($SUDO $LVS --noheading -o lv_name -S 'vg_name = $VG_NAME && pool_lv = $POOL_NAME'); do
            lv_size="\$($SUDO $LVS --nosuffix --noheadings --units B -o lv_size $VG_NAME/\$lv)"
            lvs_size=\$((lvs_size + lv_size))
        done
        if [ "\$lvs_size" -gt "\$pool_size" ]; then
            $SUDO $LVEXTEND -L \${lvs_size}B $VG_NAME/$POOL_NAME
        fi

        ${SYNC}
    else
        echo "Unable to freeze VM; aborting"
        exit 1
    fi
EOF
)

ssh_exec_and_log "$SRC_HOST" "$SNAP_CREATE_CMD" \
                 "Error creating snapshot $SNAP_NAME"

exit 0
