#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

File.open('/tmp/post_timestamp', 'w'){|f| f.write(Time.new)}

# Define libraries location
ONE_LOCATION = ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION = '/usr/lib/one/ruby'
    GEMS_LOCATION     = '/usr/share/one/gems'
    VMDIR             = '/var/lib/one'
    CONFIG_FILE       = '/var/lib/one/config'
else
    RUBY_LIB_LOCATION = ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     = ONE_LOCATION + '/share/gems'
    VMDIR             = ONE_LOCATION + '/var'
    CONFIG_FILE       = ONE_LOCATION + '/var/config'
end

if File.directory?(GEMS_LOCATION)
    Gem.use_paths(GEMS_LOCATION)
end

$LOAD_PATH << RUBY_LIB_LOCATION

$LOAD_PATH << File.dirname(__FILE__)
$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

require 'vnmmad'
require 'nokogiri'
require 'opennebula'
require 'vcenter_driver'
require 'nsx_driver'
require 'ipaddr'

def to_nets(ip_start, size)
    File.open('/tmp/post_tonet_ip.debug', 'a') {|f| f.write(ip_start)}
    File.open('/tmp/post_tonet_size.debug', 'a') {|f| f.write(size)}

    nets = Array.new

    begin
        ipaddr = IPAddr.new ip_start
    rescue
        return
    end

    ip_i = ipaddr.to_i

    if ipaddr.ipv4?
        ip_length = 32
    elsif ipaddr.ipv6?
        ip_length = 128
    else
        return
    end

    # Find the largest address block (look for the first 1-bit)
    lblock = 0

    lblock += 1 while (ip_i[lblock] == 0 && lblock < ip_length )

    # Allocate whole blocks till the size fits
    while ( size >= 2**lblock )
        nets << "#{IPAddr.new(ip_i, ipaddr.family).to_s}/#{ip_length-lblock}"

        ip_i += 2**lblock
        size -= 2**lblock

        lblock += 1 while (ip_i[lblock] == 0 && lblock < ip_length )
    end

    # Fit remaining address blocks
    ip_length.downto(0) { |i|
        next if size[i] == 0

        nets << "#{IPAddr.new(ip_i, ipaddr.family).to_s}/#{ip_length-i}"

        ip_i += 2**i
    }

    return nets
end

def extract_vnet_data(vnet_id)
    # Create client to communicate with OpenNebula
    one_client = OpenNebula::Client.new

    # Get the network XML from OpenNebula
    # This is potentially different from the Netowrk Template
    # provided as the API call argument
    one_vnet = OpenNebula::VirtualNetwork.new_with_id(vnet_id, one_client)
    rc = one_vnet.info
    if OpenNebula.is_error?(rc)
        err_msg = rc.message
        raise CreateNetworkError, err_msg
    end

    vnet_data = {
        :nsxid => one_vnet['TEMPLATE/NSX_ID'],
        :name => one_vnet['NAME']
    }

    vnet_data
end

def extract_nic_data(nic, nsx_client, vm)
    # Network attributes
    nic_id = nic.xpath('NIC_ID').text
    nic_lp = nil
    network_id = nic.xpath('NETWORK_ID').text
    network_vcref = nic.xpath('VCENTER_NET_REF').text
    network_pgtype = nic.xpath('VCENTER_PORTGROUP_TYPE').text
    network_mac = nic.xpath('MAC').text

    # Virtual Machine devices
    vm_devices = vm.item.config.hardware.device
    vm_devices.each do |device|
        next unless vm.is_nic?(device)

        next if device.macAddress != network_mac

        case network_pgtype
        when NSXDriver::NSXConstants::NSXT_LS_TYPE
            lpid = device.externalId
            File.open("/tmp/post_lpid.debug", 'w') {|f| f.write(lpid) }
            nic_lp = NSXDriver::LogicalPort.new_child(nsx_client, lpid)
            raise "Logical port with id: #{lpid} nor found" unless nic_lp
            File.open("/tmp/post_lp.debug", 'w') {|f| f.write(nic_lp.inspect) }
            # target_id => id
            # target_display_name => display_name
            # target_type => resource_type
        when NSXDriver::NSXConstants::NSXV_LS_TYPE
            device.backing.port.portGroupKey
        else
            error_msg = "Network type is: #{network_pgtype} \
                            and should be \
                            #{NSXDriver::NSXConstants::NSXT_LS_TYPE} \
                            or #{NSXDriver::NSXConstants::NSXV_LS_TYPE}"
            error = NSXDriver::NSXError::UnknownObject.new(error_msg)
            STDERR.puts error_msg
            raise error
        end
    end

    nic_data = {
        :id => nic_id,
        :network_id => network_id,

        :network_vcref => network_vcref,
        :lp => nic_lp
    }

    nic_data
end

def extract_rule_data(xml_rule)
    sg_id = xml_rule.xpath('SECURITY_GROUP_ID').text
    sg_name = xml_rule.xpath('SECURITY_GROUP_NAME').text
    sg_direction = (xml_rule.xpath('RULE_TYPE').text.upcase) == 'INBOUND' ? 'IN' : 'OUT'
    # Protocol: TCP, UDP, ICMP...
    sg_protocol = xml_rule.xpath('PROTOCOL').text
    if sg_protocol == 'ICMP'
        sg_icmp_type = xml_rule.xpath('ICMP_TYPE').text
    end
    # OpenNebula network ID
    sg_network_id = xml_rule.xpath('NETWORK_ID').text
    vnet_data = extract_vnet_data(sg_network_id)

    # ip / netmask
    sg_ip = xml_rule.xpath('IP').text
    sg_ipsize = xml_rule.xpath('SIZE').text
    # Ports
    sg_range_port = xml_rule.xpath('RANGE').text
    if sg_range_port
        if sg_range_port.index(':')
            sg_port_from = sg_range_port[0..sg_range_port.index(':')-1]
            sg_port_to = sg_range_port[sg_range_port.index(':')+1,
                                        sg_range_port.length]
            sg_ports = "#{sg_port_from}-#{sg_port_to}"
        else
            sg_ports = sg_range_port
        end
    end
    # Create hash with data
    rule_data = {
        :id => sg_id,
        :name => sg_name,
        :direction => sg_direction,
        :protocol => sg_protocol,
        :icmp_type => sg_icmp_type,
        :network_id => sg_network_id,
        :network_name => vnet_data[:name],
        :network_nsxid => vnet_data[:nsxid],
        :ip => sg_ip,
        :ipsize => sg_ipsize,
        :ports => sg_ports
    }
    File.open('/tmp/post_rule_data.debug', 'a') {|f| f.write(rule_data)}

    rule_data
end

def create_rule_spec(rule, vm_data, nic_data)

    File.open('/tmp/post_rule_spec_rule.debug', 'a') {|f| f.write(rule)}

    # default spec
    # Allow any-any to any port applied on the virtual machine logical port
    rule_spec = {
        :display_name => "#{rule[:id]}-#{rule[:name]}-#{vm_data[:id]}-#{vm_data[:deploy_id]}-#{nic_data[:id]}",
        :destinations_excluded => false,
        :sources => [],
        :destinations => [],
        :services => [],
        :applied_tos => [
            {
                :target_id => nic_data[:lp].id,
                :target_display_name => nic_data[:lp].name,
                :target_type => nic_data[:lp].type,
                :is_valid => true
            }
        ],
        :ip_protocol => 'IPV4_IPV6',
        :logged => false,
        :action => 'ALLOW',
        :sources_excluded => false,
        :disabled => false,
        :direction => rule[:direction]
    }

    # Modify default rule spec based on rule_data extracted from vm template
    # SOURCES OR DESTINATIONS: Any | IP Address | Vnet
    networks_array = []

    # Target network: Vnet
    if rule[:network_id] != ''

        networks_array << {
            :target_id => rule[:network_nsxid],
            :target_display_name => rule[:network_name],
            :target_type => "LogicalSwitch",
            :is_valid => true
        }

    # Target network: Manual network (IP Address)
    elsif rule[:ip] != "" && rule[:size] != ""
        File.open('/tmp/post_rule_spec_rule.debug', 'a') {|f| f.write(rule)}
        networks = to_nets(rule[:ip], rule[:ipsize].to_i)
        File.open('/tmp/post_nets.debug', 'w') {|f| f.write(networks)}
        raise 'Networks are empty due to invalid ip size' if networks.empty?

        networks.each do |network|
            networks_array << {
                :target_id => network,
                :target_display_name => network,
                :target_type => 'IPAddress',
                :is_valid => true
            }
        end
    end

    # (OpenNebula) INBOUND  => Destination (NSX)
    # (OpenNebula) OUTBOUND => Source (NSX)
    unless networks_array.empty?
        rule_spec['sources'] = networks_array if rule[:direction] == 'OUT'
        rule_spec['destinations'] = networks_array if rule[:direction] == 'IN'
    end

    rule_spec

end

template = Base64.decode64(STDIN.read)

template_xml = Nokogiri::XML(template)
File.open("/tmp/post1.debug", 'w') {|f| f.write(template_xml) }

# OpenNebula VM
vm_data = {
    :id => template_xml.xpath('//VM/ID').text,
    :deploy_id => template_xml.xpath('//DEPLOY_ID').text
}
one_vm = VCenterDriver::VIHelper.one_item(OpenNebula::VirtualMachine, vm_data[:id])
one_vm_name = one_vm['NAME']

# OpenNebula host
host_name = template_xml
            .xpath('//HISTORY_RECORDS/HISTORY[last()]/HOSTNAME').text
one_host = VCenterDriver::VIHelper
           .find_by_name(OpenNebula::HostPool, host_name)
rc = one_host.info
if OpenNebula.is_error?(rc)
    err_msg = rc.message
    raise err_msg
end

host_id = one_host['ID']

# vCenter VirtualMachine
vi_client = VCenterDriver::VIClient.new_from_host(host_id)
vm = VCenterDriver::VirtualMachine.new_from_ref(vi_client, vm_data[:deploy_id], one_vm_name)

# NSX Actions
nsx_client = NSXDriver::NSXTClient.new_from_id(one_host['ID'])
dfw = NSXDriver::DistributedFirewall.new_child(nsx_client)

# NICs
# Inspect each nic with attach="yes"
nics = template_xml.xpath('//TEMPLATE/NIC[ATTACH="YES"]')
nics.each do |nic|
    # Extract NIC data
nsx_client = NSXDriver::NSXTClient.new_from_id(one_host['ID'])
nic_data = extract_nic_data(nic, nsx_client, vm)
    # Get all Security Groups belonging to each NIC.
    sec_groups = nic.xpath('SECURITY_GROUPS').text.split(',')
    File.open("/tmp/post_secgroups", 'w') {|f| f.write(sec_groups) }
    sec_groups.each do |sec_group|
        File.open("/tmp/post_secgroups_times", 'a') {|f| f.write("#{sec_group} ") }
        sg_rules_array = []
        # Get all rules belonging to this Security Group.
        sg_rules = template_xml.xpath("//SECURITY_GROUP_RULE[SECURITY_GROUP_ID=#{sec_group}]")
        File.open("/tmp/post_sg_rules", 'a') {|f| f.write(sg_rules) }

        sg_rules.each do |sg_rule|
            # Create rules spec
            rule_data = extract_rule_data(sg_rule)
            rule_spec = create_rule_spec(rule_data, vm_data, nic_data)
            sg_rules_array.push(rule_spec)
        end

        File.open('/tmp/post_sg_rules_array.debug', 'w'){|f| f.write(sg_rules_array.inspect)}
        # Create NSX rules
        sg_rules_array.each do |sg_spec|
            begin
                dfw.create_rule(sg_spec)
            rescue StandardError => e
                STDERR.puts e.message
                STDERR.puts e.backtrace \
                    if VCenterDriver::CONFIG[:debug_information]
                dfw.clear_opennebula_rules(template)
                exit 1
            end
        end

    end
end



exit 0
