#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
File.open('/tmp/POST.debug', 'w'){|f| f.write('POST')}
# Define libraries location
ONE_LOCATION = ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION = '/usr/lib/one/ruby'
    GEMS_LOCATION     = '/usr/share/one/gems'
    VMDIR             = '/var/lib/one'
    CONFIG_FILE       = '/var/lib/one/config'
else
    RUBY_LIB_LOCATION = ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     = ONE_LOCATION + '/share/gems'
    VMDIR             = ONE_LOCATION + '/var'
    CONFIG_FILE       = ONE_LOCATION + '/var/config'
end

if File.directory?(GEMS_LOCATION)
    Gem.use_paths(GEMS_LOCATION)
end

$LOAD_PATH << RUBY_LIB_LOCATION

$LOAD_PATH << File.dirname(__FILE__)
$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

require 'vnmmad'
require 'nokogiri'
require 'opennebula'
require 'vcenter_driver'
require 'nsx_driver'

def modified?(template)
    template_xml = Nokogiri::XML(template)
    action = template_xml.xpath('//TEMPLATE/NIC[ATTACH="YES"]')
    action.empty? ? false : true
end

template = Base64.decode64(STDIN.read)
deploy_id = ARGV[0]

template_xml = Nokogiri::XML(template)
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("POST template:  #{template}")}
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("\n")}

# OpenNebula host
host_name = template_xml
            .xpath('//HISTORY_RECORDS/HISTORY[last()]/HOSTNAME').text
one_host = VCenterDriver::VIHelper
           .find_by_name(OpenNebula::HostPool, host_name)
rc = one_host.info
if OpenNebula.is_error?(rc)
    err_msg = rc.message
    raise err_msg
end

vc_uuid = one_host['TEMPLATE/VCENTER_INSTANCE_ID']

# OpenNebula VM
one_vm = VCenterDriver::VIHelper.find_by_ref(OpenNebula::VirtualMachinePool,
                                             'DEPLOY_ID',
                                             deploy_id,
                                             vc_uuid)
rc = one_vm.info
if OpenNebula.is_error?(rc)
    err_msg = rc.message
    raise err_msg
end

# NSX Objects
nsx_client = NSXDriver::NSXTClient.new_from_id(one_host['ID'])
dfw = NSXDriver::DistributedFirewall.new_child(nsx_client)
ls = NSXDriver::LogicalSwitch.new(nsx_client)

# Get all modified or all NSX Nics
is_modified = modified?(template)
nsx_nics = ls.nsx_nics(template_xml, is_modified)
vm_state = one_vm.state_str
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("POST vm_state: #{vm_state}")}
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("\n")}
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("POST deploy_id: #{deploy_id}")}
File.open('/tmp/XXX_process.debug', 'a'){|f| f.write("\n")}
unless nsx_nics.empty? || (vm_state == 'POWEROFF')
    begin
        dfw.create_rules(deploy_id, template, is_modified)
    rescue StandardError => e
        dfw.clear_rules(template, is_modified)
        OpenNebula::log_error("Error creating Security Group rules " \
            "due to \"#{e.message}\"" \
            "\n********* STACK TRACE *********\n" \
            "\t#{e.backtrace.join("\n\t")}" \
            "\n*******************************\n")
        exit 1
    end
end

exit 0
