# --------------------------------------------------------------------------
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# --------------------------------------------------------------------------

import os
import sys
import shutil
sys.path.append("../../../share/scons")
from lex_bison import *

# This is the absolute path where the project is located
cwd="../../../"

# Environment that will be applied to each scons child
main_env=Environment()
main_env['ENV']['PATH']=os.environ['PATH']

# Add builders for flex and bison
add_lex(main_env)
add_bison(main_env)

# Include dirs
main_env.Append(CPPPATH=[
    cwd + '/include',
    cwd + '/include/test',
    '/usr/include/cppunit/',
])

# Library dirs
main_env.Append(LIBPATH=[
    cwd + '/src/common',
    cwd + '/src/nebula',
    cwd + '/src/pool',
    cwd + '/src/um',
    '/usr/include/openssl/',
])

main_env.Append(LIBS=[
    'nebula_um',
    'nebula_pool',
    'nebula_common',
    'nebula_core',
    'cppunit',
    'dl',
    'pthread',
    'sqlite3',
    'mysqlclient',
    'crypto'
])

# Compile flags
main_env.Append(CPPFLAGS=[
    "-g",
    "-Wall"
])

# Linking flags
main_env.Append(LDFLAGS=["-g "])
main_env.Program('test','UserPoolTest.cc')

# MYSQL
main_env.Append(LIBPATH=["/usr/lib/mysql"])
main_env.Append(CPPPATH=["/usr/include/mysql"])

