#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
end

$: << RUBY_LIB_LOCATION
$: << RUBY_LIB_LOCATION+"/cli"

require 'command_parser'
require 'one_helper/onetemplate_helper'

cmd=CommandParser::CmdParser.new(ARGV) do
    usage "`onetemplate` <command> [<args>] [<options>]"
    version OpenNebulaHelper::ONE_VERSION

    helper = OneTemplateHelper.new

    ########################################################################
    # Global Options
    ########################################################################
    set :option, CommandParser::OPTIONS

    list_options = CLIHelper::OPTIONS
    list_options << OpenNebulaHelper::XML
    list_options << OpenNebulaHelper::NUMERIC

    instantiate_options = [
        OneTemplateHelper::VM_NAME,
        OneTemplateHelper::MULTIPLE
    ]

    ########################################################################
    # Formatters for arguments
    ########################################################################
    set :format, :groupid, OpenNebulaHelper.rname_to_id_desc("GROUP") do |arg|
        OpenNebulaHelper.rname_to_id(arg, "GROUP")
    end

    set :format, :userid, OpenNebulaHelper.rname_to_id_desc("USER") do |arg|
        OpenNebulaHelper.rname_to_id(arg, "USER")
    end

    set :format, :templateid, OneTemplateHelper.to_id_desc do |arg|
        helper.to_id(arg)
    end

    set :format, :templateid_list, OneTemplateHelper.list_to_id_desc do |arg|
        helper.list_to_id(arg)
    end

    set :format, :filterflag, OneTemplateHelper.filterflag_to_i_desc do |arg|
        helper.filterflag_to_i(arg)
    end

    ########################################################################
    # Commands
    ########################################################################

    create_desc = <<-EOT.unindent
        Creates a new Template from the given template file
    EOT

    command :create, create_desc, :file do
        helper.create_resource(options) do |t|
            template=File.read(args[0])
            t.allocate(template)
        end
    end

    clone_desc = <<-EOT.unindent
        Creates a new Template from an existing one
    EOT

    command :clone, clone_desc, :templateid, :name do
        helper.perform_action(args[0],options,"cloned") do |t|
            res = t.clone(args[1])

            if !OpenNebula.is_error?(res)
                puts "ID: #{res}"
            end
        end
    end

    delete_desc = <<-EOT.unindent
        Deletes the given Image
    EOT

    command :delete, delete_desc, [:range, :templateid_list] do
        helper.perform_actions(args[0],options,"deleted") do |t|
            t.delete
        end
    end

    instantiate_desc = <<-EOT.unindent
        Creates a new VM instance from the given Template. This VM can be
        managed with the 'onevm' command
    EOT

    command :instantiate, instantiate_desc, :templateid,
            :options=>instantiate_options do
        exit_code=0

        number = options[:multiple] || 1
        number.times do |i|
            exit_code=helper.perform_action(args[0],options,"instantiated") do |t|
                name = options[:vm_name]
                name = name.gsub("%i",i.to_s) if name
                res = t.instantiate(name)

                if !OpenNebula.is_error?(res)
                    puts "VM ID: #{res}"
                end

                res
            end

            break if exit_code==-1
        end

        exit_code
    end

    publish_desc = <<-EOT.unindent
        DEPRECATED, use chmod instead. Publishes the given Template. A public 
        Template can be seen and instantiated by other users in the Template's 
        group.
    EOT

    command :publish, publish_desc, [:range,:templateid_list] do
        helper.perform_actions(args[0],options,"published") do |t|
            t.publish
        end
    end

    unpublish_desc = <<-EOT.unindent
        DEPRECATED, use chmod instead. Unpublishes the given Template. A private
        Template can't be instantiated by any other user.
    EOT

    command :unpublish, unpublish_desc, [:range,:templateid_list] do
        helper.perform_actions(args[0],options,"unpublished") do |t|
            t.unpublish
        end
    end

    chgrp_desc = <<-EOT.unindent
        Changes the Template group
    EOT

    command :chgrp, chgrp_desc,[:range, :templateid_list], :groupid do
        helper.perform_actions(args[0],options,"Group changed") do |t|
            t.chown(-1, args[1].to_i)
        end
    end

    chown_desc = <<-EOT.unindent
        Changes the Template owner and group
    EOT

    command :chown, chown_desc, [:range, :templateid_list], :userid,
            [:groupid,nil] do
        gid = args[2].nil? ? -1 : args[2].to_i
        helper.perform_actions(args[0],options,"Owner/Group changed") do |t|
            t.chown(args[1].to_i, gid)
        end
    end

    chmod_desc = <<-EOT.unindent
        Changes the Template permissions
    EOT

    command :chmod, chmod_desc, [:range, :templateid_list], :octet do
        helper.perform_actions(args[0],options, "Permissions changed") do |t|
            t.chmod_octet(args[1])
        end
    end

    update_desc = <<-EOT.unindent
        Update the template contents. If a path is not provided the editor will
        be launched to modify the current content.
    EOT

    command :update, update_desc, :templateid, [:file, nil] do
        helper.perform_action(args[0],options,"modified") do |template|
            str = OpenNebulaHelper.update_template(args[0], template, args[1])
            template.update(str)
        end
    end

    list_desc = <<-EOT.unindent
        Lists Templates in the pool
    EOT

    command :list, list_desc, [:filterflag, nil], :options=>list_options do
        helper.list_pool(options, false, args[0])
    end

    show_desc = <<-EOT.unindent
        Shows information for the given Template
    EOT

    command :show, show_desc, :templateid, :options=>OpenNebulaHelper::XML do
        helper.show_resource(args[0],options)
    end

    top_desc = <<-EOT.unindent
        Lists Templates continuously
    EOT

    command :top, top_desc, [:filterflag, nil], :options=>list_options do
        helper.list_pool(options, true, args[0])
    end
end
