#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

ONE_LOCATION = ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION = '/usr/lib/one/ruby'
    GEMS_LOCATION     = '/usr/share/one/gems'
else
    RUBY_LIB_LOCATION = ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     = ONE_LOCATION + '/share/gems'
end

# %%RUBYGEMS_SETUP_BEGIN%%
if File.directory?(GEMS_LOCATION)
    real_gems_path = File.realpath(GEMS_LOCATION)
    if !defined?(Gem) || Gem.path != [real_gems_path]
        $LOAD_PATH.reject! {|l| l =~ /vendor_ruby/ }

        # Suppress warnings from Rubygems
        # https://github.com/OpenNebula/one/issues/5379
        begin
            verb = $VERBOSE
            $VERBOSE = nil
            require 'rubygems'
            Gem.use_paths(real_gems_path)
        ensure
            $VERBOSE = verb
        end
    end
end
# %%RUBYGEMS_SETUP_END%%

$LOAD_PATH << RUBY_LIB_LOCATION
$LOAD_PATH << RUBY_LIB_LOCATION + '/cli'

require 'command_parser'
require 'one_helper/onevmgroup_helper'

CommandParser::CmdParser.new(ARGV) do
    usage '`onevmgroup` <command> [<args>] [<options>]'
    version OpenNebulaHelper::ONE_VERSION

    helper = OneVMGroupHelper.new

    before_proc do
        helper.set_client(options)
    end

    USE = {
        :name => 'use',
        :large => '--use',
        :description => 'lock use actions'
    }

    MANAGE = {
        :name => 'manage',
        :large => '--manage',
        :description => 'lock manage actions'
    }

    ADMIN = {
        :name => 'admin',
        :large => '--admin',
        :description => 'lock admin actions'
    }

    ALL = {
        :name => 'all',
        :large => '--all',
        :description => 'lock all actions'
    }

    ########################################################################
    # Global Options
    ########################################################################
    set :option, CommandParser::OPTIONS + OpenNebulaHelper::CLIENT_OPTIONS

    list_options  = CLIHelper::OPTIONS
    list_options += OpenNebulaHelper::FORMAT
    list_options << OpenNebulaHelper::NUMERIC
    list_options << OpenNebulaHelper::DESCRIBE

    ########################################################################
    # Formatters for arguments
    ########################################################################
    set :format, :groupid, OpenNebulaHelper.rname_to_id_desc('GROUP') do |arg|
        OpenNebulaHelper.rname_to_id(arg, 'GROUP')
    end

    set :format, :userid, OpenNebulaHelper.rname_to_id_desc('USER') do |arg|
        OpenNebulaHelper.rname_to_id(arg, 'USER')
    end

    set :format, :vmgroupid, OneVMGroupHelper.to_id_desc do |arg|
        tmp = helper.to_id(arg)
        @current_vmg = tmp[1]
        tmp
    end

    set :format, :vmgroupid_list, OneVMGroupHelper.list_to_id_desc do |arg|
        helper.list_to_id(arg)
    end

    set :format, :filterflag, OneVMGroupHelper.filterflag_to_i_desc do |arg|
        helper.filterflag_to_i(arg)
    end

    format :roleid, 'Role identifier' do |arg|
        helper.retrieve_role_id(@current_vmg, arg)
    end

    ########################################################################
    # Commands
    ########################################################################

    create_desc = <<-EOT.unindent
        Creates a new VM Group from the given description
    EOT

    command :create, create_desc, :file do
        helper.create_resource(options) do |obj|
            begin
                if args[0]
                    template = File.read(args[0])
                elsif !(stdin = OpenNebulaHelper.read_stdin).empty?
                    template = stdin
                else
                    STDERR.puts 'No VM Group description provided'
                    exit(-1)
                end

                obj.allocate(template)
            rescue StandardError => e
                STDERR.puts "Error creating VM Group: #{e.message}"
                exit(-1)
            end
        end
    end

    delete_desc = <<-EOT.unindent
        Deletes the VM Group
    EOT

    command :delete, delete_desc, [:range, :vmgroupid_list] do
        helper.perform_actions(args[0], options, 'deleted') do |obj|
            obj.delete
        end
    end

    list_desc = <<-EOT.unindent
        Lists VM Group in the pool. #{OneVMGroupHelper.list_layout_help}
    EOT

    command :list, list_desc, [:filterflag, nil], :options => list_options do
        helper.list_pool(options, false, args[0])
    end

    show_desc = <<-EOT.unindent
        Shows information for the given VM Group
    EOT

    command :show,
            show_desc,
            :vmgroupid,
            :options => OpenNebulaHelper::FORMAT do
        helper.show_resource(args[0], options)
    end

    chgrp_desc = <<-EOT.unindent
        Changes the VM Group's group
    EOT

    command :chgrp, chgrp_desc, [:range, :vmgroupid_list], :groupid do
        helper.perform_actions(args[0], options, 'Group changed') do |obj|
            obj.chown(-1, args[1].to_i)
        end
    end

    chown_desc = <<-EOT.unindent
        Changes the VM Group's owner and group
    EOT

    command :chown, chown_desc, [:range, :vmgroupid_list], :userid,
            [:groupid, nil] do
        args[2].nil? ? gid = -1 : gid = args[2].to_i
        helper.perform_actions(args[0], options, 'Owner/Group changed') do |obj|
            obj.chown(args[1].to_i, gid)
        end
    end

    chmod_desc = <<-EOT.unindent
        Changes the VM Group permissions
    EOT

    command :chmod, chmod_desc, [:range, :vmgroupid_list], :octet do
        helper.perform_actions(args[0], options, 'Permissions changed') do |t|
            t.chmod_octet(OpenNebulaHelper.to_octet(args[1]))
        end
    end

    update_desc = <<-EOT.unindent
        Update the template contents. If a path is not provided the editor will
        be launched to modify the current content.
    EOT

    command :update, update_desc, :vmgroupid, [:file, nil],
            :options => OpenNebulaHelper::APPEND do
        helper.perform_action(args[0], options, 'modified') do |obj|
            if options[:append]
                str = OpenNebulaHelper.append_template(args[0], obj, args[1])
            else
                str = OpenNebulaHelper.update_template(args[0], obj, args[1])
            end

            helper.set_client(options)
            obj = helper.retrieve_resource(obj.id)

            obj.update(str, options[:append])
        end
    end

    rename_desc = <<-EOT.unindent
        Renames the VM Group
    EOT

    command :rename, rename_desc, :vmgroupid, :name do
        helper.perform_action(args[0], options, 'renamed') do |o|
            o.rename(args[1])
        end
    end

    lock_desc = <<-EOT.unindent
        Locks a VM Group to prevent certain actions defined by different levels.
        The show action will never be locked.
        Valid states are: All.
        Levels:
        [Use]: locks Admin, Manage and Use actions.
        [Manage]: locks Manage and Use actions.
        [Admin]: locks only Admin actions.
    EOT

    command :lock, lock_desc, [:range, :vmgroupid_list],
            :options => [USE, MANAGE, ADMIN, ALL] do
        helper.perform_actions(args[0], options, 'VMGroup locked') do |vmg|
            if !options[:use].nil?
                level = 1
            elsif !options[:manage].nil?
                level = 2
            elsif !options[:admin].nil?
                level = 3
            elsif !options[:all].nil?
                level = 4
            else
                level = 1
            end
            vmg.lock(level)
        end
    end

    unlock_desc = <<-EOT.unindent
        Unlocks a VM Group.
        Valid states are: All.
    EOT

    command :unlock, unlock_desc, [:range, :vmgroupid_list] do
        helper.perform_actions(args[0], options, 'VMGroup unlocked') do |vmg|
            vmg.unlock
        end
    end

    role_add_desc = <<-EOT.unindent
        Add role to VM Group.
    EOT

    command :"role-add", role_add_desc, :vmgroupid, [:file, nil] do
        begin
            if args[1]
                template = File.read(args[1])
            elsif !(stdin = OpenNebulaHelper.read_stdin).empty?
                template = stdin
            end
        rescue StandardError => e
            STDERR.puts "Error reading template: #{e.message}."
            exit(-1)
        end

        # Ensure the template attributes are in ROLE section
        unless template.gsub(' ', '').match(/ROLE=\[/)
            template = "ROLE=[\n#{template.split("\n").join(",\n")}]"
        end

        helper.perform_action(args[0], options, 'Role added') do |vmg|
            vmg.role_add(template)
        end
    end

    role_delete_desc = <<-EOT.unindent
        Deletes role from VM Group.
    EOT

    command :"role-delete", role_delete_desc, :vmgroupid, :roleid do
        roleid = args[1].to_i

        helper.perform_action(args[0], options, 'Role removed') do |vmg|
            vmg.role_delete(roleid)
        end
    end

    role_update_desc = <<-EOT.unindent
        Update VM Group role
    EOT

    command :"role-update", role_update_desc, :vmgroupid, :roleid, [:file, nil] do
        vmg_id = args[0].to_i
        role_id = args[1].to_i
        file = args[2]

        helper.perform_action(vmg_id, options, 'Role updated') do |vmg|
            str = OpenNebulaHelper.update_template(vmg_id, vmg, file,
                                                   "ROLES/ROLE[ID=#{role_id}]")

            # Ensure the updated attributes are in ROLE section
            unless str.gsub(' ', '').match(/ROLE=\[/)
                str = "ROLE=[\n#{str.split("\n").join(",\n")}]"
            end

            vmg.role_update(role_id, str)
        end
    end
end
