#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
end

$: << RUBY_LIB_LOCATION
$: << RUBY_LIB_LOCATION+"/cli"

require 'command_parser'
require 'one_helper/onevnet_helper'
require 'one_helper/onecluster_helper'

cmd=CommandParser::CmdParser.new(ARGV) do
    usage "`onevnet` <command> [<args>] [<options>]"
    version OpenNebulaHelper::ONE_VERSION

    helper = OneVNetHelper.new

    ########################################################################
    # Global Options
    ########################################################################
    set :option, CommandParser::OPTIONS

    CREATE_OPTIONS = [OneClusterHelper::CLUSTER]

    ########################################################################
    # Formatters for arguments
    ########################################################################
    set :format, :groupid, OpenNebulaHelper.rname_to_id_desc("GROUP") do |arg|
        OpenNebulaHelper.rname_to_id(arg, "GROUP")
    end

    set :format, :userid, OpenNebulaHelper.rname_to_id_desc("USER") do |arg|
        OpenNebulaHelper.rname_to_id(arg, "USER")
    end

    set :format, :vnetid, OneVNetHelper.to_id_desc do |arg|
        helper.to_id(arg)
    end

    set :format, :vnetid_list, OneVNetHelper.list_to_id_desc do |arg|
        helper.list_to_id(arg)
    end

    set :format, :filterflag, OneVNetHelper.filterflag_to_i_desc do |arg|
        helper.filterflag_to_i(arg)
    end

    ########################################################################
    # Commands
    ########################################################################

    create_desc = <<-EOT.unindent
        Creates a new Virtual Network from the given template file
    EOT

    command :create, create_desc, :file, :options=>CREATE_OPTIONS do
        cid = options[:cluster] || ClusterPool::NONE_CLUSTER_ID

        helper.create_resource(options) do |vn|
            begin 
                template=File.read(args[0])
                vn.allocate(template, cid)
            rescue => e
                STDERR.puts e.message
                exit -1
            end
        end
    end

    delete_desc = <<-EOT.unindent
        Deletes the given Virtual Network
    EOT

    command :delete, delete_desc, [:range, :vnetid_list] do
        helper.perform_actions(args[0],options,"deleted") do |vn|
            vn.delete
        end
    end

    addleases_desc = <<-EOT.unindent
        Adds a lease to the Virtual Network
    EOT

    command :addleases, addleases_desc, :vnetid, :ip, [:mac, nil] do
        helper.perform_action(args[0],options,"lease added") do |vn|
            vn.addleases(args[1], args[2])
        end
    end

    rmleases_desc = <<-EOT.unindent
        Removes a lease from the Virtual Network
    EOT

    command :rmleases, rmleases_desc, :vnetid, :ip do
        helper.perform_action(args[0],options,"lease removed") do |vn|
            vn.rmleases(args[1])
        end
    end

    hold_desc = <<-EOT.unindent
        Holds a Virtual Network lease, marking it as used
    EOT

    command :hold, hold_desc, :vnetid, :ip do
        helper.perform_action(args[0],options,"lease on hold") do |vn|
            vn.hold(args[1])
        end
    end

    release_desc = <<-EOT.unindent
        Releases a Virtual Network lease on hold
    EOT

    command :release, release_desc, :vnetid, :ip do
        helper.perform_action(args[0],options,"lease released") do |vn|
            vn.release(args[1])
        end
    end

    publish_desc = <<-EOT.unindent
        DEPRECATED, use chmod instead. Publishes the given Virtual Network. 
        A public Virtual Network can be seen and used by other users in the 
        Virtual Network's group.
    EOT

    command :publish, publish_desc, [:range,:vnetid_list] do
        helper.perform_actions(args[0],options,"published") do |vn|
            vn.publish
        end
    end

    unpublish_desc = <<-EOT.unindent
        DEPRECATED, use chmod instead. Unpublishes the given Virtual Network. A 
        private Virtual Network can't be used by any other user.
    EOT

    command :unpublish, unpublish_desc, [:range,:vnetid_list] do
        helper.perform_actions(args[0],options,"unpublished") do |vn|
            vn.unpublish
        end
    end

    chgrp_desc = <<-EOT.unindent
        Changes the Virtual Network group
    EOT

    command :chgrp, chgrp_desc,[:range, :vnetid_list], :groupid do
        helper.perform_actions(args[0],options,"Group changed") do |vn|
            vn.chown(-1, args[1].to_i)
        end
    end

    chown_desc = <<-EOT.unindent
        Changes the Virtual Network owner and group
    EOT

    command :chown, chown_desc, [:range, :vnetid_list], :userid,
            [:groupid,nil] do
        gid = args[2].nil? ? -1 : args[2].to_i
        helper.perform_actions(args[0],options,"Owner/Group changed") do |vn|
            vn.chown(args[1].to_i, gid)
        end
    end

    chmod_desc = <<-EOT.unindent
        Changes the Virtual Network permissions
    EOT

    command :chmod, chmod_desc, [:range, :vnetid_list], :octet do
        helper.perform_actions(args[0],options, "Permissions changed") do |vn|
            vn.chmod_octet(args[1])
        end
    end

    list_desc = <<-EOT.unindent
        Lists Virtual Networks in the pool
    EOT

    command :list, list_desc, [:filterflag, nil],
            :options=>CLIHelper::OPTIONS+OpenNebulaHelper::OPTIONS do
        helper.list_pool(options, false, args[0])
    end

    show_desc = <<-EOT.unindent
        Shows information for the given Virtual Network
    EOT

    command :show, show_desc, :vnetid,
            :options=>OpenNebulaHelper::XML do
        helper.show_resource(args[0],options)
    end

    update_desc = <<-EOT.unindent
        Update the template contents. If a path is not provided the editor will
        be launched to modify the current content.
    EOT

    command :update, update_desc, :vnetid, [:file, nil] do
        helper.perform_action(args[0],options,"modified") do |vnet|
            str = OpenNebulaHelper.update_template(args[0], vnet, args[1])
            vnet.update(str)
        end
    end
end
