#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
    MAD_LOCATION="/usr/lib/one/mads"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
    MAD_LOCATION=ONE_LOCATION+"/lib/mads"
end

$: << RUBY_LIB_LOCATION
$: << File.join(File.dirname(__FILE__), '../../vmm/ec2')

require 'pp'
require 'OpenNebulaDriver'
require 'ec2_driver'

host = ARGV[2]

def monitor(host)
    sinst  = ENV["SMALL_INSTANCES"].to_i
    linst  = ENV["LARGE_INSTANCES"].to_i
    xlinst = ENV["EXTRALARGE_INSTANCES"].to_i

    smem  = 1048576 * 1.7 * sinst
    scpu  = 100 * sinst

    lmem  = 1048576 * 7.5 * linst
    lcpu  = 400 * linst

    xlmem = 1048576 * 15 * xlinst
    xlcpu = 800 * xlinst

    totalmemory = smem + lmem + xlmem
    totalcpu    = scpu + lcpu + xlcpu

    info="HYPERVISOR=ec2\nTOTALMEMORY=#{totalmemory}\n"<<
        "TOTALCPU=#{totalcpu}\nCPUSPEED=1000\nFREEMEMORY=#{totalmemory}"<<
        "\nFREECPU=#{totalcpu}\n"
    info << "HOSTNAME=\"#{host}\"\n"

    puts info
end

monitor(host)
