#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$LOAD_PATH << File.dirname(__FILE__)
$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

require 'vnmmad'
require 'vxlan_driver'

template64   = STDIN.read
deploy_id    = ARGV[0]
vn_id        = Integer(ARGV[1])

xpath_filter = VXLANDriver::XPATH_FILTER

begin
    # PRE - Related changes
    hm = VXLANDriver.from_base64(template64, xpath_filter, deploy_id)
    hm.update(vn_id)

    # POST - Related changes
    filter_driver = VNMMAD::VNMDriver.filter_driver(template64,
                                                    xpath_filter,
                                                    deploy_id)
    filter_driver.update(vn_id)
rescue StandardError => e
    OpenNebula.log_error(e.message)
    OpenNebula.log_error(e.backtrace)
    exit 1
end
