---

- block:
  - name: Update centos-release package
    yum: name=centos-release state=latest
    register: yum_result
    until: yum_result is succeeded
    retries: 3
    delay: 10
  - name: Install qemu-ev repository
    yum: name=centos-release-qemu-ev state=latest
    register: yum_result
    until: yum_result is succeeded
    retries: 3
    delay: 10
  - name: Install qemu-kvm-ev
    yum: name=qemu-kvm-ev state=present
    register: yum_result
    until: yum_result is succeeded
    retries: 3
    delay: 10
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - opennebula_node_kvm_use_ev

- block:
    - name: Enable RHEV repo
      command: subscription-manager repos --enable {{ opennebula_node_kvm_rhev_repo }}
      register: sm_result
      until: sm_result is succeeded
      retries: 3
      delay: 10
    - name: Instal RHEV
      yum: name=qemu-kvm-rhev state=latest
      until: yum_result is succeeded
      retries: 3
      delay: 10
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"
    - opennebula_node_kvm_use_ev

- name: Install qemu-kvm (base)
  yum: name=qemu-kvm state=present
  register: yum_result
  until: yum_result is succeeded
  retries: 3
  delay: 10
  when: not opennebula_node_kvm_use_ev or ansible_distribution_major_version != "7"

# Update to a fixed mkswap
# * Wed Jan 31 2018 Karel Zak <kzak@redhat.com> 2.23.2-51
# - fix #1538545 - SELinux error creating swap file
- name: Update util-linux
  package:
    name: util-linux
    state: latest
  register: pkg_result
  until: pkg_result is succeeded
  retries: 3
  delay: 10

- name: Install libgcrypt
  package:
    name: libgcrypt
    state: latest
  register: pkg_result
  until: pkg_result is succeeded
  retries: 3
  delay: 10
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenNebula node KVM package
  yum: name=opennebula-node-kvm state=latest
  register: yum_result
  until: yum_result is succeeded
  retries: 3
  delay: 10
