---

- name: Install OpenNebula node-kvm package
  apt:
    name: opennebula-node-kvm
    state: fixed
  retries: 3
  delay: 10

- include: kvm.yaml
  when: opennebula_node_kvm_manage_kvm == True

- include: libvirt.yaml
- include: security.yaml

- name: "create datastore for ONE_LOCATION"
  file: path={{ one_location }}/var/datastores owner=oneadmin group=oneadmin state=directory
  when: one_location is defined
