---

# SELinux
- block:
  - name: Set SELinux booleans
    seboolean:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      persistent: yes
    with_items: '{{ opennebula_node_selinux_booleans }}'
  when:
    - ansible_selinux.status == 'enabled'
    - ansible_os_family == "RedHat"

# AppArmor
- name: Check if AppArmor configuration exists
  stat: path=/etc/apparmor.d/abstractions/libvirt-qemu
  register: apparmor_libvirt_qemu

- block:
  - name: Add permissions to apparmor
    lineinfile:
      dest: /etc/apparmor.d/abstractions/libvirt-qemu
      line: "{{ item }}"
    with_items:
      - "  /srv/** rwk,"
      - "  /var/lib/one/datastores/** rwk,"

  - name: Reload apparmor
    service:
      name: apparmor
      state: reloaded
    register: service_result
    failed_when:
      - service_result is failed
      - "'find' not in service_result.msg and 'found' not in service_result.msg"
  when:
    - ansible_os_family == 'Debian'
    - apparmor_libvirt_qemu.stat.exists == True
