#!/bin/bash 

# -------------------------------------------------------------------------- #
# Copyright 2002-2011, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/xenrc

function error_exit() {
    exit_code=$1
    if [ "x$exit_code" != "x0" ]; then
        exit $exit_code
    fi
}

domain=$1

mkdir -p `dirname $domain`
cat > $domain

output=`$XM_CREATE $domain`

error_exit $?

domain_name=`echo $output | grep 'Started domain' | sed 's/^.*Started domain //' | tr -d '\n'`

out=`grep -e '^\#O CPU_CREDITS =' < $domain`

if [ "x$?" = "x0" ]; then
    credits=`echo $out | cut -d= -f2 | tr -d ' '`
    
    name=`grep -e '^name =' < $domain | cut -d= -f2 | tr -d ' ' | tr -d "\'"`
    
    $XM_CREDITS -d $name -w $credits
    
    error_exit $?
fi

echo $domain_name

