#!/bin/bash

if [ -z "${ONE_LOCATION}" ]; then
    DRIVERRC=/etc/one/vmm_kvm/vmm_kvmrc
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one
else
    DRIVERRC=$ONE_LOCATION/etc/vmm_kvm/vmm_kvmrc
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var
fi

. $MADCOMMON

# Export the vmm_mad specific rc
export_rc_vars $DRIVERRC

# Go to ONE_LOCATION
cd $VAR_LOCATION

# Execute the actual MAD
execute_mad $*
