---

- name: Update local known_hosts
  delegate_to: localhost
  become: no
  known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ inventory_hostname }} {{ item.type }} {{ item.key }}"
  when: item.key != ''
  with_items:
    - {  type: 'ssh-dss', key: "{{ ansible_ssh_host_key_dss_public | default('') }}" }
    - {  type: 'ssh-rsa', key: "{{ ansible_ssh_host_key_rsa_public | default('') }}" }
    - {  type: 'ecdsa-sha2-nistp256', key: "{{ ansible_ssh_host_key_ecdsa_public | default('') }}" }
    - {  type: 'ssh-ed25519', key: "{{ ansible_ssh_host_key_ed25519_public | default('') }}" }

- name: Update remote authorized_keys
  authorized_key:
    user: "oneadmin"
    key: "{{ lookup('file', '/var/lib/one/.ssh/id_rsa.pub') }}"

- name: Check for /var/lib/one/.ssh/id_rsa.pub
  delegate_to: localhost
  become: no
  stat:
    path: /var/lib/one/.ssh/id_rsa.pub
  register: stat_id_rsa_pub

- name: Check for /var/lib/one/.ssh/known_hosts
  delegate_to: localhost
  become: no
  stat:
    path: /var/lib/one/.ssh/known_hosts
  register: stat_known_hosts

- name: Copy local SSH keys
  copy:
    src: /var/lib/one/.ssh/id_rsa.pub
    dest: /var/lib/one/.ssh/id_rsa.pub
    owner: 9869
    group: 9869
    mode: "0644"
  when: stat_id_rsa_pub.stat.exists == true

- name: Copy local known_hosts
  copy:
    src: /var/lib/one/.ssh/known_hosts
    dest: /var/lib/one/.ssh/known_hosts
    owner: 9869
    group: 9869
    mode: "0644"
  when: stat_known_hosts.stat.exists == true

- name: Copy local private SSH keys
  copy:
    src: /var/lib/one/.ssh/{{ item.name }}
    dest: /var/lib/one/.ssh/{{ item.name }}
    owner: 9869
    group: 9869
    mode: "{{ item.mode }}"
  with_items:
    - { name: 'id_rsa',      mode: '0600' }
  when: opennebula_ssh_deploy_private_key == True
