---

- name: Create /var/lib/one/.ssh directory
  file:
    path: /var/lib/one/.ssh
    owner: 9869
    group: 9869
    mode: 0700
    state: directory

- include: sshd.yml
  when: opennebula_ssh_manage_sshd == True

- include: deploy_local.yml
  when: opennebula_ssh_deploy_local == True
