# Sunstone server configuration

# Timezone configuration
# Possible values:
#   currentTimeZone: any valid timezone string (e.g., "UTC", "America/New_York")
#   timeFormat: "24h" (default) or "12h"
#   timeSource: "browser" (default, use browser's timezone/format) or "os" (use server's configuration from currentTimeZone and timeFormat)
currentTimeZone = UTC
timeFormat = 24h
timeSource = browser
