#!/bin/bash
#
#    /etc/rc.d/init.d/opennebula-sunstone
#
# Starts the Sunstone Server
#
# chkconfig: 345 66 34
# description: Starts the OpenNebula daemon
# processname: opennebula-sunstone

### BEGIN INIT INFO
# Provides: opennebula-sunstone
# Required-Start: $local_fs $remote_fs oned
# Required-Stop: $local_fs $remote_fs oned
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop opennebula-sunstone
# Description: start and stop opennebula-sunstone
### END INIT INFO

prog="opennebula-sunstone"

SUNSTONE_BIN=/usr/bin/sunstone-server
LOCKFILE=/var/lock/subsys/${prog}
PID_FILE=/var/run/${prog}.pid

# Source function library.
. /etc/rc.d/init.d/functions


RETVAL=0

check() {
    # Check that we're a privileged user
    [ `id -u` = 0 ] || exit 4

    # Check if sunstone-server is executable
    test -x $SUNSTONE_BIN || exit 5
}

start() {
    check

    echo -n $"Starting Sunstone Server daemon: "
    daemon --user oneadmin $SUNSTONE_BIN start-sunstone
    RETVAL=$?

	echo
    [ $RETVAL -eq 0 ] && {
		touch $LOCKFILE
		echo $(ps -ef|grep su[n]stone-server | awk '{print $2}') > $PID_FILE
	}

    return $RETVAL
    service opennebula-novnc start
}

stop() {
    check

    service opennebula-novnc stop
    echo -n $"Stopping Sunstone Server daemon: "
    daemon --user oneadmin $SUNSTONE_BIN stop-sunstone
    RETVAL=$?

	[ $RETVAL -eq 0 ] && success || failure
	echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE $PID_FILE

    return $RETVAL
}

restart() {
    stop
    start
}


case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
status)
    status $prog
    RETVAL=$?
    ;;
*)
    echo $"Usage: $0 {start|stop|status|restart}"
    RETVAL=2
esac

exit $RETVAL
