#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

DRIVER_PATH=$(dirname $0)

DEFAULT_TYPE="raw"

DOMAIN="$1"
SOURCE="$2"
TARGET="$3"
TARGET_INDEX="$4"
DRV_ACTION="$5"

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

DISK_XPATH="/VMM_DRIVER_ACTION_DATA/VM/TEMPLATE/DISK[ATTACH='YES']"

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     $DISK_XPATH/DRIVER \
                    $DISK_XPATH/TYPE \
                    $DISK_XPATH/READONLY \
                    $DISK_XPATH/CACHE)

DRIVER="${XPATH_ELEMENTS[0]:-$DEFAULT_TYPE}"
TYPE="${XPATH_ELEMENTS[1]}"
READONLY="${XPATH_ELEMENTS[2]}"
CACHE="${XPATH_ELEMENTS[3]}"

TYPE=$(echo "$TYPE"|tr A-Z a-z)

case "$TYPE" in
block)
    TYPE_SOURCE="dev"
    TYPE_XML="block"
    DEVICE="disk"
    ;;
cdrom)
    TYPE_SOURCE="file"
    TYPE_XML="file"
    DEVICE="cdrom"
    ;;
*) 
    #NOTE: This includes TYPE=FS and TYPE=SWAP
    TYPE_SOURCE="file"
    TYPE_XML="file"
    DEVICE="disk"
    ;;
esac

[ -z "$CACHE" ] && [ -n "$DEFAULT_ATTACH_CACHE" ] && \
    CACHE="$DEFAULT_ATTACH_CACHE"
[ -n "$CACHE" ] && CACHE="cache='$CACHE'"

if [ "$READONLY" = "YES" ]; then
    READONLY="<readonly/>"
else
    READONLY=""
fi

ATTACH_FILE="$SOURCE.attach"

cat <<EOF > $ATTACH_FILE
<disk type='$TYPE_XML' device='$DEVICE'>
  <driver name='qemu' type='$DRIVER' $CACHE/>
  <source $TYPE_SOURCE='$SOURCE'/>
  <target dev='$TARGET'/>
  $READONLY
</disk>
EOF

exec_and_log "virsh --connect $LIBVIRT_URI attach-device $DOMAIN $ATTACH_FILE" \
    "Could not attach $SOURCE ($TARGET) to $DOMAIN"

rm -f "$ATTACH_FILE"
