#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/../../etc/vmm/kvm/kvmrc
source $(dirname $0)/../../scripts_common.sh

deploy_id=$1

TIMEOUT=60

function destroy_and_monitor
{
    # Get datastore path to get vm.xml
    DATASTORE="$(/var/tmp/one/vgpu "DATASTORE" "$deploy_id")"

    virsh --connect $LIBVIRT_URI --readonly dominfo $deploy_id > /dev/null 2>&1 || return 0

    virsh --connect $LIBVIRT_URI destroy $deploy_id

    # Destroy vGPU (only if suported by node)
    (sudo -l | grep -q vgpu) && sudo /var/tmp/one/vgpu "DELETE" "$DATASTORE/vm.xml"

    virsh --connect $LIBVIRT_URI --readonly dominfo $deploy_id > /dev/null 2>&1
    [ "x$?" != "x0" ]
}

retry $TIMEOUT destroy_and_monitor

if [ "x$?" != "x0" ]; then
    error_message "Could not destroy $deploy_id"
    exit 1
fi

# Compact memory
if [ "x$CLEANUP_MEMORY_ON_STOP" = "xyes" ]; then
    (sudo -l | grep -q sysctl) && (sudo -n sysctl vm.drop_caches=3 vm.compact_memory=1 &>/dev/null &) || true
fi
