#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/../../etc/vmm/kvm/kvmrc
source $(dirname $0)/../../scripts_common.sh

DOMAIN="$1"
SOURCE="$2"
TARGET="$3"
TARGET_INDEX="$4"

DETACH_PARAMS="--domain $DOMAIN --target $TARGET"

exec_and_log "virsh --connect $LIBVIRT_URI detach-disk $DETACH_PARAMS" \
    "Could not detach $TARGET from $DOMAIN"

virsh --connect $LIBVIRT_URI dumpxml $DOMAIN | \
    xmllint -xpath "//disk/target[@dev='$TARGET']" - >/dev/null 2>&1

if [ $? -eq 0 ] ; then
    error_message "Could not detach $TARGET from $DOMAIN"
    exit -1
fi

exit 0
