#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

deploy_id=$1
file=$2

if [ -f $file ]; then
    log "Moving old checkpoint file $file"
    epoch=`date +%s`

    exec_and_log "mv $file $file.$epoch" \
        "Could not move $file to $file.$epoch"
fi

touch $file
chmod 666 $file

exec_and_log "virsh --connect $LIBVIRT_URI save $deploy_id $file" \
    "Could not save $deploy_id to $file"
