
source "http://rubygems.org"

gem 'rdoc'

# Optional gems
group :optional do
    gem "rake" 
    gem "nokogiri"
    gem "libxml-ruby"
end

group :quota do
    gem "sqlite3-ruby"
    gem "sequel"
end

group :sunstone do
    gem 'json', '= 1.5.1'
    gem 'rack', '= 1.2.2'
    gem 'sinatra', '1.2.1'
    gem 'thin', '1.2.7'
end

group :cloud do
    gem 'amazon-ec2'
    gem 'rack', '= 1.2.2'
    gem 'sinatra', '1.2.1'
    gem 'thin', '1.2.7'
    gem 'uuid'
    gem 'curb'
end

group :ozones_client do
    gem 'json', '= 1.5.1'
end

group :ozones_server do
    gem 'json', '= 1.5.1'
    gem 'datamapper'
    gem 'dm-sqlite-adapter'
    gem 'dm-mysql-adapter'
end

group :ozones_server_mysql do
    gem 'json', '= 1.5.1'
    gem 'datamapper'
    gem 'dm-mysql-adapter'
end

group :ozones_server_sqlite do
    gem 'json', '= 1.5.1'
    gem 'datamapper'
    gem 'dm-sqlite-adapter'
end

group :acct do
    gem 'sequel'
    gem 'sqlite3'
    gem 'mysql'
end

group :acct_sqlite do
    gem 'sequel'
    gem 'sqlite3'
end

group :acct_mysql do
    gem 'sequel'
    gem 'mysql'
end




group :dummy do
    gem 'rake'
end

