#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

WHOAMI=`hostname -f`
if [ "$?" != "0" ]; then
    log "Couldn't get local hostname!?"
    unset WHOAMI
fi

SRC_PATH=`arg_path $SRC`
DST_PATH=`arg_path $DST`
SRC_PATH_SNAP="${SRC_PATH}.snap"
DST_PATH_SNAP="${DST_PATH}.snap"

SRC_HOST=`arg_host $SRC`
DST_HOST=`arg_host $DST`

DST_DIR=`dirname $DST_PATH`

ssh_make_path $DST_HOST $DST_DIR

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(basename ${DST_PATH} | cut -d. -f2)

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/ORIGINAL_SIZE)

SIZE="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"

#-------------------------------------------------------------------------------
# Copy files to the remote host
#-------------------------------------------------------------------------------
case $SRC in
http://*)
    log "Downloading $SRC"
    RMT_CMD="$WGET -O $DST_PATH $SRC"
    ssh_exec_and_log "$DST_HOST" "$RMT_CMD" "Error downloading $SRC"
    ;;

*)
    if [ -n "$WHOAMI" ]; then
        # check if SRC is the local machine
        if [ "$WHOAMI" = "$SRC_HOST" ]; then
            log "Replacing $SRC with $SRC_PATH"
            SRC=$SRC_PATH
        fi

        # check if DST is the local machine
        if [ "$WHOAMI" = "$DST_HOST" ]; then
            log "Replacing $DST with $DST_PATH"
            DST=$DST_PATH
        fi
    fi

    log "Cloning $SRC into $DST"
    exec_and_log "$SCP -r $SRC $DST" "Error copying $SRC to $DST"

    if [ -d "${SRC_PATH_SNAP}" ]; then
        exec_and_log "$SCP -r ${SRC_PATH_SNAP} ${DST_PATH_SNAP}" \
            "Error copying $SRC to $DST"
    fi

    if [ -n "$ORIGINAL_SIZE" -a "$SIZE" -gt "$ORIGINAL_SIZE" ]; then
       RESIZE_CMD="qemu-img resize ${DST_PATH} ${SIZE}M"
       ssh_exec_and_log "$DST_HOST" "$RESIZE_CMD" \
           "Error resizing image $DST"
    fi
    ;;
esac

