#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mvds host:remote_system_ds/disk.i fe:SOURCE|SOURCE vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

SRC_PATH="$(arg_path $SRC)"
DST_PATH="$(arg_path $DST)"
SRC_HOST="$(arg_host $SRC)"
DST_HOST="$(arg_host $DST)"

SRC_PATH_SNAP="${SRC_PATH}.snap"

DST_SNAP="${DST}.snap"

SRC_FILE="$(basename $SRC_PATH)"
DST_FILE="$(basename $DST_PATH)"

DST_DIR="$(dirname $DST_PATH)"
SRC_DIR="$(dirname $SRC_PATH)"

#-------------------------------------------------------------------------------
# Convert potentially qcow2 chain to single image (replica recovery snaps)
# and delete base + base.1, snap link and snap dir (if empty)
#-------------------------------------------------------------------------------
CONVERT_CMD=$(cat <<EOF
   if [ -L "$SRC_PATH" ]; then
       $QEMU_IMG convert -O qcow2 $SRC_PATH $SRC_PATH.full

       rm -f $SRC_PATH

       if [ -e $SRC_PATH_SNAP/base ]; then
           rm -f $SRC_PATH_SNAP/base $SRC_PATH_SNAP/base.1 $SRC_PATH_SNAP/rs_tmp

           if [ "\$(ls $SRC_PATH_SNAP)" = "${SRC_FILE}.snap" ]; then
               rm -f $SRC_PATH_SNAP/${SRC_FILE}.snap
           fi

           rmdir $SRC_PATH_SNAP
       elif [ -d $SRC_PATH_SNAP ]; then
           rm -rf $SRC_PATH_SNAP
       fi

       mv $SRC_PATH.full $SRC_PATH
   fi
EOF
)

ssh_exec_and_log "$SRC_HOST" "$CONVERT_CMD" "Error converting $SRC to standalone image"

#-------------------------------------------------------------------------------
# Move the image back to the datastore
#-------------------------------------------------------------------------------

log "Moving $SRC to datastore as $DST_PATH"

# Copy from possibly remote host to possible remote host
if [ "$(fix_dir_slashes $DST_HOST)" != "$DST_PATH" ]; then
    COPY_CMD=$(cat <<EOF
        set -e -o pipefail
        $TAR -C $SRC_DIR --transform="flags=r;s|$SRC_FILE|$DST_FILE|" -cSf - $SRC_FILE | \
            $SSH $DST_HOST "$TAR -xSf - -C $DST_DIR"
EOF
)

    ssh_forward ssh_exec_and_log "$SRC_HOST" "$COPY_CMD" \
                                 "Error copying $SRC to $DST_HOST:$DST_PATH"
else # Copy from possibly remote host to local
    REMOTE_CMD=$(cat <<EOF
        set -e -o pipefail
        $SSH $SRC_HOST "$TAR -C $SRC_DIR --transform=\"flags=r;s|$SRC_FILE|$DST_FILE|\" -cSf - $SRC_FILE" | \
            $TAR -xSf - -C $DST_DIR
EOF
)

    multiline_exec_and_log "$REMOTE_CMD" "Error copying $SRC to $DST_PATH"
fi

if $SSH $SRC_HOST ls ${SRC_PATH_SNAP} >/dev/null 2>&1; then
    exec_and_log "rsync -r --delete ${SRC_HOST}:${SRC_PATH_SNAP}/ ${DST_SNAP}"
fi

rm -f ${DST}.md5sum

exit 0
