---

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: "create datastore for ONE_LOCATION"
  file: path={{ one_location }}/var/datastores owner=oneadmin group=oneadmin state=directory
  when: one_location is defined

- name: 'Create hook subfolders into network driver folders'
  become: no
  local_action:
    module: file
    path: /var/lib/one/remotes/vnm/{{ item[0] }}/{{ item[1] }}.d
    state: directory
  with_nested:
    - '{{ opennebula_node_firecracker_network_drivers }}'
    - '{{ opennebula_node_firecracker_network_hook_types }}'

- name: 'Install firecracker hooks'
  become: no
  local_action:
    module: copy
    src: /var/lib/one/remotes/vnm/hooks/{{ item[1] }}/firecracker
    dest: /var/lib/one/remotes/vnm/{{ item[0] }}/{{ item[1] }}.d/firecracker
    mode: 'u+x,g+x'
  with_nested:
    - '{{ opennebula_node_firecracker_network_drivers }}'
    - '{{ opennebula_node_firecracker_network_hook_types }}'
