#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)
$: << File.join(File.dirname(__FILE__), "..")

require 'OpenNebulaNetwork'
require 'Ebtables'
require 'Firewall'
require 'SecurityGroups'

template64 = ARGV[0]

onevlan = EbtablesVLAN.from_base64(template64)
onevlan.deactivate

if OpenNebulaNetwork.has_fw_attrs?(template64)
    fw = OpenNebulaFirewall.from_base64(template64)
    fw.deactivate
else
    sg = OpenNebulaSG.from_base64(template64)
    sg.deactivate
end
