#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2010-2015, C12G Labs S.L                                         #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)

require 'az_driver'

deploy_id = ARGV[0]
host      = ARGV[1]

az_drv = AzureDriver.new(host)

az_drv.cancel(deploy_id)

