source 'https://rubygems.org'

if RUBY_VERSION < '2.1.0'
    gem 'nokogiri', '< 1.7'
elsif RUBY_VERSION < '2.3.0'
    gem 'nokogiri', '< 1.10'
else
    gem 'nokogiri'
end

if RUBY_VERSION < '2.0.0'
    gem 'net-ldap', '< 0.13'              # auth
    gem 'mysql2', '< 0.5.0'               # onedb
    gem 'mime-types', '< 3.0'             # hybrid (azure)
else
    gem 'net-ldap'                        # auth
    gem 'mysql2'                          # onedb
end

if RUBY_VERSION < '2.0.0'
    gem 'public_suffix', '< 1.5.0'
elsif RUBY_VERSION < '2.1.0'
    gem 'public_suffix', '< 3.0.0'
else
    gem 'public_suffix'
end

if RUBY_VERSION < '2.2.0'
    gem 'rack', '< 2.0.0'                 # sunstone, cloud, oneflow
    gem 'minitest', '< 5.12.0'            # packethost
    gem 'pg', '< 1.2.0'                   # onedb
else
    gem 'rack'                            # sunstone, cloud, oneflow
    gem 'pg'                              # onedb
end

if RUBY_VERSION >= '2.4.0'
    gem 'xmlrpc'
    gem 'webauthn'                        # sunstone
end

if RUBY_VERSION < '2.1'
    gem 'scrub_rb'
end

if RUBY_VERSION < '2.3'
    gem 'zendesk_api', '< 1.17.0'         # sunstone
    gem 'rqrcode', '< 1.0.0'              # sunstone
else
    gem 'zendesk_api'                     # sunstone
    gem 'rqrcode'                         # sunstone
end

if RUBY_VERSION >= '2.3'
    gem 'vsphere-automation-cis', '~> 0.4.6'
    gem 'vsphere-automation-vcenter', '~> 0.4.6'
end

ps = '< 3.0.0' if ruby_version < Gem::Version.new('2.1.0')

if ruby_version < Gem::Version.new('2.2.0')
    rack     = '< 2.0.0'
    minitest = '< 5.12.0'
    pg       = '< 1.2.0'
end

if ruby_version < Gem::Version.new('2.3.0')
    zendesk = '< 1.17.0'
    rq      = '< 1.0.0'
end

gem 'ffi-rzmq', '~> 2.0.7'
gem 'net-ldap'
gem 'nokogiri', nokogiri
gem 'public_suffix', ps

group :cli do
    gem 'gnuplot'
    gem 'highline', '~> 1.7'
    gem 'mysql2'
    gem 'pg', pg
    gem 'sqlite3'
    gem 'sequel'
end

group :onecfg, :cli do
    gem 'augeas', '~> 0.6'
end

group :onecfg, :cloud, :oneflow, :sunstone do
    gem 'json', '>= 2.0'
end

group :onecfg do
    gem 'git', '~> 1.5'
end

group :hybrid do
    gem 'aws-sdk-ec2', '>=1.151'
    gem 'aws-sdk-s3'
    gem 'aws-sdk-cloudwatch'
    gem 'azure_mgmt_compute'
    gem 'azure_mgmt_monitor'
    gem 'azure_mgmt_network'
    gem 'azure_mgmt_resources'
    gem 'azure_mgmt_storage'
    gem 'configparser'
end

group :packethost do
    gem 'minitest', minitest
    if ruby_version >= Gem::Version.new('2.3.0')
	    gem 'faraday_middleware', '~> 1.2.0'
    end
    gem 'activesupport', '~> 4.2'
    gem 'i18n', '~> 0.9'
end

group :cloud, :oneflow, :sunstone do
    gem 'rack', rack
    gem 'sinatra'
end

group :cloud do
    gem 'thin'
    gem 'uuidtools'
    gem 'curb'
end

group :oneflow, :sunstone do
    gem 'ipaddress', '~> 0.8.3'
end

group :oneflow do
    gem 'treetop', '>= 1.6.3'
    gem 'parse-cron'
end

group :sunstone do
    if ruby_version >= Gem::Version.new('2.4.0')
        gem 'webauthn'
    end

    gem 'zendesk_api', zendesk
    gem 'rqrcode', rq
    gem 'memcache-client'
    gem 'dalli', '<3.0'  # https://github.com/OpenNebula/one/issues/5584
    gem 'rotp'
end

group :oca do
    gem 'ox'
end

group :vmware do
    gem 'addressable'

    if ruby_version >= Gem::Version.new('2.3.0')
        gem 'vsphere-automation-cis', '~> 0.4.6'
        gem 'vsphere-automation-vcenter', '~> 0.4.6'
    end

    if ruby_version >= Gem::Version.new('2.4.1')
        gem 'rbvmomi', '~> 3.0.0'
    else
        gem 'rbvmomi', '~> 2.2.0'
    end
end
