#!/usr/bin/env ruby

require 'pp'

PACKAGES=%w{optional sunstone quota cloud ozones_client ozones_server
    ozones_server_mysql ozones_server_sqlite}

DEFAULT=%w{optional sunstone quota cloud ozones_server acct}

GROUPS={
    :optional => %w{nokogiri xmlparser},
    :quota => %w{sqlite3 sequel},
    :sunstone => %w{json rack sinatra thin},
    :cloud => %w{amazon-ec2 rack sinatra thin uuid curb},
    :ozones_client => %w{json},
    :ozones_server => %w{json datamapper dm-sqlite-adapter dm-mysql-adapter},
    :ozones_server_sqlite => %w{json datamapper dm-sqlite-adapter},
    :ozones_server_mysql => %w{json datamapper dm-mysql-adapter},
    :acct => %w{sequel sqlite3 mysql},
    :acct_sqlite => %w{sequel sqlite3 mysql},
    :acct_mysql => %w{sequel sqlite3 mysql}
}

DISTRIBUTIONS={
    :debian => {
        :id => ['Ubuntu', 'Debian'],
        :dependencies => {
            'sqlite3'   => 'libsqlite3-dev',
            'mysql'     => 'libmysqlclient-dev',
            'curb'      => 'libcurl4-openssl-dev',
            'nokogiri'  => 'libexpat1-dev',
            'xmlparser' => %w{libxml2-dev libxslt1-dev}
        },
        :install_command => 'apt-get install'
    },
    :redhat => {
        :id => ['CentOS', /^RedHat/],
        :dependencies => {
            'sqlite3'   => 'sqlite-devel',
            'mysql'     => 'mysql-devel',
            'curb'      => 'curl-devel',
            'nokogiri'  => 'expat-devel',
            'xmlparser' => %w{libxml2-devel libxslt-devel}
        },
        :install_command => 'yum install'
    },
    :suse => {
        :id => [/^SUSE/],
        :dependencies => {
            'sqlite3'   => 'sqlite3-devel' ,
            'mysql'     => 'libmysqlclient-devel',
            'curb'      => 'libcurl-devel',
            'nokogiri'  => 'libexpat-devel',
            'xmlparser' => %w{libxml2-devel libxslt-devel}
        },
        :install_command => 'zypper install'
    }
}


class String
    def unindent(spaces=4)
        self.gsub!(/^ {#{spaces}}/, '')
    end
end

def try_library(name, error_message)
    begin
        require name.to_s
    rescue LoadError
        STDERR.puts error_message
        exit -1
    end
end

def install_warning(packages)
#    puts "Use -h for help"
#    puts
    puts "About to install the gems for these components:"
    puts "* "<<packages.join("\n* ")
    puts
    puts "Press enter to continue..."
    yes=STDIN.readline
end

def help
    puts "Specify the package dependencies from this list:"
    puts "* "<<PACKAGES.join("\n* ")
    puts
    puts "If no parameters are specified then this list will be used:"
    puts DEFAULT.join(' ')
end

def get_gems(packages)
    packages.map do |package|
        GROUPS[package.to_sym]
    end.flatten.uniq
end

def detect_distro
    #lsb_info=`lsb_release -a`
    lsb_info="Distributor ID: RedHat"
    if $?!=0 && false
        STDERR.puts("lsb_release command not found")
        return nil
    end

    distribution_id=nil

    lsb_info.scan(/^Distributor ID: (.*?)$/) do |m|
        distribution_id=m.first.strip
    end

    return nil if !distribution_id

    distro=nil

    DISTRIBUTIONS.find do |dist, info|
        info[:id].find do |dist_id|
            dist_id===distribution_id
        end
    end
end

def get_dependencies(gems, dependencies)
    deps=[]

    gems.each do |gem_name|
        deps<<dependencies[gem_name]
    end

    deps.flatten!
    deps.compact!

    deps
end

def install_dependencies(gems, distro)
    if !distro
        puts(<<-EOT.unindent(12))
            Distribution not detected. Make sure you manually install the
            dependencies described in Building from Source from the OpenNebula
            documentation.

            Press enter to continue...
    EOT
    else
        puts "Distribution \"#{distro.first}\" detected."
        deps=get_dependencies(gems, distro.last[:dependencies])

        if deps.length==0
            return
        end

        puts "About to install these dependencies:"
        puts "* "<<deps.join("\n* ")
        puts
        puts "Press enter to continue..."
        STDIN.readline

        command=distro.last[:install_command]+" "<<deps.join(' ')
        puts command
        system command
    end
end

try_library :rubygems, <<-EOT.unindent
    rubygems required to use this tool

    Use one of these methods:

        * Debian/Ubuntu
            apt-get install rubygems libopenssl-ruby

        * RHEL/CENTOS
            yum install rubygems

        * Specific rubygems package for your distro

        * Follow the instructions from http://rubygems.org/pages/download
EOT

if ARGV.include?('-h')
    help
    exit(0)
end

if ARGV.length>0
    packages=ARGV
else
    packages=DEFAULT
end

gems_list=get_gems(packages)

dist=detect_distro

install_dependencies(gems_list, dist)

packages_string=gems_list.join(' ')


command_string = "gem install --no-ri --no-rdoc #{packages_string}"

install_warning(packages)

puts command_string
system command_string



