#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2014, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)
$: << File.join(File.dirname(__FILE__), "..")

require 'OpenNebulaNetwork'
require 'SecurityGroups'

template64 = ARGV[0]
deploy_id  = ARGV[1]

sg = OpenNebulaSG.from_base64(template64, deploy_id)
begin
    sg.activate
rescue OpenNebulaSGError => e
    error = e.error
    stage = e.stage

    OpenNebula.log_error(error.message)
    OpenNebula.log_error(error.backtrace)

    case stage
    when :bootstrap, :security_groups
        OpenNebula.log_info("Deactivating security groups for #{deploy_id}.")

        sg.deactivate
    when :deactivate
        OpenNebula.log_error("Error deactivating security group rules for #{deploy_id}. Please verify manually.")
    end
    exit 1

rescue Exception => error
    OpenNebula.log_error(error.message)
    OpenNebula.log_error(error.backtrace)
    exit 1
end
