#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$LOAD_PATH << File.dirname(__FILE__)
$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

require 'AliasSDNAT'

template64   = ARGV[0]
deploy_id    = nil
xpath_filter = AliasSDNATDriver::XPATH_FILTER

begin
    drv = AliasSDNATDriver.from_base64(template64, xpath_filter, deploy_id)
    drv.deactivate
rescue StandardError => e
    OpenNebula.log_error(e.message)
    OpenNebula.log_error(e.backtrace)
    exit 1
end
