# SConstruct for src/template

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('env')

lib_name='nebula_parsers'

if env['parsers']=='yes':
    # LEX
    parser=env.Lex(
    source='template_parser.l'
    )

    parser=env.Lex(
    source='vm_var_parser.l'
    )

    parser=env.Lex(
    source='expr_parser.l'
    )
    env.NoClean(parser)

    # BISON
    parser=env.Bison(
        source='template_syntax.y'
    )

    parser=env.Bison(
    source='vm_var_syntax.y'
    )

    parser=env.Bison(
    source='vm_file_var_syntax.y'
    )

    parser=env.Bison(
    source='expr_arith.y'
    )

    parser=env.Bison(
    source='expr_bool.y'
    )
    env.NoClean(parser)

# Sources to generate the library
source_files=[
    'template_parser.cc',
    'template_syntax.cc',
    'vm_var_parser.cc',
    'vm_var_syntax.cc',
    'vm_file_var_syntax.cc',
    'expr_parser.cc',
    'expr_bool.cc',
    'expr_arith.cc',
    'mem_collector.cc'
]

# Build library
env.StaticLibrary(lib_name, source_files)
