# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('env')
import os

# This is the absolute path where the project is located
cwd=os.getcwd()
workspace_dir=GetLaunchDir()

# Include dirs
env.Append(CPPPATH=[
    cwd + '/include/',
    workspace_dir + '/share/vendor/',
])

# Library dirs

env.Append(LIBPATH=[
    cwd+'/src/pool',
    cwd+'/src/sched'
])

env.Append(LIBS=['curl'])

################################################################################
# SCONS scripts to build
################################################################################

build_scripts=[
    'src/pool/SConstruct',
    'src/sched/SConstruct'
]

for script in build_scripts:
    sched_env=env.Clone()
    SConscript(script, exports='sched_env')
