# -------------------------------------------------------------------------- #
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

import os
import sys
import shutil
sys.path.append("../../share/scons")

from lex_bison import *

# This is the absolute path where the project is located
cwd=os.getcwd()

# Environment that will be applied to each scons child set in the main SConstruct
Import('env')
main_env=env

# Add builders for flex and bison
add_lex(main_env)
add_bison(main_env)

# Include dirs
main_env.Replace(CPPPATH=[
    cwd + '/include/',
    cwd + '../../../include/'
])

# Library dirs
main_env.Replace(LIBPATH=[
    cwd+'/src/xml',
    cwd+'/src/pool',
    cwd+'/src/sched',
    cwd+'/../log',
    cwd+'/../common',
])

################################################################################
#                               EXTRA CONFIGURATION
################################################################################

#-------------------------------------------------------------------------------
# libxml2
#-------------------------------------------------------------------------------

main_env.ParseConfig('xml2-config --libs --cflags')

################################################################################
# SCONS scripts to build
################################################################################

build_scripts=[
    'src/xml/SConstruct',
    'src/pool/SConstruct',
    'src/sched/SConstruct'
]

for script in build_scripts:
    env=main_env.Clone()
    SConscript(script, exports='env')
