#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i size
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON

DST_HOST=`arg_host $DST`

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`

DISK_ID=$(echo $DST|awk -F. '{print $NF}')
RBD_DST="${SRC_PATH}-${VM_ID}-${DISK_ID}"
RBD_SNAP="${VM_ID}-${DISK_ID}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
        done < <(onevm show -x $VM_ID| $XPATH  \
                            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CEPH_USER \
                            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/ORIGINAL_SIZE)

CEPH_USER="${XPATH_ELEMENTS[j++]}"
SIZE="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"

#-------------------------------------------------------------------------------
# Clone the image
#-------------------------------------------------------------------------------

if [ -n "$CEPH_USER" ]; then
    RBD="$RBD --id ${CEPH_USER}"
fi

CLONE_CMD=$(cat <<EOF
    set -e

    $RBD info $RBD_DST > /dev/null 2>&1 && exit 0

    RBD_FORMAT=\$($RBD info $SRC_PATH | sed -n 's/.*format: // p')

    if [ "\$RBD_FORMAT" = "2" ]; then
        $RBD snap create "$SRC_PATH@$RBD_SNAP"
        $RBD snap protect "$SRC_PATH@$RBD_SNAP"
        $RBD clone "$SRC_PATH@$RBD_SNAP" $RBD_DST
    else
        $RBD copy $SRC_PATH $RBD_DST
    fi

    if [ -n "$ORIGINAL_SIZE" -a "$SIZE" -gt "$ORIGINAL_SIZE" ]; then
        $RBD resize $RBD_DST --size $SIZE
    fi
EOF
)

ssh_exec_and_log "$DST_HOST" "$CLONE_CMD" \
                 "Error cloning $SRC_PATH to $RBD_DST in $DST_HOST"
exit 0
