#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# snap_delete host:parent_image snap_id vmid ds_id

SRC=$1
SNAP_ID=$2
VM_ID=$3
DS_ID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../datastore/ceph/ceph.conf

CEPH_UTILS=${DRIVER_PATH}/../../datastore/ceph/ceph_utils.sh

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VM_ID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CEPH_USER)

RBD_SRC="${XPATH_ELEMENTS[j++]}"
CLONE="${XPATH_ELEMENTS[j++]}"
CEPH_USER="${XPATH_ELEMENTS[j++]}"

if [ "$CLONE" = "NO" ]; then
    RBD_DST="${RBD_SRC}"
else
    RBD_DST="${RBD_SRC}-${VM_ID}-${DISK_ID}"
fi

#-------------------------------------------------------------------------------
# Delete snapshots
#-------------------------------------------------------------------------------

if [ -n "$CEPH_USER" ]; then
    RBD="$RBD --id ${CEPH_USER}"
fi

SNAP_DELETE_CMD=$(cat <<EOF
    RBD_FORMAT=\$($RBD info $RBD_SRC | sed -n 's/.*format: // p')

    if [ "\${RBD_FORMAT}" != "2" ]; then
        echo "Only RBD Format 2 is supported for this operation" >&2
        exit 1
    fi

    \$($RBD --format json snap ls $RBD_DST | grep -Pq "(?<=\"name\":\")$SNAP_ID")

    if [ \$? -eq 0 ]; then
        RBD_TGT=$RBD_DST
    else
        POOL_NAME=\$(echo $RBD_DST | cut -f1 -d'/')
        VOL_NAME=\$(echo $RBD_DST | cut -f2 -d'/')

        RBD_TGT=\$($RBD ls \${POOL_NAME} | grep "\${VOL_NAME}-[^-]*$SNAP_ID[^-]*")
        RBD_TGT="\${POOL_NAME}/\${RBD_TGT}"
    fi

    if [ -z "\${RBD_TGT}" ]; then
        echo "Could not find a volume with snapshot $SNAP_ID" >&2
        exit 1
    fi

    $RBD snap unprotect \${RBD_TGT}@$SNAP_ID
    $RBD snap rm \${RBD_TGT}@$SNAP_ID

    SNAPIDS=\$($RBD --format json snap ls \${RBD_TGT} | \
               grep -Po '(?<="name":")\d+' | \
               paste -d: -s)

    if [ -z "\${SNAPIDS}" ]; then
        $RBD rm \${RBD_TGT}
    else
        $RBD rename \${RBD_TGT} ${RBD_DST}-\${SNAPIDS}
    fi
EOF
)

ssh_exec_and_log "$SRC_HOST" "$SNAP_DELETE_CMD" \
                 "Error deleting snapshot $RBD_DST-$SNAP_ID@$SNAP_ID"
