#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

HYPERVISOR_DIR=$1.d

SCRIPTS_DIR=`dirname $0`
cd $SCRIPTS_DIR


function run_dir {
    (
    DIR=$1
    cd $DIR
    for i in `ls *`;do
        if [ -x "$i" ]; then
            ./$i
        fi
    done
    )
}

data=$(
    run_dir 'common.d'
    if [ -d "$HYPERVISOR_DIR" ]; then
        run_dir $HYPERVISOR_DIR
    fi
)

echo $data | tr '\n' ' '
