# SConstruct for src/vm

Import('env')

lib_name='nebula_dm'

# Sources to generate the library
source_files=[
	'DispatchManager.cc',
	'DispatchManagerActions.cc',	
	'DispatchManagerStates.cc',	
]

# Build library
env.StaticLibrary(lib_name, source_files)
