// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package image

import (
	context "context"
	shared "github.com/OpenNebula/one/src/oca/go/src/goca/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Persistent(ctx context.Context, in *PersistentRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chtype(ctx context.Context, in *ChtypeRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	SnapshotDelete(ctx context.Context, in *SnapshotDeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	SnapshotRevert(ctx context.Context, in *SnapshotRevertRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	SnapshotFlatten(ctx context.Context, in *SnapshotFlattenRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Chmod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Chown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Clone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Persistent(ctx context.Context, in *PersistentRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Persistent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Chtype(ctx context.Context, in *ChtypeRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Chtype", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) SnapshotDelete(ctx context.Context, in *SnapshotDeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/SnapshotDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) SnapshotRevert(ctx context.Context, in *SnapshotRevertRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/SnapshotRevert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) SnapshotFlatten(ctx context.Context, in *SnapshotFlattenRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/SnapshotFlatten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.image.ImageService/PoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error)
	Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error)
	Info(context.Context, *InfoRequest) (*shared.ResponseXML, error)
	Update(context.Context, *UpdateRequest) (*shared.ResponseID, error)
	Rename(context.Context, *RenameRequest) (*shared.ResponseID, error)
	Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error)
	Chown(context.Context, *ChownRequest) (*shared.ResponseID, error)
	Lock(context.Context, *LockRequest) (*shared.ResponseID, error)
	Unlock(context.Context, *UnlockRequest) (*shared.ResponseID, error)
	Clone(context.Context, *CloneRequest) (*shared.ResponseID, error)
	Enable(context.Context, *EnableRequest) (*shared.ResponseID, error)
	Persistent(context.Context, *PersistentRequest) (*shared.ResponseID, error)
	Chtype(context.Context, *ChtypeRequest) (*shared.ResponseID, error)
	SnapshotDelete(context.Context, *SnapshotDeleteRequest) (*shared.ResponseID, error)
	SnapshotRevert(context.Context, *SnapshotRevertRequest) (*shared.ResponseID, error)
	SnapshotFlatten(context.Context, *SnapshotFlattenRequest) (*shared.ResponseID, error)
	Restore(context.Context, *RestoreRequest) (*shared.ResponseXML, error)
	PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error)
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedImageServiceServer) Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedImageServiceServer) Info(context.Context, *InfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedImageServiceServer) Update(context.Context, *UpdateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedImageServiceServer) Rename(context.Context, *RenameRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedImageServiceServer) Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chmod not implemented")
}
func (UnimplementedImageServiceServer) Chown(context.Context, *ChownRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chown not implemented")
}
func (UnimplementedImageServiceServer) Lock(context.Context, *LockRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedImageServiceServer) Unlock(context.Context, *UnlockRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedImageServiceServer) Clone(context.Context, *CloneRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedImageServiceServer) Enable(context.Context, *EnableRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedImageServiceServer) Persistent(context.Context, *PersistentRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Persistent not implemented")
}
func (UnimplementedImageServiceServer) Chtype(context.Context, *ChtypeRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chtype not implemented")
}
func (UnimplementedImageServiceServer) SnapshotDelete(context.Context, *SnapshotDeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotDelete not implemented")
}
func (UnimplementedImageServiceServer) SnapshotRevert(context.Context, *SnapshotRevertRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotRevert not implemented")
}
func (UnimplementedImageServiceServer) SnapshotFlatten(context.Context, *SnapshotFlattenRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotFlatten not implemented")
}
func (UnimplementedImageServiceServer) Restore(context.Context, *RestoreRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedImageServiceServer) PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolInfo not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Chmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Chmod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Chmod(ctx, req.(*ChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Chown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Chown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Chown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Chown(ctx, req.(*ChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Clone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Clone(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Persistent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Persistent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Persistent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Persistent(ctx, req.(*PersistentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Chtype_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChtypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Chtype(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Chtype",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Chtype(ctx, req.(*ChtypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_SnapshotDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).SnapshotDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/SnapshotDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).SnapshotDelete(ctx, req.(*SnapshotDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_SnapshotRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).SnapshotRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/SnapshotRevert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).SnapshotRevert(ctx, req.(*SnapshotRevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_SnapshotFlatten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotFlattenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).SnapshotFlatten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/SnapshotFlatten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).SnapshotFlatten(ctx, req.(*SnapshotFlattenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_PoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).PoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.image.ImageService/PoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).PoolInfo(ctx, req.(*PoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "one.image.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _ImageService_Allocate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ImageService_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _ImageService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ImageService_Update_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _ImageService_Rename_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _ImageService_Chmod_Handler,
		},
		{
			MethodName: "Chown",
			Handler:    _ImageService_Chown_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _ImageService_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _ImageService_Unlock_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _ImageService_Clone_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _ImageService_Enable_Handler,
		},
		{
			MethodName: "Persistent",
			Handler:    _ImageService_Persistent_Handler,
		},
		{
			MethodName: "Chtype",
			Handler:    _ImageService_Chtype_Handler,
		},
		{
			MethodName: "SnapshotDelete",
			Handler:    _ImageService_SnapshotDelete_Handler,
		},
		{
			MethodName: "SnapshotRevert",
			Handler:    _ImageService_SnapshotRevert_Handler,
		},
		{
			MethodName: "SnapshotFlatten",
			Handler:    _ImageService_SnapshotFlatten_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _ImageService_Restore_Handler,
		},
		{
			MethodName: "PoolInfo",
			Handler:    _ImageService_PoolInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image.proto",
}
