#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2016, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to monitor the free and used space of a datastore
###############################################################################

# -------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/ceph.conf

# -------- Get datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/POOL_NAME \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/CEPH_USER \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/CEPH_CONF)

BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
POOL_NAME="${XPATH_ELEMENTS[j++]:-$POOL_NAME}"
CEPH_USER="${XPATH_ELEMENTS[j++]}"
CEPH_CONF="${XPATH_ELEMENTS[j++]}"

HOST=`get_destination_host`

if [ -z "$HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

if [ -n "$CEPH_USER" ]; then
    CEPH="$CEPH --id ${CEPH_USER}"
fi

if [ -n "$CEPH_CONF" ]; then
    CEPH="$CEPH --conf ${CEPH_CONF}"
    RADOS="$RADOS --conf ${CEPH_CONF}"
fi

# ------------ Compute datastore usage -------------

MONITOR_SCRIPT=$(cat <<EOF
$CEPH df --format xml
EOF
)

MONITOR_DATA=$(ssh_monitor_and_log $HOST "$MONITOR_SCRIPT" 2>&1)
MONITOR_STATUS=$?

if [ "$MONITOR_STATUS" = "0" ]; then
    XPATH="${DRIVER_PATH}/../xpath.rb --stdin"

    unset i j XPATH_ELEMENTS

    while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
    done < <(echo $MONITOR_DATA | $XPATH \
                        "/stats/pools/pool[name = \"${POOL_NAME}\"]/stats/bytes_used" \
                        "/stats/pools/pool[name = \"${POOL_NAME}\"]/stats/max_avail")

    BYTES_USED="${XPATH_ELEMENTS[j++]}"
    FREE="${XPATH_ELEMENTS[j++]}"

    echo "USED_MB=$(($BYTES_USED / 1024**2))
          TOTAL_MB=$((($BYTES_USED + $FREE) / 1024**2))
          FREE_MB=$(($FREE / 1024**2))" | tr -d ' '
else
    echo "$MONITOR_DATA"
    exit $MONITOR_STATUS
fi
