# -------------------------------------------------------------------------- 
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)            
#                                                                          
# Licensed under the Apache License, Version 2.0 (the "License"); you may 
# not use this file except in compliance with the License. You may obtain   
# a copy of the License at                                               
#                                                                          
# http://www.apache.org/licenses/LICENSE-2.0                              
#                                                                           
# Unless required by applicable law or agreed to in writing, software      
# distributed under the License is distributed on an "AS IS" BASIS,       
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and    
# limitations under the License.                                        
# -------------------------------------------------------------------------- 

import os
import sys
import shutil
sys.path.append("../../../share/scons")
from lex_bison import *

# This is the absolute path where the project is located
cwd="../../../"

# Environment that will be applied to each scons child
main_env=Environment()
main_env['ENV']['PATH']=os.environ['PATH']

# Add builders for flex and bison
add_lex(main_env)
add_bison(main_env)

# Include dirs
main_env.Append(CPPPATH=[
    cwd + '/include',
    '/usr/include/cppunit/',
])

# Library dirs
main_env.Append(LIBPATH=[
    cwd + '/src/common',
    cwd + '/src/log',
    cwd + '/src/pool',
    cwd + '/src/sql',
    cwd + '/src/pool/test',
    cwd + '/src/nebula',
])

main_env.Append(LIBS=[
    'nebula_pool',
    'nebula_common',
    'nebula_log',
    'nebula_core',
    'nebula_sql',
    'cppunit',
    'dl',
    'pthread',
    'test_object'
])

# Compile flags
main_env.Append(CPPFLAGS=[
    "-g",
    "-Wall"
])

# MYSQL
main_env.Append(LIBPATH=["/usr/lib/mysql"])
main_env.Append(CPPPATH=["/usr/include/mysql"])

sqlite=ARGUMENTS.get('sqlite', 'yes')
if sqlite=='yes':
    main_env.Append(CPPFLAGS=["-DSQLITE_DB"])
    main_env.Append(LIBS=[ 'sqlite3', ])

# MySQL
mysql=ARGUMENTS.get('mysql', 'no')
if mysql=='yes':
    main_env.Append(CPPFLAGS=["-DMYSQL_DB"])
    main_env.Append(LIBS=[ 'mysqlclient', ])


main_env.StaticLibrary('test_object', ['TestPoolSQL.cc', 'TestPoolSQL.h'])
main_env.Program('test','pool.cc')

