# -------------------------------------------------------------------------- 
# Copyright 2002-2010, OpenNebula Project Leads (OpenNebula.org)            
#                                                                          
# Licensed under the Apache License, Version 2.0 (the "License"); you may 
# not use this file except in compliance with the License. You may obtain   
# a copy of the License at                                               
#                                                                          
# http://www.apache.org/licenses/LICENSE-2.0                              
#                                                                           
# Unless required by applicable law or agreed to in writing, software      
# distributed under the License is distributed on an "AS IS" BASIS,       
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and    
# limitations under the License.                                        
# -------------------------------------------------------------------------- 

Import('env')

# Library dirs
env.Append(LIBPATH=[
    '.'
])

env.Append(LIBS=[
    'nebula_pool',
    'nebula_common',
    'nebula_log',
    'nebula_core',
    'nebula_sql',
    'cppunit',
    'dl',
    'pthread',
    'test_object'
])

sqlite=ARGUMENTS.get('sqlite', 'yes')
if sqlite=='yes':
    env.Append(CPPFLAGS=["-DSQLITE_DB"])
    env.Append(LIBS=[ 'sqlite3', ])

# MySQL
mysql=ARGUMENTS.get('mysql', 'no')
if mysql=='yes':
    env.Append(CPPFLAGS=["-DMYSQL_DB"])
    env.Append(LIBS=[ 'mysqlclient', ])


env.StaticLibrary('test_object', ['TestPoolSQL.cc', 'TestPoolSQL.h'])
env.Program('test','pool.cc')

