---

- name: Update util-linux
  package:
    name: util-linux
    state: latest
  register: pkg_result
  until: pkg_result is succeeded
  retries: 3
  delay: 10

- name: Install libgcrypt
  package:
    name: libgcrypt
    state: latest
  register: pkg_result
  until: pkg_result is succeeded
  retries: 3
  delay: 10
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenNebula node LXC package
  yum: name=opennebula-node-lxc state=latest
  register: yum_result
  until: yum_result is succeeded
  retries: 3
  delay: 10
