---

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: security.yml

- name: "create datastore for ONE_LOCATION"
  file: path={{ one_location }}/var/datastores owner=oneadmin group=oneadmin state=directory
  when: one_location is defined
