// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vdc

import (
	context "context"
	shared "github.com/OpenNebula/one/src/oca/go/src/goca/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// VdcServiceClient is the client API for VdcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VdcServiceClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	DelGroup(ctx context.Context, in *DelGroupRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	AddCluster(ctx context.Context, in *AddClusterRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	DelCluster(ctx context.Context, in *DelClusterRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	DelHost(ctx context.Context, in *DelHostRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	AddDatastore(ctx context.Context, in *AddDatastoreRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	DelDatastore(ctx context.Context, in *DelDatastoreRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	AddVnet(ctx context.Context, in *AddVnetRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	DelVnet(ctx context.Context, in *DelVnetRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
}

type vdcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVdcServiceClient(cc grpc.ClientConnInterface) VdcServiceClient {
	return &vdcServiceClient{cc}
}

func (c *vdcServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/AddGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) DelGroup(ctx context.Context, in *DelGroupRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/DelGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) AddCluster(ctx context.Context, in *AddClusterRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/AddCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) DelCluster(ctx context.Context, in *DelClusterRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/DelCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/AddHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) DelHost(ctx context.Context, in *DelHostRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/DelHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) AddDatastore(ctx context.Context, in *AddDatastoreRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/AddDatastore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) DelDatastore(ctx context.Context, in *DelDatastoreRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/DelDatastore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) AddVnet(ctx context.Context, in *AddVnetRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/AddVnet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) DelVnet(ctx context.Context, in *DelVnetRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/DelVnet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vdcServiceClient) PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.vdc.VdcService/PoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VdcServiceServer is the server API for VdcService service.
// All implementations must embed UnimplementedVdcServiceServer
// for forward compatibility
type VdcServiceServer interface {
	Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error)
	Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error)
	Info(context.Context, *InfoRequest) (*shared.ResponseXML, error)
	Update(context.Context, *UpdateRequest) (*shared.ResponseID, error)
	Rename(context.Context, *RenameRequest) (*shared.ResponseID, error)
	AddGroup(context.Context, *AddGroupRequest) (*shared.ResponseID, error)
	DelGroup(context.Context, *DelGroupRequest) (*shared.ResponseID, error)
	AddCluster(context.Context, *AddClusterRequest) (*shared.ResponseID, error)
	DelCluster(context.Context, *DelClusterRequest) (*shared.ResponseID, error)
	AddHost(context.Context, *AddHostRequest) (*shared.ResponseID, error)
	DelHost(context.Context, *DelHostRequest) (*shared.ResponseID, error)
	AddDatastore(context.Context, *AddDatastoreRequest) (*shared.ResponseID, error)
	DelDatastore(context.Context, *DelDatastoreRequest) (*shared.ResponseID, error)
	AddVnet(context.Context, *AddVnetRequest) (*shared.ResponseID, error)
	DelVnet(context.Context, *DelVnetRequest) (*shared.ResponseID, error)
	PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error)
	mustEmbedUnimplementedVdcServiceServer()
}

// UnimplementedVdcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVdcServiceServer struct {
}

func (UnimplementedVdcServiceServer) Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedVdcServiceServer) Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVdcServiceServer) Info(context.Context, *InfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVdcServiceServer) Update(context.Context, *UpdateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVdcServiceServer) Rename(context.Context, *RenameRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedVdcServiceServer) AddGroup(context.Context, *AddGroupRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroup not implemented")
}
func (UnimplementedVdcServiceServer) DelGroup(context.Context, *DelGroupRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelGroup not implemented")
}
func (UnimplementedVdcServiceServer) AddCluster(context.Context, *AddClusterRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCluster not implemented")
}
func (UnimplementedVdcServiceServer) DelCluster(context.Context, *DelClusterRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCluster not implemented")
}
func (UnimplementedVdcServiceServer) AddHost(context.Context, *AddHostRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHost not implemented")
}
func (UnimplementedVdcServiceServer) DelHost(context.Context, *DelHostRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelHost not implemented")
}
func (UnimplementedVdcServiceServer) AddDatastore(context.Context, *AddDatastoreRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDatastore not implemented")
}
func (UnimplementedVdcServiceServer) DelDatastore(context.Context, *DelDatastoreRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelDatastore not implemented")
}
func (UnimplementedVdcServiceServer) AddVnet(context.Context, *AddVnetRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVnet not implemented")
}
func (UnimplementedVdcServiceServer) DelVnet(context.Context, *DelVnetRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelVnet not implemented")
}
func (UnimplementedVdcServiceServer) PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolInfo not implemented")
}
func (UnimplementedVdcServiceServer) mustEmbedUnimplementedVdcServiceServer() {}

// UnsafeVdcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VdcServiceServer will
// result in compilation errors.
type UnsafeVdcServiceServer interface {
	mustEmbedUnimplementedVdcServiceServer()
}

func RegisterVdcServiceServer(s *grpc.Server, srv VdcServiceServer) {
	s.RegisterService(&_VdcService_serviceDesc, srv)
}

func _VdcService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/AddGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).AddGroup(ctx, req.(*AddGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_DelGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).DelGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/DelGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).DelGroup(ctx, req.(*DelGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_AddCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).AddCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/AddCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).AddCluster(ctx, req.(*AddClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_DelCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).DelCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/DelCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).DelCluster(ctx, req.(*DelClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_AddHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).AddHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/AddHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).AddHost(ctx, req.(*AddHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_DelHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).DelHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/DelHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).DelHost(ctx, req.(*DelHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_AddDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).AddDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/AddDatastore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).AddDatastore(ctx, req.(*AddDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_DelDatastore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelDatastoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).DelDatastore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/DelDatastore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).DelDatastore(ctx, req.(*DelDatastoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_AddVnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).AddVnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/AddVnet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).AddVnet(ctx, req.(*AddVnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_DelVnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelVnetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).DelVnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/DelVnet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).DelVnet(ctx, req.(*DelVnetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VdcService_PoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdcServiceServer).PoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vdc.VdcService/PoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdcServiceServer).PoolInfo(ctx, req.(*PoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VdcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "one.vdc.VdcService",
	HandlerType: (*VdcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _VdcService_Allocate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VdcService_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _VdcService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VdcService_Update_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _VdcService_Rename_Handler,
		},
		{
			MethodName: "AddGroup",
			Handler:    _VdcService_AddGroup_Handler,
		},
		{
			MethodName: "DelGroup",
			Handler:    _VdcService_DelGroup_Handler,
		},
		{
			MethodName: "AddCluster",
			Handler:    _VdcService_AddCluster_Handler,
		},
		{
			MethodName: "DelCluster",
			Handler:    _VdcService_DelCluster_Handler,
		},
		{
			MethodName: "AddHost",
			Handler:    _VdcService_AddHost_Handler,
		},
		{
			MethodName: "DelHost",
			Handler:    _VdcService_DelHost_Handler,
		},
		{
			MethodName: "AddDatastore",
			Handler:    _VdcService_AddDatastore_Handler,
		},
		{
			MethodName: "DelDatastore",
			Handler:    _VdcService_DelDatastore_Handler,
		},
		{
			MethodName: "AddVnet",
			Handler:    _VdcService_AddVnet_Handler,
		},
		{
			MethodName: "DelVnet",
			Handler:    _VdcService_DelVnet_Handler,
		},
		{
			MethodName: "PoolInfo",
			Handler:    _VdcService_PoolInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vdc.proto",
}
