---
version: 2
playbook: default

networks:
  - name: "nat"
    vn_mad: dummy
    bridge: br0
    dns: "8.8.8.8 8.8.4.4"
    gateway: "192.168.150.1"
    description: "Host-only networking with NAT"
    ar:
      - ip: "192.168.150.2"
        size: 253
        type: IP4
