---
- hosts: nodes
  roles:
    - ddc
    - opennebula-repository
    - { role: opennebula-node-kvm, when: oneprovision_hypervisor == 'kvm' }
    - { role: opennebula-node-lxc, when: oneprovision_hypervisor == 'lxc' }
    - opennebula-ssh
    - role: iptables
      iptables_base_rules_services:
        - { protocol: 'tcp', port: 22 }
        # TCP/179 bgpd (TODO: only needed on Route Refector(s))
        - { protocol: 'tcp', port: 179 }
        # TCP/8742 default VXLAN port on Linux (UDP/4789 default IANA)
        - { protocol: 'udp', port: 8472 }
        # Port 16509 is needed for connecting to the destination host by using TLS.
        - { protocol: 'tcp', port: 16509 }
        # Port 16514 is needed for connecting to the destination host by using TCP.
        - { protocol: 'tcp', port: 16514 }
        # Ports 49152-49215 are needed by QEMU for transferring the memory and disk migration data.
        - { protocol: 'tcp', port: '49152:49215' }
    - role: frr
      #bond0_0 is attached to the project private network
      frr_iface: 'bond0_0'
      # Use /25 for the internal management network address
      frr_prefix_length: 25
