// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vntemplate

import (
	context "context"
	shared "github.com/OpenNebula/one/src/oca/go/src/goca/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// VNTemplateServiceClient is the client API for VNTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VNTemplateServiceClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Instantiate(ctx context.Context, in *InstantiateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
}

type vNTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVNTemplateServiceClient(cc grpc.ClientConnInterface) VNTemplateServiceClient {
	return &vNTemplateServiceClient{cc}
}

func (c *vNTemplateServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Chmod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Chown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Clone(ctx context.Context, in *CloneRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Clone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) Instantiate(ctx context.Context, in *InstantiateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/Instantiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vNTemplateServiceClient) PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.vntemplate.VNTemplateService/PoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VNTemplateServiceServer is the server API for VNTemplateService service.
// All implementations must embed UnimplementedVNTemplateServiceServer
// for forward compatibility
type VNTemplateServiceServer interface {
	Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error)
	Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error)
	Info(context.Context, *InfoRequest) (*shared.ResponseXML, error)
	Update(context.Context, *UpdateRequest) (*shared.ResponseID, error)
	Rename(context.Context, *RenameRequest) (*shared.ResponseID, error)
	Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error)
	Chown(context.Context, *ChownRequest) (*shared.ResponseID, error)
	Lock(context.Context, *LockRequest) (*shared.ResponseID, error)
	Unlock(context.Context, *UnlockRequest) (*shared.ResponseID, error)
	Clone(context.Context, *CloneRequest) (*shared.ResponseID, error)
	Instantiate(context.Context, *InstantiateRequest) (*shared.ResponseID, error)
	PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error)
	mustEmbedUnimplementedVNTemplateServiceServer()
}

// UnimplementedVNTemplateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVNTemplateServiceServer struct {
}

func (UnimplementedVNTemplateServiceServer) Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedVNTemplateServiceServer) Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVNTemplateServiceServer) Info(context.Context, *InfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVNTemplateServiceServer) Update(context.Context, *UpdateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVNTemplateServiceServer) Rename(context.Context, *RenameRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedVNTemplateServiceServer) Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chmod not implemented")
}
func (UnimplementedVNTemplateServiceServer) Chown(context.Context, *ChownRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chown not implemented")
}
func (UnimplementedVNTemplateServiceServer) Lock(context.Context, *LockRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedVNTemplateServiceServer) Unlock(context.Context, *UnlockRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedVNTemplateServiceServer) Clone(context.Context, *CloneRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedVNTemplateServiceServer) Instantiate(context.Context, *InstantiateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Instantiate not implemented")
}
func (UnimplementedVNTemplateServiceServer) PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolInfo not implemented")
}
func (UnimplementedVNTemplateServiceServer) mustEmbedUnimplementedVNTemplateServiceServer() {}

// UnsafeVNTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VNTemplateServiceServer will
// result in compilation errors.
type UnsafeVNTemplateServiceServer interface {
	mustEmbedUnimplementedVNTemplateServiceServer()
}

func RegisterVNTemplateServiceServer(s *grpc.Server, srv VNTemplateServiceServer) {
	s.RegisterService(&_VNTemplateService_serviceDesc, srv)
}

func _VNTemplateService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Chmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Chmod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Chmod(ctx, req.(*ChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Chown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Chown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Chown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Chown(ctx, req.(*ChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Clone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Clone(ctx, req.(*CloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_Instantiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).Instantiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/Instantiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).Instantiate(ctx, req.(*InstantiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VNTemplateService_PoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VNTemplateServiceServer).PoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.vntemplate.VNTemplateService/PoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VNTemplateServiceServer).PoolInfo(ctx, req.(*PoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VNTemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "one.vntemplate.VNTemplateService",
	HandlerType: (*VNTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _VNTemplateService_Allocate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VNTemplateService_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _VNTemplateService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VNTemplateService_Update_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _VNTemplateService_Rename_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _VNTemplateService_Chmod_Handler,
		},
		{
			MethodName: "Chown",
			Handler:    _VNTemplateService_Chown_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _VNTemplateService_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _VNTemplateService_Unlock_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _VNTemplateService_Clone_Handler,
		},
		{
			MethodName: "Instantiate",
			Handler:    _VNTemplateService_Instantiate_Handler,
		},
		{
			MethodName: "PoolInfo",
			Handler:    _VNTemplateService_PoolInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vntemplate.proto",
}
