#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    DATASTORES=/var/lib/one/datastores
    LIB_LOCATION=/usr/lib/one
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    DATASTORES=$ONE_LOCATION/var/datastores
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh

# -------- Get image and datastore arguments from OpenNebula core ------------

DRV_ACTION=`cat -`
ID=$1

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TARGET_SNAPSHOT \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TM_MAD )

BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
DISK_SRC="${XPATH_ELEMENTS[j++]}"
SNAP_ID="${XPATH_ELEMENTS[j++]}"
TM_MAD="${XPATH_ELEMENTS[j++]}"

SRC_PATH=`arg_path $SRC`

SYSTEM_DS_PATH=$(dirname ${SRC_PATH})

SNAP_DIR="${DISK_SRC}.snap"
SNAP_PATH="${SNAP_DIR}/${SNAP_ID}"

if [ "$TM_MAD" = "qcow2" ]; then
    SNAP_ID_SCRIPT=$(cat <<EOF
set -e -o pipefail
ls $SNAP_DIR | grep '^[[:digit:]]*\$' | sort -n | tail -n 1
EOF
)
    if [ -n "$BRIDGE_LIST" ]; then
        DST_HOST=`get_destination_host $ID`

        ACTIVE_SNAP_ID=$(ssh_monitor_and_log "$DST_HOST" "$SNAP_ID_SCRIPT" "Error get active snapshot ID" 2>&1)
        ACTIVE_SNAP_PATH="${SNAP_DIR}/${ACTIVE_SNAP_ID}"

        ssh_exec_and_log "$DST_HOST" "rm $ACTIVE_SNAP_PATH" \
            "Error deleting $ACTIVE_SNAP_PATH"

        ssh_exec_and_log "$DST_HOST" "qemu-img create -f qcow2 -o backing_fmt=qcow2 -b $SNAP_PATH $ACTIVE_SNAP_PATH" \
            "Error reverting snapshot to $SNAP_PATH"
    else
        ACTIVE_SNAP_ID=$(monitor_and_log "$SNAP_ID_SCRIPT" "Error get active snapshot ID" 2>&1)
        ACTIVE_SNAP_PATH="${SNAP_DIR}/${ACTIVE_SNAP_ID}"

        exec_and_log "rm ${ACTIVE_SNAP_PATH}" \
            "Error deleting $ACTIVE_SNAP_PATH"

        exec_and_log "qemu-img create -f qcow2 -o backing_fmt=qcow2 -b ${SNAP_PATH} ${ACTIVE_SNAP_PATH}" \
            "Error reverting snapshot to $SNAP_PATH"
    fi
else
    if [ -n "$BRIDGE_LIST" ]; then
        DST_HOST=`get_destination_host $ID`

        ssh_exec_and_log "$DST_HOST" "cp -f ${SNAP_PATH} ${DISK_SRC}.tmp" \
            "Error copying snapshot $SNAP_PATH"

        ssh_exec_and_log "$DST_HOST" "mv ${DISK_SRC}.tmp ${DISK_SRC}" \
            "Error moving to $DISK_SRC"
    else
        exec_and_log "cp -f ${SNAP_PATH} ${DISK_SRC}.tmp" \
            "Error copying snapshot $SNAP_PATH"

        exec_and_log "mv ${DISK_SRC}.tmp ${DISK_SRC}" \
            "Error moving to $DISK_SRC"

        rm -f ${DISK_SRC}.md5sum
    fi
fi
