#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [ -z "${ONE_LOCATION}" ]; then
    DRIVERRC=/etc/one/vmm_ec2/vmm_ec2rc
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one
else
    DRIVERRC=$ONE_LOCATION/etc/vmm_ec2/vmm_ec2rc
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var
fi

. $MADCOMMON

# Export the vmm_mad specific rc
export_rc_vars $DRIVERRC

# Go to ONE_LOCATION
cd $VAR_LOCATION

while getopts u:h:k:c: option $@
do
    case $option in
    u)  export EC2_URL="$OPTARG";;
    h)  export EC2_HOME="$OPTARG";;
    k)  export EC2_PRIVATE_KEY="$OPTARG";;
    c)  export EC2_CERT="$OPTARG";;
    esac
done

# Execute the actual MAD
execute_mad $*
