# Sunstone server configuration
# Time configuration: use 'browser' to use browser's local time, 'os' to use server OS timezone, or 'timezone' to set explicit timezone.
time_configuration_source = os

# Explicit timezone name if time_configuration_source is 'timezone'. E.g., 'America/New_York'
timezone = ""

# Date format: '24h' (default) or '12h'
date_format = 24h