# SConstruct for src/vm

Import('env')

lib_name='nebula_lcm'

# Sources to generate the library
source_files=[
	'LifeCycleManager.cc',
	'LifeCycleActions.cc',	
	'LifeCycleStates.cc',	
]

# Build library
env.StaticLibrary(lib_name, source_files)
