---
- name: Validate group_vars parameters
  assert:
    that:
      -  "{{ sys_ds_ids }} is defined"
      -  "{{ first_host }} is not none"

- name: Update replica host
  local_action:
    module: shell
    cmd: onedatastore update {{ item }}
  environment:
    EDITOR: "sed -i -e 's/REPLICA_HOST=.*/REPLICA_HOST={{ first_host }}/'"
  become: false
  with_items: "{{ sys_ds_ids }}"

