#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to register a new IP network in the IPAM. The network may
# be selected by a pool of free networks or if an specific network is requested
# its availability maybe checked by the IPAM driver.
#
# The IPAM driver must return an OpenNebula AddressRange definition, potentially
# augmented with network specific variables to be used by VMs (e.g. GATEWAYS,
# MASK...)
#
# STDIN Input:
#   - Base64 encoded XML with AR request
#
# XML format
#  <IPAM_DRIVER_ACTION_DATA>
#    <AR>
#      <AWS_ALLOCATION_ID>aws allocation id</AWS_ALLOCATION_ID>
#      <AWS_ACCESS_KEY>access key</AWS_ACCESSKEY>
#      <AWS_SECRET_KEY>secret key</AWS_SECRET_KEY>
#      <AWS_REGION>region</AWS_REGION>
#    </AR>
#  </IPAM_DRIVER_ACTION_DATA>
################################################################################

ONE_LOCATION = ENV['ONE_LOCATION'] unless defined?(ONE_LOCATION)

if !ONE_LOCATION
    LIB_LOCATION      ||= '/usr/lib/one'
    RUBY_LIB_LOCATION ||= '/usr/lib/one/ruby'
    GEMS_LOCATION     ||= '/usr/share/one/gems'
    DRIVERS_PATH      ||= '/usr/share/one/oneform/drivers'
else
    LIB_LOCATION      ||= ONE_LOCATION + '/lib'
    RUBY_LIB_LOCATION ||= ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     ||= ONE_LOCATION + '/share/gems'
    DRIVERS_PATH      ||= ONE_LOCATION + '/share/oneform/drivers'
end

# %%RUBYGEMS_SETUP_BEGIN%%
require 'load_opennebula_paths'
# %%RUBYGEMS_SETUP_END%%

$LOAD_PATH << RUBY_LIB_LOCATION

require 'base64'
require 'nokogiri'
require 'aws-sdk-ec2'
require 'opennebula'
require 'opennebula/oneform_client'

begin
    data = Nokogiri::XML(Base64.decode64(STDIN.read))

    # --------------------------------------------------------------------------
    # Get connection details for the provider
    # --------------------------------------------------------------------------
    provision_id = data.xpath('//AR/PROVISION_ID').text

    if provision_id.empty?
        STDERR.puts 'Missing provision id in address range'
        exit(-1)
    end

    client   = OneForm::Client.new
    document = client.get_provision(provision_id)

    if document.key?(:err_code)
        STDERR.puts "Error retrieving provision #{provision_id}: #{provision[:message]}"
        exit(-1)
    end

    provision = document[:TEMPLATE][:PROVISION_BODY]
    document  = client.get_provider(provision[:provider_id])

    if document.key?(:err_code)
        STDERR.puts "Error retrieving provider #{provision[:provider_id]}: #{document[:message]}"
        exit(-1)
    end

    provider = document[:TEMPLATE][:PROVIDER_BODY]
    connect  = provider[:connection]

    options = {
        :access_key_id     => connect[:access_key],
        :secret_access_key => connect[:secret_key],
        :region            => connect[:region]
    }

    # --------------------------------------------------------------------------
    # Connect to AWS delete the IP allocation
    # --------------------------------------------------------------------------
    allocation_id = data.xpath('//AR/AWS_ALLOCATION_ID').text

    unless allocation_id
        STDERR.puts 'AWS_ALLOCATION_ID not found in AR'
        exit(-1)
    end

    Aws.config.merge!(options)

    ec2 = Aws::EC2::Resource.new.client

    ec2.release_address({ :allocation_id => allocation_id })
rescue Aws::EC2::Errors::AuthFailure
    puts 'The IP address has already been released or belongs to another account.'
rescue Aws::EC2::Errors::InvalidAllocationIDNotFound
    puts 'The specified allocation ID does not exist.'
rescue StandardError => e
    STDERR.puts e.to_s
    exit(-1)
end
