#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#Setup driver variables
if [ -z "${ONE_LOCATION}" ]; then
    DRIVERRC=/etc/one/${DRIVER_NAME}/${DRIVER_NAME}rc
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one
else
    DRIVERRC=$ONE_LOCATION/etc/${DRIVER_NAME}/${DRIVER_NAME}rc
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var
fi

. $MADCOMMON

# Export the im_mad specific rc

export_rc_vars $DRIVERRC

# Go to var directory ONE_LOCATION/var or /var/lib/one
cd $VAR_LOCATION

LOG_FILE=$DRIVER_NAME

# Execute the actual MAD
execute_mad $*
