---

- name: Uninstall firewalld
  package:
    name: firewalld
    state: absent

- name: Install iptables-services
  package:
    name: iptables-services
    state: present

- name: Create persistent rules configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'rules.v4.j2', dest: '/etc/sysconfig/iptables' }
    - { src: 'rules.v6.j2', dest: '/etc/sysconfig/ip6tables' }

- name: Enable iptables services
  service:
    name: iptables
    enabled: true
  with_items:
    - iptables
    - ip6tables
