---
###############################################################################
# Valid defaults
###############################################################################

# Whether to use the ev package for kvm
opennebula_node_kvm_use_ev: False

# Enable nested KVM virtualization
opennebula_node_kvm_param_nested: False

# Enable KVM configuration
opennebula_node_kvm_manage_kvm: True

# SELinux booleans to configure
opennebula_node_selinux_booleans:
  - { name: 'virt_use_nfs', state: 'yes' }
