#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"]

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby"
    ETC_LOCATION="/etc/one/"
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby"
    ETC_LOCATION=ONE_LOCATION+"/etc/"
end

$: << RUBY_LIB_LOCATION

require 'opennebula/server_x509_auth'
require 'scripts_common'
require 'rexml/document'
require 'opennebula/error'
require 'opennebula/xml_utils'

begin
    xml = OpenNebula::XMLElement.new
    xml.initialize_xml(STDIN.read, 'AUTHN')

    user   = xml['/AUTHN/USERNAME'] # username as registered in OpenNebula
    pass   = xml['/AUTHN/PASSWORD'] # password for this user
    secret = xml['/AUTHN/SECRET']   # Base64 encoded secret as obtained from login_token
rescue
    STDERR.puts "Invalid XML input"
    exit(-1)
end

#OpenNebula.log_debug("Authenticating #{user}, with password #{pass} (#{secret})")

begin
    server_auth = OpenNebula::ServerX509Auth.new
    dsecret     = Base64::decode64(secret)

    rc = server_auth.authenticate(user, pass, dsecret)
rescue => e
    OpenNebula.error_message e.message
    exit -1
end

if rc == true
    exit 0
else
    OpenNebula.error_message rc
    exit -1
end
