// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package datastore

import (
	context "context"
	shared "github.com/OpenNebula/one/src/oca/go/src/goca/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DatastoreServiceClient is the client API for DatastoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatastoreServiceClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
}

type datastoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatastoreServiceClient(cc grpc.ClientConnInterface) DatastoreServiceClient {
	return &datastoreServiceClient{cc}
}

func (c *datastoreServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Chmod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Chown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreServiceClient) PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.datastore.DatastoreService/PoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatastoreServiceServer is the server API for DatastoreService service.
// All implementations must embed UnimplementedDatastoreServiceServer
// for forward compatibility
type DatastoreServiceServer interface {
	Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error)
	Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error)
	Info(context.Context, *InfoRequest) (*shared.ResponseXML, error)
	Update(context.Context, *UpdateRequest) (*shared.ResponseID, error)
	Rename(context.Context, *RenameRequest) (*shared.ResponseID, error)
	Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error)
	Chown(context.Context, *ChownRequest) (*shared.ResponseID, error)
	Enable(context.Context, *EnableRequest) (*shared.ResponseID, error)
	PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error)
	mustEmbedUnimplementedDatastoreServiceServer()
}

// UnimplementedDatastoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDatastoreServiceServer struct {
}

func (UnimplementedDatastoreServiceServer) Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedDatastoreServiceServer) Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDatastoreServiceServer) Info(context.Context, *InfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedDatastoreServiceServer) Update(context.Context, *UpdateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDatastoreServiceServer) Rename(context.Context, *RenameRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedDatastoreServiceServer) Chmod(context.Context, *ChmodRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chmod not implemented")
}
func (UnimplementedDatastoreServiceServer) Chown(context.Context, *ChownRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chown not implemented")
}
func (UnimplementedDatastoreServiceServer) Enable(context.Context, *EnableRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedDatastoreServiceServer) PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolInfo not implemented")
}
func (UnimplementedDatastoreServiceServer) mustEmbedUnimplementedDatastoreServiceServer() {}

// UnsafeDatastoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatastoreServiceServer will
// result in compilation errors.
type UnsafeDatastoreServiceServer interface {
	mustEmbedUnimplementedDatastoreServiceServer()
}

func RegisterDatastoreServiceServer(s *grpc.Server, srv DatastoreServiceServer) {
	s.RegisterService(&_DatastoreService_serviceDesc, srv)
}

func _DatastoreService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Chmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Chmod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Chmod(ctx, req.(*ChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Chown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Chown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Chown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Chown(ctx, req.(*ChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreService_PoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreServiceServer).PoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.datastore.DatastoreService/PoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreServiceServer).PoolInfo(ctx, req.(*PoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatastoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "one.datastore.DatastoreService",
	HandlerType: (*DatastoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _DatastoreService_Allocate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DatastoreService_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _DatastoreService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DatastoreService_Update_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _DatastoreService_Rename_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _DatastoreService_Chmod_Handler,
		},
		{
			MethodName: "Chown",
			Handler:    _DatastoreService_Chown_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _DatastoreService_Enable_Handler,
		},
		{
			MethodName: "PoolInfo",
			Handler:    _DatastoreService_PoolInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datastore.proto",
}
