#!/bin/bash
#
#    /etc/rc.d/init.d/opennebula-gate
#
# Starts the OpenNebula gate Server
#
# chkconfig: 345 66 34
# description: Starts the OneGate daemon
# processname: opennebula-gate

### BEGIN INIT INFO
# Provides: opennebula-gate
# Required-Start: $local_fs $remote_fs oned
# Required-Stop: $local_fs $remote_fs oned
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop opennebula-gate
# Description: start and stop opennebula-gate
### END INIT INFO

prog="opennebula-gate"

SERVER_BIN=/usr/bin/onegate-server
SERVER_PROGRAM=onegate-server.rb
LOCKFILE=/var/lock/subsys/${prog}
PID_FILE=/var/run/${prog}.pid

# Source function library.
. /etc/rc.d/init.d/functions


RETVAL=0

check() {
    # Check that we're a privileged user
    [ `id -u` = 0 ] || exit 4

    # Check if $SERVER_BIN is executable
    test -x $SERVER_BIN || exit 5
}

start() {
    check

    echo -n $"Starting $prog Server: "
    daemon --user oneadmin $SERVER_BIN start
    RETVAL=$?

	echo
    [ $RETVAL -eq 0 ] && {
		touch $LOCKFILE
		echo $(ps -ef|grep $SERVER_PROGRAM | awk '{print $2}') > $PID_FILE
	}

    return $RETVAL
}

stop() {

    check

    echo -n $"Stopping $prog Server daemon: "
    daemon --user oneadmin $SERVER_BIN stop
    RETVAL=$?

    [ $RETVAL -eq 0 ] && success || failure
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE $PID_FILE

    return $RETVAL
}

restart() {
    stop
    start
}


case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    restart
    ;;
status)
    status $prog
    RETVAL=$?
    ;;
*)
    echo $"Usage: $0 {start|stop|status|restart}"
    RETVAL=2
esac

exit $RETVAL
