#!/bin/sh

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [ ! -t 0 ]; then
    tmpxml="$(mktemp -t failmigrate-${4}-XXXXXXXX)"
    cat >"$tmpxml"
    TEMPLATE_64="$tmpxml"
    SYSTEM_MAD="$6"
    trap "rm -rf \"$tmpxml\"" EXIT TERM INT HUP QUIT 
else
    TEMPLATE_64="$6"
    SYSTEM_MAD="$7"
fi

migrate_other "$@"

exit 0
