// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package host

import (
	context "context"
	shared "github.com/OpenNebula/one/src/oca/go/src/goca/api/shared"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*shared.ResponseID, error)
	Monitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
	PoolMonitoring(ctx context.Context, in *PoolMonitoringRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*shared.ResponseID, error) {
	out := new(shared.ResponseID)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Monitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.host.HostService/Monitoring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) PoolInfo(ctx context.Context, in *PoolInfoRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.host.HostService/PoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) PoolMonitoring(ctx context.Context, in *PoolMonitoringRequest, opts ...grpc.CallOption) (*shared.ResponseXML, error) {
	out := new(shared.ResponseXML)
	err := c.cc.Invoke(ctx, "/one.host.HostService/PoolMonitoring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility
type HostServiceServer interface {
	Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error)
	Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error)
	Info(context.Context, *InfoRequest) (*shared.ResponseXML, error)
	Update(context.Context, *UpdateRequest) (*shared.ResponseID, error)
	Rename(context.Context, *RenameRequest) (*shared.ResponseID, error)
	Status(context.Context, *StatusRequest) (*shared.ResponseID, error)
	Monitoring(context.Context, *MonitoringRequest) (*shared.ResponseXML, error)
	PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error)
	PoolMonitoring(context.Context, *PoolMonitoringRequest) (*shared.ResponseXML, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHostServiceServer struct {
}

func (UnimplementedHostServiceServer) Allocate(context.Context, *AllocateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedHostServiceServer) Delete(context.Context, *DeleteRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedHostServiceServer) Info(context.Context, *InfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedHostServiceServer) Update(context.Context, *UpdateRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedHostServiceServer) Rename(context.Context, *RenameRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedHostServiceServer) Status(context.Context, *StatusRequest) (*shared.ResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHostServiceServer) Monitoring(context.Context, *MonitoringRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Monitoring not implemented")
}
func (UnimplementedHostServiceServer) PoolInfo(context.Context, *PoolInfoRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolInfo not implemented")
}
func (UnimplementedHostServiceServer) PoolMonitoring(context.Context, *PoolMonitoringRequest) (*shared.ResponseXML, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PoolMonitoring not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s *grpc.Server, srv HostServiceServer) {
	s.RegisterService(&_HostService_serviceDesc, srv)
}

func _HostService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Monitoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Monitoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/Monitoring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Monitoring(ctx, req.(*MonitoringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_PoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).PoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/PoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).PoolInfo(ctx, req.(*PoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_PoolMonitoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolMonitoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).PoolMonitoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one.host.HostService/PoolMonitoring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).PoolMonitoring(ctx, req.(*PoolMonitoringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "one.host.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _HostService_Allocate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _HostService_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _HostService_Info_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _HostService_Update_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _HostService_Rename_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _HostService_Status_Handler,
		},
		{
			MethodName: "Monitoring",
			Handler:    _HostService_Monitoring_Handler,
		},
		{
			MethodName: "PoolInfo",
			Handler:    _HostService_PoolInfo_Handler,
		},
		{
			MethodName: "PoolMonitoring",
			Handler:    _HostService_PoolMonitoring_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host.proto",
}
