#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# ln fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

   #-v ------------------------------------------------------------------------------
# Retrieve needed information, Example (same for SRC)
#  DST       : esx1:/vmfs/volumes/105/90/disk.0
#  SRC       : one:/vmfs/volumes/104/84045f4a
#  DST_PATH  : /vmfs/volumes/105/90/disk.0
#  DST_DIR   : /vmfs/volumes/105/90/
#  DST_HOST  : esx1
#
#  DISK_TYPE: CDROM if it is a cd (not a directory)
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
DST_PATH=`arg_path $DST`

DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

DISK_TYPE=$(disk_type)

#-------------------------------------------------------------------------------
# Link (ln) SRC into DST
#-------------------------------------------------------------------------------

if [ "$DISK_TYPE" != "CDROM" ]; then
    log "Link all files in $SRC_PATH to $DST_PATH"

    LINK_SCRIPT=$(cat <<EOF
if [ ! -d $DST_PATH ]; then
   mkdir -p $DST_PATH
fi

for file in \$(find $SRC_PATH -type f); do
    (cd $DST_PATH ; ln -sf \$file)
done
EOF
)
    ssh_exec_and_log $DST_HOST "$LINK_SCRIPT" \
            "Error linking files from $SRC_PATH to $DST_PATH"
else
    log "Link CD-ROM from $SRC_PATH to $DST_PATH"

    LINK_SCRIPT=$(cat <<EOF
if [ ! -d $DST_DIR ]; then
   mkdir -p $DST_DIR
fi

rm -f $DST_PATH.iso
ln -s $SRC_PATH $DST_PATH.iso
EOF
)
    ssh_exec_and_log $DST_HOST "$LINK_SCRIPT" \
            "Error linking CDROM ISO file from $SRC_PATH to $DST_PATH"
fi

exit 0
