#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mvds host:remote_system_ds/disk.i fe:SOURCE vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    VMWARERC=/etc/one/vmwarerc
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    VMWARERC=$ONE_LOCATION/etc/vmwarerc
fi

. $TMCOMMON

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

function mvds_ssh {

MVSCRIPT=$(cat <<EOF
SRC_READLN=\$($READLINK -f $SRC_PATH)
DST_READLN=\$($READLINK -f $DST_PATH)

if [ \( -L $SRC \) -a \( "$SRC_READLN" = "$DST_READLN" \) ] ; then
    echo "Not moving files to image repo, they are the same"
else
    $VMKFSTOOLS -U $DST_DISK
    $VMKFSTOOLS -i $SRC_DISK -d thin $DST_DISK
fi

if [ -d $DST_PATH ]; then
    chmod 0770 $DST_PATH
else
    chmod 0660 $DST_PATH
fi
EOF
)

ssh_exec_and_log $SRC_HOST "$MVSCRIPT" \
        "Could not move image $SRC_DISK_VMW to $DST_DISK_VMW"
}

#-------------------------------------------------------------------------------

function mvds_local {

$VMKFSTOOLS $VI_PARAMS -U $DST_DISK_VMW &> /dev/null

exec_and_log "$VMKFSTOOLS $VI_PARAMS -i $SRC_DISK_VMW -d thin $DST_DISK_VMW" \
                 "Could not move image $SRC_DISK_VMW to $DST_DISK_VMW"
}

#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Retrieve needed information, set dst path and dir
#-------------------------------------------------------------------------------
SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`
SRC_FOLDER=`basename $SRC_PATH`

DST_PATH=`arg_path $DST`
DST_HOST=$SRC_HOST
DST_FOLDER=`basename $DST_PATH`

USE_SSH=$(get_tm_use_ssh $DSID)

IMAGE_DS_NAME=`basename $(dirname $DST_PATH)`
SYSTEM_DS_NAME=`basename $(dirname $(dirname $SRC_PATH))`

# Paths for disks

SRC_DISK="/vmfs/volumes/$SYSTEM_DS_NAME/$VMID/$SRC_FOLDER/disk.vmdk"
SRC_DISK_VMW="[$SYSTEM_DS_NAME]$VMID/$SRC_FOLDER/disk.vmdk"

DST_DISK="/vmfs/volumes/$IMAGE_DS_NAME/$DST_FOLDER/disk.vmdk"
DST_DISK_VMW="[$IMAGE_DS_NAME]$DST_FOLDER/disk.vmdk"

#-------------------------------------------------------------------------------
# Set up datastore
#-------------------------------------------------------------------------------

vmfs_set_up

#-------------------------------------------------------------------------------
# Move the image back to the datastore
#-------------------------------------------------------------------------------

log "Moving $SRC_DISK_VMW to $DST_DISK_VMW"

if [ "$USE_SSH" == "yes" ]; then
    mvds_ssh
else
    mvds_local
fi

exit 0
