# SConstruct for src/pool

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

Import('sched_env')

lib_name='scheduler_pool'

source_files=[
    'AclXML.cc',
    'HostPoolXML.cc',
    'HostXML.cc',
    'VirtualMachinePoolXML.cc',
    'VirtualMachineXML.cc',
    'ClusterPoolXML.cc',
    'UserPoolXML.cc',
    'VMGroupPoolXML.cc',
    'VMGroupXML.cc',
    'DatastorePoolXML.cc',
    'DatastoreXML.cc',
    'VirtualNetworkPoolXML.cc',
    'VirtualNetworkXML.cc'
]

# Build library
sched_env.StaticLibrary(lib_name, source_files)
