# SConstruct for src/mad

Import('env')

lib_name='oneapi'

# Sources to generate the library
source_files=[
	'OneClient.cc',
	'OneClient_C_Wrapper.cc'
]

# Compiling flags
env.Append(CPPFLAGS=["-fPIC"])

# Build library
env.StaticLibrary(lib_name, source_files)
