.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECONE\-ATTACH\-VOLUME" "1" "July 2016" "" "econe-attach-volume(1) -- Attaches a DATABLOCK to an instance"
.
.SH "NAME"
\fBecone\-attach\-volume\fR \- Attaches a DATABLOCK to an instance
.
.SH "SYNOPSIS"
econe\-attach\-volume \fIOPTIONS\fR VOLUME\-ID
.
.P
Attaches a DATABLOCK to a running instance and exposes it as the specified device\. VOLUME\-ID: The ID of the DATABLOCK
.
.SH "OPTIONS"
.
.nf

 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-K, \-\-access\-key id       The username of the user
 \-S, \-\-secret\-key key      The sha1 hashed password of the user
 \-U, \-\-url url             Set url as the web service url to use
 \-i, \-\-instance instance_id The ID of the instance to attach the volume to
 \-d, \-\-device device       Specifies the device name to expose to the
                           instance\. Example: \-d /dev/sdf
.
.fi
.
.P
\fIvolume_id\fR
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 5\.0\.2 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
