.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECONE\-ALLOCATE\-ADDRESS" "1" "May 2016" "" "econe-allocate-address(1) -- Allocates a new elastic IP address for the user"
.
.SH "NAME"
\fBecone\-allocate\-address\fR \- Allocates a new elastic IP address for the user
.
.SH "SYNOPSIS"
econe\-allocate\-address \fIOPTIONS\fR
.
.P
Allocate a new elastic IP address for the user
.
.SH "OPTIONS"
.
.nf

 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-K, \-\-access\-key id       The username of the user
 \-S, \-\-secret\-key key      The sha1 hashed password of the user
 \-U, \-\-url url             Set url as the web service url to use
.
.fi
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.90\.0 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
