.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECONE\-DESCRIBE\-IMAGES" "1" "March 2015" "" "econe-describe-images(1) -- Lists all registered images belonging to one particular user"
.
.SH "SYNOPSIS"
econe\-describe\-images \fIOPTIONS\fR
.
.P
List and describe previously uploaded images of a user to be used with an OpenNebula Cloud\.
.
.SH "OPTIONS"
.
.nf

 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-K, \-\-access\-key id       The username of the user
 \-S, \-\-secret\-key key      The sha1 hashed password of the user
 \-U, \-\-url url             Set url as the web service url to use
.
.fi
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.12\.1 Copyright 2002\-2015, OpenNebula Project (OpenNebula\.org), C12G Labs
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
