.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ECONE\-DETACH\-VOLUME" "1" "October 2014" "" "econe-detach-volume(1) -- Detaches a DATABLOCK from an instance"
.
.SH "NAME"
\fBecone\-detach\-volume\fR
.
.SH "SYNOPSIS"
econe\-detach\-volume \fIOPTIONS\fR VOLUME\-ID
.
.P
Detaches a volume from an instance\. Make sure to unmount any file systems on the device within your operating system before detaching the volume VOLUME\-ID: The ID of the DATABLOCK
.
.SH "OPTIONS"
.
.nf

 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-K, \-\-access\-key id       The username of the user
 \-S, \-\-secret\-key key      The sha1 hashed password of the user
 \-U, \-\-url url             Set url as the web service url to use
 \-i, \-\-instance instance_id The ID of the instance to attach the volume to
 \-d, \-\-device device       Specifies the device name to expose to the
                           instance\. Example: \-d /dev/sdf
.
.fi
.
.P
\fIvolume_id\fR
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.9\.80 Copyright 2002\-2014, OpenNebula Project (OpenNebula\.org), C12G Labs
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
