.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONECLUSTER" "1" "April 2012" "" "onecluster(1) -- manages OpenNebula clusters"
.
.SH "NAME"
\fBonecluster\fR
.
.SH "SYNOPSIS"
\fBonecluster\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIname\fR
.
.IP "" 4
.
.nf

Creates a new Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|clusterid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list
.
.IP "" 4
.
.nf

Lists Clusters in the pool
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIclusterid\fR
.
.IP "" 4
.
.nf

Shows information for the given Cluster
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
addhost \fIclusterid\fR \fIhostid\fR
.
.IP "" 4
.
.nf

Adds a Host to the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delhost \fIclusterid\fR \fIhostid\fR
.
.IP "" 4
.
.nf

Deletes a Host from the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
adddatastore \fIclusterid\fR \fIdatastoreid\fR
.
.IP "" 4
.
.nf

Adds a Datastore to the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
deldatastore \fIclusterid\fR \fIdatastoreid\fR
.
.IP "" 4
.
.nf

Deletes a Datastore from the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
addvnet \fIclusterid\fR \fIvnetid\fR
.
.IP "" 4
.
.nf

Adds a Virtual Network to the given Cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delvnet \fIclusterid\fR \fIvnetid\fR
.
.IP "" 4
.
.nf

Deletes a Virtual Network from the given Cluster
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
clusterid
.
.IP "" 4
.
.nf

OpenNebula CLUSTER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
clusterid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula CLUSTER names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vnetid
.
.IP "" 4
.
.nf

OpenNebula VNET name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hostid
.
.IP "" 4
.
.nf

OpenNebula HOST name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
datastoreid
.
.IP "" 4
.
.nf

OpenNebula DATASTORE name or id
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
