.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEDATASTORE" "1" "April 2012" "" "onedatastore(1) -- manages OpenNebula datastores"
.
.SH "NAME"
\fBonedatastore\fR
.
.SH "SYNOPSIS"
\fBonedatastore\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-c, \-\-cluster id|name     Selects the cluster
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Creates a new Datastore from the given template file
valid options: cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|datastoreid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Datastore
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|datastoreid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the Datastore group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chown \fIrange|datastoreid_list\fR \fIuserid\fR [\fIgroupid\fR]
.
.IP "" 4
.
.nf

Changes the Datastore owner and group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chmod \fIrange|datastoreid_list\fR \fIoctet\fR
.
.IP "" 4
.
.nf

Changes the Datastore permissions
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list
.
.IP "" 4
.
.nf

Lists Datastores in the pool
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIdatastoreid\fR
.
.IP "" 4
.
.nf

Shows information for the given Datastore
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fIdatastoreid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
datastoreid
.
.IP "" 4
.
.nf

OpenNebula DATASTORE name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
datastoreid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula DATASTORE names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
clusterid
.
.IP "" 4
.
.nf

OpenNebula CLUSTER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
