.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEFLOW\-TEMPLATE" "1" "July 2014" "" "oneflow-template(1) -- Manage oneFlow Templates"
.
.SH "NAME"
\fBoneflow\-template\fR
.
.SH "SYNOPSIS"
\fBoneflow\-template\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-j, \-\-json                Print the resource in JSON
 \-t, \-\-top                 Top for the command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-s, \-\-server url          Service endpoint
 \-u, \-\-username name       User name
 \-p, \-\-password pass       User password
 \-V, \-\-version             Show version and copyright information
 \-h, \-\-help                Show this message
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
list List the available Service Templates valid options: json
.
.IP "\(bu" 4
top List the available Service Templates continuously valid options: json, top, delay
.
.IP "\(bu" 4
create \fIfile\fR Create a new Service Template valid options: json
.
.IP "\(bu" 4
show \fItemplateid\fR Show detailed information of a given Service Template valid options: json
.
.IP "\(bu" 4
delete \fIrange|templateid_list\fR Delete a given Service Template
.
.IP "\(bu" 4
instantiate \fItemplateid\fR [\fIfile\fR] Instantiate a Service Template valid options: json, top
.
.IP "\(bu" 4
chgrp \fIrange|templateid_list\fR \fIgroupid\fR Changes the service template group
.
.IP "\(bu" 4
chown \fIrange|templateid_list\fR \fIuserid\fR [\fIgroupid\fR] Changes the service template owner and group
.
.IP "\(bu" 4
chmod \fIrange|templateid_list\fR \fIoctet\fR Changes the service template permissions
.
.IP "\(bu" 4
update \fItemplateid\fR [\fIfile\fR] Update the template contents\. If a path is not provided the editor will be launched to modify the current content\.
.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "\(bu" 4
groupid OpenNebula GROUP name or id
.
.IP "\(bu" 4
userid OpenNebula USER name or id
.
.IP "\(bu" 4
templateid OpenNebula SERVICE TEMPLATE name or id
.
.IP "\(bu" 4
templateid_list Comma\-separated list of OpenNebula SERVICE TEMPLATE names or ids
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.8\.0 Copyright 2002\-2014, OpenNebula Project (OpenNebula\.org), C12G Labs
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
