.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEFLOW" "1" "May 2016" "" "oneflow(1) -- Manage oneFlow Services"
.
.SH "NAME"
\fBoneflow\fR \- Manage oneFlow Services
.
.SH "SYNOPSIS"
\fBoneflow\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-j, \-\-json                Print the resource in JSON
 \-t, \-\-top                 Top for the command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-f, \-\-force               Force the new cardinality even if it is outside
                           the limits
 \-p, \-\-period x            Seconds between each group of actions
 \-n, \-\-number x            Number of VMs to apply the action to each period
 \-s, \-\-server url          Service endpoint
 \-u, \-\-username name       User name
 \-p, \-\-password pass       User password
 \-V, \-\-version             Show version and copyright information
 \-h, \-\-help                Show this message
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
list List the available services valid options: json
.
.IP "\(bu" 4
show \fIservice_id\fR Show detailed information of a given service valid options: json
.
.IP "\(bu" 4
top [\fIservice_id\fR] Top the services or the extended information of the target service if a id is specified valid options: json, top, delay
.
.IP "\(bu" 4
delete \fIrange|service_id_list\fR Delete a given service
.
.IP "\(bu" 4
shutdown \fIrange|service_id_list\fR Shutdown a service\. From RUNNING or WARNING shuts down the Service
.
.IP "\(bu" 4
recover \fIrange|service_id_list\fR Recover a failed service, cleaning the failed VMs\. From FAILED_DEPLOYING continues deploying the Service From FAILED_SCALING continues scaling the Service From FAILED_UNDEPLOYING continues shutting down the Service From COOLDOWN the Service is set to running ignoring the cooldown duration From WARNING failed VMs are deleted, and new VMs are instantiated
.
.IP "\(bu" 4
scale \fIservice_id\fR \fIrole_name\fR \fIcardinality\fR Scale a role to the given cardinality valid options: force
.
.IP "\(bu" 4
chgrp \fIrange|service_id_list\fR \fIgroupid\fR Changes the service group
.
.IP "\(bu" 4
chown \fIrange|service_id_list\fR \fIuserid\fR [\fIgroupid\fR] Changes the service owner and group
.
.IP "\(bu" 4
chmod \fIrange|service_id_list\fR \fIoctet\fR Changes the service permissions
.
.IP "\(bu" 4
rename \fIservice_id\fR \fIname\fR Renames the Service
.
.IP "\(bu" 4
action \fIservice_id\fR \fIrole_name\fR \fIvm_action\fR Perform an action on all the Virtual Machines of a given role\. Actions supported: terminate,terminate\-hard,undeploy,undeploy\-hard,hold,release,stop,suspend,resume,reboot,reboot\-hard,poweroff,poweroff\-hard,snapshot\-create valid options: period, number
.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "\(bu" 4
groupid OpenNebula GROUP name or id
.
.IP "\(bu" 4
userid OpenNebula USER name or id
.
.IP "\(bu" 4
service_id OpenNebula SERVICE name or id
.
.IP "\(bu" 4
service_id_list Comma\-separated list of OpenNebula SERVICE names or ids
.
.IP "\(bu" 4
vm_action Actions supported: terminate, terminate\-hard, undeploy, undeploy\-hard, hold, release, stop, suspend, resume, reboot, reboot\-hard, poweroff, poweroff\-hard, snapshot\-create
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.90\.5 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
