.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEHOST" "1" "April 2012" "" "onehost(1) -- manages OpenNebula hosts"
.
.SH "NAME"
\fBonehost\fR
.
.SH "SYNOPSIS"
\fBonehost\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-i, \-\-im im_mad           Set the information driver for the host
 \-v, \-\-vm vmm_mad          Set the virtualization driver for the host
 \-n, \-\-net vnet_mad        Set the network driver for the host
 \-c, \-\-cluster id|name     Selects the cluster
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-k, \-\-kilobytes           Show units in kilobytes
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIhostname\fR
.
.IP "" 4
.
.nf

Creates a new Host
valid options: im, vmm, vnm, cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|hostid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Host
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
enable \fIrange|hostid_list\fR
.
.IP "" 4
.
.nf

Enables the given Host
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
disable \fIrange|hostid_list\fR
.
.IP "" 4
.
.nf

Disables the given Host
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fIhostid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
sync
.
.IP "" 4
.
.nf

Synchronizes probes in /var/lib/one/remotes ($ONE_LOCATION/var/remotes
in self\-contained installations) with Hosts\.
The copy is performed the next time the Host is monitored
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list
.
.IP "" 4
.
.nf

Lists Hosts in the pool
valid options: list, delay, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIhostid\fR
.
.IP "" 4
.
.nf

Shows information for the given Host
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
top
.
.IP "" 4
.
.nf

Lists Hosts continuously
valid options: list, delay, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hostid
.
.IP "" 4
.
.nf

OpenNebula HOST name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hostid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula HOST names or ids
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
