.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEIMAGE" "1" "April 2012" "" "oneimage(1) -- manages OpenNebula images"
.
.SH "NAME"
\fBoneimage\fR
.
.SH "SYNOPSIS"
\fBoneimage\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-d, \-\-datastore id|name   Selects the datastore
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Creates a new Image from the given template file
valid options: datastore
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Image
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
publish \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Publishes the given Image\. A public Image
can be seen and used by other users in the Image\'s group\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
unpublish \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Unpublishes the given Image\. A private
Image can\'t be used by any other user\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
persistent \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

Makes the given Image persistent\. A persistent Image saves the changes
made to the contents after the VM instance is shutdown (or in real time
if a shared FS is used)\. Persistent Images can be used by only
one VM instance at a time\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
nonpersistent \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

Makes the given Image non persistent\. See \'oneimage persistent\'
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fIimageid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
enable \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

Enables the given Image
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chtype \fIrange|imageid_list\fR \fItype\fR
.
.IP "" 4
.
.nf

Changes the Image\'s type
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
disable \fIrange|imageid_list\fR
.
.IP "" 4
.
.nf

Disables the given Image
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|imageid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the Image group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chown \fIrange|imageid_list\fR \fIuserid\fR [\fIgroupid\fR]
.
.IP "" 4
.
.nf

Changes the Image owner and group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chmod \fIrange|imageid_list\fR \fIoctet\fR
.
.IP "" 4
.
.nf

Changes the Image permissions
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Images in the pool
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIimageid\fR
.
.IP "" 4
.
.nf

Shows information for the given Image
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
top [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Images continuously
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
imageid
.
.IP "" 4
.
.nf

OpenNebula IMAGE name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
imageid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula IMAGE names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
filterflag
.
.IP "" 4
.
.nf

a, all       all the known IMAGEs
m, mine      the IMAGE belonging to the user in ONE_AUTH
g, group     \'mine\' plus the IMAGE belonging to the groups
             the user is member of
uid          IMAGE of the user identified by this uid
user         IMAGE of the user identified by the username
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
