.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEMARKETAPP" "1" "June 2016" "" "onemarketapp(1) -- manages appliances from Marketplaces"
.
.SH "NAME"
\fBonemarketapp\fR \- manages appliances from Marketplaces
.
.SH "SYNOPSIS"
\fBonemarket\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-m, \-\-marketplace id|name Selects the marketplace
 \-\-name name               Name of the new MarketPlaceApp
 \-\-description description Description for the new MarketPlaceApp
 \-\-image id|name           Selects the image
 \-\-dry                     Just print the template
 \-d, \-\-datastore id|name   Selects the datastore
 \-\-vmname name             Selects the name for the new VM Template, if the
                           App contains one
 \-\-force                   Overwrite the file
 \-a, \-\-append              Append new attributes to the current template
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-f, \-\-filter x,y,z        Filter data\. An array is specified with
                           column=value pairs\.
 \-\-csv                     Write table in csv format
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-\-describe                Describe list columns
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-\-user name               User name used to connect to OpenNebula
 \-\-password password       Password to authenticate with OpenNebula
 \-\-endpoint endpoint       URL of OpenNebula xmlrpc frontend
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create [\fIfile\fR] Creates a new marketplace app in the given marketplace valid options: marketplace, name, description, image, dry
.
.IP "\(bu" 4
export \fIappid\fR \fIname\fR Exports the marketplace app to the OpenNebula cloud valid options: datastore, vmname
.
.IP "\(bu" 4
download \fIappid\fR \fIpath\fR Downloads a MarketApp to a file valid options: force
.
.IP "\(bu" 4
delete \fIrange|appid_list\fR Deletes the given marketplace app
.
.IP "\(bu" 4
update \fIappid\fR [\fIfile\fR] Update the template contents for the app\. If a path is not provided the editor will be launched to modify the current content\. valid options: append
.
.IP "\(bu" 4
chgrp \fIrange|appid_list\fR \fIgroupid\fR Changes the marketplace app group
.
.IP "\(bu" 4
chown \fIrange|appid_list\fR \fIuserid\fR [\fIgroupid\fR] Changes the marketplace app owner and group
.
.IP "\(bu" 4
chmod \fIrange|appid_list\fR \fIoctet\fR Changes the marketplace app permissions
.
.IP "\(bu" 4
rename \fIappid\fR \fIname\fR Renames the marketplace app
.
.IP "\(bu" 4
list [\fIfilterflag\fR] Lists marketplace apps valid options: list, delay, filter, csv, xml, numeric, describe
.
.IP "\(bu" 4
show \fIappid\fR Shows information for the given marketplace app valid options: xml
.
.IP "\(bu" 4
enable \fIrange|appid_list\fR Enables the marketplace app
.
.IP "\(bu" 4
disable \fIrange|appid_list\fR Disables the marketplace app\. A disabled marketplace app cannot be exported to a cloud
.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "\(bu" 4
groupid OpenNebula GROUP name or id
.
.IP "\(bu" 4
userid OpenNebula USER name or id
.
.IP "\(bu" 4
appid OpenNebula MARKETPLACEAPP name or id
.
.IP "\(bu" 4
appid_list Comma\-separated list of OpenNebula MARKETPLACEAPP names or ids
.
.IP "\(bu" 4
filterflag a, all all the known MARKETPLACEAPPs m, mine the MARKETPLACEAPP belonging to the user in ONE_AUTH g, group \'mine\' plus the MARKETPLACEAPP belonging to the groups the user is member of uid MARKETPLACEAPP of the user identified by this uid user MARKETPLACEAPP of the user identified by the username
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 5\.0\.1 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
