.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONESECGROUP" "1" "May 2016" "" "onesecgroup(1) -- manages OpenNebula security groups"
.
.SH "NAME"
\fBonesecgroup\fR \- manages OpenNebula security groups
.
.SH "SYNOPSIS"
\fBonesecgroup\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-a, \-\-append              Append new attributes to the current template
 \-r, \-\-recover             If set the commit operation will only operate on
                           outdated and error VMs\. This is intended for
                           retrying updates of VMs or reinitialize the
                           updating process if oned stopped or fail\.
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-f, \-\-filter x,y,z        Filter data\. An array is specified with
                           column=value pairs\.
 \-\-csv                     Write table in csv format
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-\-describe                Describe list columns
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-\-user name               User name used to connect to OpenNebula
 \-\-password password       Password to authenticate with OpenNebula
 \-\-endpoint endpoint       URL of OpenNebula xmlrpc frontend
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR Creates a new Security Group from the given description
.
.IP "\(bu" 4
clone \fIsecgroupid\fR \fIname\fR Creates a new Security Group from an existing one
.
.IP "\(bu" 4
delete \fIrange|secgroupid_list\fR Deletes the given Security Group
.
.IP "\(bu" 4
chgrp \fIrange|secgroupid_list\fR \fIgroupid\fR Changes the Security Group\'s group
.
.IP "\(bu" 4
chown \fIrange|secgroupid_list\fR \fIuserid\fR [\fIgroupid\fR] Changes the Security Group\'s owner and group
.
.IP "\(bu" 4
chmod \fIrange|secgroupid_list\fR \fIoctet\fR Changes the Security Group permissions
.
.IP "\(bu" 4
update \fIsecgroupid\fR [\fIfile\fR] Update the template contents\. If a path is not provided the editor will be launched to modify the current content\. valid options: append
.
.IP "\(bu" 4
rename \fIsecgroupid\fR \fIname\fR Renames the Security Group
.
.IP "\(bu" 4
commit \fIsecgroupid\fR Commit SG changes to associated VMs\. This command is to propagate security group rules to VMs when they are updated\. This operation takes time to iterate over all VMs in the security group, progress can be checked through the outdated, updating and error VM sets\. valid options: recover
.
.IP "\(bu" 4
list [\fIfilterflag\fR] Lists Security Group in the pool valid options: list, delay, filter, csv, xml, numeric, describe
.
.IP "\(bu" 4
show \fIsecgroupid\fR Shows information for the given Security Group valid options: xml
.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "\(bu" 4
groupid OpenNebula GROUP name or id
.
.IP "\(bu" 4
userid OpenNebula USER name or id
.
.IP "\(bu" 4
secgroupid OpenNebula SECURITY_GROUP name or id
.
.IP "\(bu" 4
secgroupid_list Comma\-separated list of OpenNebula SECURITY_GROUP names or ids
.
.IP "\(bu" 4
filterflag a, all all the known SECURITY_GROUPs m, mine the SECURITY_GROUP belonging to the user in ONE_AUTH g, group \'mine\' plus the SECURITY_GROUP belonging to the groups the user is member of uid SECURITY_GROUP of the user identified by this uid user SECURITY_GROUP of the user identified by the username
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 4\.90\.5 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
