.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONETEMPLATE" "1" "April 2012" "" "onetemplate(1) -- manages OpenNebula templates"
.
.SH "NAME"
\fBonetemplate\fR
.
.SH "SYNOPSIS"
\fBonetemplate\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-n, \-\-name vm_name        Name of the new Virtual Machine\. When instantiating
                           multiple VMs you can use the"%i" wildcard to produce
                           different names such as vm\-0, vm\-1\.\.\.

 \-m, \-\-multiple x          Instance multiple VMs
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Creates a new Template from the given template file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|templateid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Image
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
instantiate \fItemplateid\fR
.
.IP "" 4
.
.nf

Creates a new VM instance from the given Template\. This VM can be
managed with the \'onevm\' command
valid options: vm_name, multiple
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
publish \fIrange|templateid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Publishes the given Template\. A public
Template can be seen and instantiated by other users in the Template\'s
group\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
unpublish \fIrange|templateid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Unpublishes the given Template\. A private
Template can\'t be instantiated by any other user\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|templateid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the Template group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chown \fIrange|templateid_list\fR \fIuserid\fR [\fIgroupid\fR]
.
.IP "" 4
.
.nf

Changes the Template owner and group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chmod \fIrange|templateid_list\fR \fIoctet\fR
.
.IP "" 4
.
.nf

Changes the Template permissions
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fItemplateid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Templates in the pool
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fItemplateid\fR
.
.IP "" 4
.
.nf

Shows information for the given Template
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
top [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Templates continuously
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
templateid
.
.IP "" 4
.
.nf

OpenNebula VMTEMPLATE name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
templateid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula VMTEMPLATE names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
filterflag
.
.IP "" 4
.
.nf

a, all       all the known VMTEMPLATEs
m, mine      the VMTEMPLATE belonging to the user in ONE_AUTH
g, group     \'mine\' plus the VMTEMPLATE belonging to the groups
             the user is member of
uid          VMTEMPLATE of the user identified by this uid
user         VMTEMPLATE of the user identified by the username
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
