.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEUSER" "1" "April 2012" "" "oneuser(1) -- manages OpenNebula users"
.
.SH "NAME"
\fBoneuser\fR
.
.SH "SYNOPSIS"
\fBoneuser\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-r, \-\-read\-file           Read password from file
 \-\-sha1                    The password will be hashed using the sha1 algorithm
 \-\-ssh                     SSH Auth system
 \-\-x509                    x509 Auth system for x509 certificates
 \-k, \-\-key path_to_private_key_pem Path to the Private Key of the User
 \-c, \-\-cert path_to_user_cert_pem Path to the Certificate of the User
 \-\-driver driver           Driver to autehnticate this user
 \-\-x509_proxy              x509 Auth system based on x509 proxy certificates
 \-\-proxy path_to_user_proxy_pem Path to the user proxy certificate
 \-\-time x                  Token duration in seconds, defaults to 3600 (1 h)
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIusername\fR [\fIpassword\fR]
.
.IP "" 4
.
.nf

Creates a new User
Examples:
  oneuser create my_user my_password
  oneuser create my_user \-r /tmp/mypass
  oneuser create my_user \-\-ssh \-\-key /tmp/id_rsa
  oneuser create my_user \-\-ssh \-r /tmp/public_key
  oneuser create my_user \-\-x509 \-\-cert /tmp/my_cert\.pem
valid options: read_file, sha1, ssh, x509, key, cert, driver
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fIuserid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
login \fIusername\fR
.
.IP "" 4
.
.nf

Creates the Login token for authentication
Examples:
  oneuser login my_user \-\-ssh \-\-key /tmp/id_rsa \-\-time 72000
  oneuser login my_user \-\-x509 \-\-cert /tmp/my_cert\.pem                                 \-\-key /tmp/my_key\.pk \-\-time 72000
  oneuser login my_user \-\-x509_proxy \-\-proxy /tmp/my_cert\.pem                                 \-\-time 72000
valid options: ssh, x509, x509_proxy, key, cert, proxy, time
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
key
.
.IP "" 4
.
.nf

Shows a public key from a private SSH key\. Use it as password
for the SSH authentication mechanism\.
valid options: key
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|userid_list\fR
.
.IP "" 4
.
.nf

Deletes the given User
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
passwd \fIuserid\fR [\fIpassword\fR]
.
.IP "" 4
.
.nf

Changes the given User\'s password
valid options: read_file, sha1, ssh, x509, key, cert, driver
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|userid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the User\'s main group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chauth \fIuserid\fR [\fIauth\fR] [\fIpassword\fR]
.
.IP "" 4
.
.nf

Changes the User\'s auth driver and its password (optional)
Examples:
  oneuser chauth my_user core
  oneuser chauth my_user core new_password
  oneuser chauth my_user core \-r /tmp/mypass
  oneuser chauth my_user \-\-ssh \-\-key /home/oneadmin/\.ssh/id_rsa
  oneuser chauth my_user \-\-ssh \-r /tmp/public_key
  oneuser chauth my_user \-\-x509 \-\-cert /tmp/my_cert\.pem
valid options: read_file, sha1, ssh, x509, key, cert, driver
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list
.
.IP "" 4
.
.nf

Lists Users in the pool
valid options: list, delay, xml, numeric
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show [\fIuserid\fR]
.
.IP "" 4
.
.nf

Shows information for the given User
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula USER names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
password
.
.IP "" 4
.
.nf

User password
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
