.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEVNET" "1" "June 2016" "" "onevnet(1) -- manages OpenNebula networks"
.
.SH "NAME"
\fBonevnet\fR \- manages OpenNebula networks
.
.SH "SYNOPSIS"
\fBonevnet\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-c, \-\-cluster id|name     Selects the cluster
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-\-user name               User name used to connect to OpenNebula
 \-\-password password       Password to authenticate with OpenNebula
 \-\-endpoint endpoint       URL of OpenNebula xmlrpc frontend
 \-s, \-\-size size           Number of addresses
 \-m, \-\-mac mac             First MAC address in : notation
 \-i, \-\-ip ip               First IP address in \. notation
 \-g, \-\-ip6_global ip6_pref IP6 global prefix
 \-u, \-\-ip6_ula ip6_pref    IP6 ula prefix
 \-\-gateway ip              IP of the gateway
 \-\-netmask mask            Netmask in dot notation
 \-\-vn_mad mad              Use this driver for the network
 \-\-vlanid id               VLAN ID assigned
 \-a, \-\-address_range ar_id ID of the address range
 \-n, \-\-name reservation name Name of the address reservation
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-f, \-\-filter x,y,z        Filter data\. An array is specified with
                           column=value pairs\.
 \-\-csv                     Write table in csv format
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-k, \-\-kilobytes           Show units in kilobytes
 \-\-describe                Describe list columns
 \-\-show\-ar                 Show also AR templates
 \-a, \-\-append              Append new attributes to the current template
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
 \-\-user name               User name used to connect to OpenNebula
 \-\-password password       Password to authenticate with OpenNebula
 \-\-endpoint endpoint       URL of OpenNebula xmlrpc frontend
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR Creates a new Virtual Network from the given template file valid options: cluster
.
.IP "\(bu" 4
delete \fIrange|vnetid_list\fR Deletes the given Virtual Network
.
.IP "\(bu" 4
addar \fIvnetid\fR [\fIfile\fR] Adds an address range to the Virtual Network valid options: verbose, help, version, user, password, endpoint, size, mac, ip, ip6_global, ip6_ula, gateway, netmask, vn_mad, vlanid
.
.IP "\(bu" 4
addleases \fIvnetid\fR \fIip\fR [\fImac\fR] (DEPRECATED, use addar) Adds a lease to the Virtual Network
.
.IP "\(bu" 4
rmar \fIvnetid\fR \fIar_id\fR Removes an address range from the Virtual Network
.
.IP "\(bu" 4
rmleases \fIvnetid\fR \fIip\fR (DEPRECATED, use rmar) Removes a lease from the Virtual Network
.
.IP "\(bu" 4
free \fIvnetid\fR \fIar_id\fR Frees a reserved address range from the Virtual Network
.
.IP "\(bu" 4
hold \fIvnetid\fR \fIip\fR Holds a Virtual Network lease, marking it as used valid options: verbose, help, version, user, password, endpoint, address_range
.
.IP "\(bu" 4
release \fIvnetid\fR \fIip\fR Releases a Virtual Network lease on hold valid options: verbose, help, version, user, password, endpoint, address_range
.
.IP "\(bu" 4
reserve \fIvnetid\fR [\fIvnetid\fR] Reserve addresses from the Virtual Network\. A new virtual network will be created to hold the reservation\. Optionally the reservation can be put on an exisiting VNET, as long as it contains a valid reservation from the same VNET valid options: verbose, help, version, user, password, endpoint, address_range, name, size, mac, ip
.
.IP "\(bu" 4
chgrp \fIrange|vnetid_list\fR \fIgroupid\fR Changes the Virtual Network group
.
.IP "\(bu" 4
chown \fIrange|vnetid_list\fR \fIuserid\fR [\fIgroupid\fR] Changes the Virtual Network owner and group
.
.IP "\(bu" 4
chmod \fIrange|vnetid_list\fR \fIoctet\fR Changes the Virtual Network permissions
.
.IP "\(bu" 4
list [\fIfilterflag\fR] Lists Virtual Networks in the pool valid options: list, delay, filter, csv, xml, numeric, kilobytes, describe
.
.IP "\(bu" 4
show \fIvnetid\fR Shows information for the given Virtual Network valid options: xml, show_ar
.
.IP "\(bu" 4
update \fIvnetid\fR [\fIfile\fR] Update the template contents\. If a path is not provided the editor will be launched to modify the current content\. valid options: append
.
.IP "\(bu" 4
updatear \fIvnetid\fR \fIar_id\fR [\fIfile\fR] Update Address Range variables\. SIZE, IP, MAC and TYPE cannot be updated
.
.IP "\(bu" 4
rename \fIvnetid\fR \fIname\fR Renames the Virtual Network
.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file Path to a file
.
.IP "\(bu" 4
range List of id\'s in the form 1,8\.\.15
.
.IP "\(bu" 4
text String
.
.IP "\(bu" 4
groupid OpenNebula GROUP name or id
.
.IP "\(bu" 4
userid OpenNebula USER name or id
.
.IP "\(bu" 4
vnetid OpenNebula VNET name or id
.
.IP "\(bu" 4
vnetid_list Comma\-separated list of OpenNebula VNET names or ids
.
.IP "\(bu" 4
filterflag a, all all the known VNETs m, mine the VNET belonging to the user in ONE_AUTH g, group \'mine\' plus the VNET belonging to the groups the user is member of uid VNET of the user identified by this uid user VNET of the user identified by the username
.
.IP "\(bu" 4
ar_id Integer
.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 5\.0\.1 Copyright 2002\-2016, OpenNebula Project, OpenNebula Systems
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
