.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEVNET" "1" "April 2012" "" "onevnet(1) -- manages OpenNebula networks"
.
.SH "NAME"
\fBonevnet\fR
.
.SH "SYNOPSIS"
\fBonevnet\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-c, \-\-cluster id|name     Selects the cluster
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-k, \-\-kilobytes           Show units in kilobytes
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Creates a new Virtual Network from the given template file
valid options: cluster
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|vnetid_list\fR
.
.IP "" 4
.
.nf

Deletes the given Virtual Network
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
addleases \fIvnetid\fR \fIip\fR [\fImac\fR]
.
.IP "" 4
.
.nf

Adds a lease to the Virtual Network
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
rmleases \fIvnetid\fR \fIip\fR
.
.IP "" 4
.
.nf

Removes a lease from the Virtual Network
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hold \fIvnetid\fR \fIip\fR
.
.IP "" 4
.
.nf

Holds a Virtual Network lease, marking it as used
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
release \fIvnetid\fR \fIip\fR
.
.IP "" 4
.
.nf

Releases a Virtual Network lease on hold
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
publish \fIrange|vnetid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Publishes the given Virtual Network\.
A public Virtual Network can be seen and used by other users in the
Virtual Network\'s group\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
unpublish \fIrange|vnetid_list\fR
.
.IP "" 4
.
.nf

DEPRECATED, use chmod instead\. Unpublishes the given Virtual Network\. A
private Virtual Network can\'t be used by any other user\.
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|vnetid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the Virtual Network group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chown \fIrange|vnetid_list\fR \fIuserid\fR [\fIgroupid\fR]
.
.IP "" 4
.
.nf

Changes the Virtual Network owner and group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chmod \fIrange|vnetid_list\fR \fIoctet\fR
.
.IP "" 4
.
.nf

Changes the Virtual Network permissions
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Virtual Networks in the pool
valid options: list, delay, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIvnetid\fR
.
.IP "" 4
.
.nf

Shows information for the given Virtual Network
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
update \fIvnetid\fR
.
.IP "" 4
.
.nf

Launches the system editor to modify and update the template contents
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vnetid
.
.IP "" 4
.
.nf

OpenNebula VNET name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vnetid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula VNET names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
filterflag
.
.IP "" 4
.
.nf

a, all       all the known VNETs
m, mine      the VNET belonging to the user in ONE_AUTH
g, group     \'mine\' plus the VNET belonging to the groups
             the user is member of
uid          VNET of the user identified by this uid
user         VNET of the user identified by the username
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
