.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEVDC" "1" "April 2012" "" "onevdc(1) -- manages OpenNebula Virtual DataCenters"
.
.SH "NAME"
\fBonevdc\fR
.
.SH "SYNOPSIS"
\fBonevdc\fR command [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-f, \-\-force               Force the usage of Hosts in more than one VDC
 \-j, \-\-json                Show the resource in JSON format
 \-s, \-\-hosts 1,2,3         Host IDs
 \-d, \-\-datastores 1,2,3    Datastore IDs
 \-n, \-\-networks 1,2,3      Network IDs
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Create a new VDC
valid options: force
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIvdcid\fR
.
.IP "" 4
.
.nf

Show information of a particular VDC
valid options: json
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list
.
.IP "" 4
.
.nf

Lists VDCs in the pool
valid options: json
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIvdcid\fR
.
.IP "" 4
.
.nf

Deletes a VDC
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
add \fIvdcid\fR
.
.IP "" 4
.
.nf

Adds the set of resources to the VDC
valid options: force, hosts, datastores, networks
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
del \fIvdcid\fR
.
.IP "" 4
.
.nf

Deletes the set of resources from the VDC
valid options: hosts, datastores, networks
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vdcid
.
.IP "" 4
.
.nf

VDC ID
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
