.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONEVM" "1" "April 2012" "" "onevm(1) -- manages OpenNebula virtual machines"
.
.SH "NAME"
\fBonevm\fR
.
.SH "SYNOPSIS"
\fBonevm\fR \fIcommand\fR [\fIargs\fR] [\fIoptions\fR]
.
.SH "OPTIONS"
.
.nf

 \-m, \-\-multiple x          Instance multiple VMs
 \-x, \-\-xml                 Show the resource in xml format
 \-n, \-\-numeric             Do not translate user and group IDs
 \-k, \-\-kilobytes           Show units in kilobytes
 \-t, \-\-type type           Type of the new Image
 \-l, \-\-list x,y,z          Selects columns to display with list command
 \-d, \-\-delay x             Sets the delay in seconds for top command
 \-v, \-\-verbose             Verbose mode
 \-h, \-\-help                Show this message
 \-V, \-\-version             Show version and copyright information
.
.fi
.
.SH "COMMANDS"
.
.IP "\(bu" 4
create \fIfile\fR
.
.IP "" 4
.
.nf

Creates a new VM from the given template file\. This command bypasses
the Template pool, which is the preferred way to instantiate new VMs\.
See \'onetemplate create\' and \'onetemplate instantiate\'
valid options: multiple, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
delete \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Deletes the given VM

States: ANY
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hold \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Sets the given VM on hold\. A VM on hold is not scheduled until it is
released\. It can be, however, deployed manually; see \'onevm deploy\'

States: PENDING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
release \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Releases a VM on hold\. See \'onevm hold\'

States: HOLD
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
saveas \fIvmid\fR \fIdiskid\fR \fIimg_name\fR
.
.IP "" 4
.
.nf

Sets the specified VM disk to be saved in a new Image\. The Image is
created inmediately, but the contents are saved only if the VM is
shut down gracefuly (i\.e\., using \'onevm shutdown\' and not
\'onevm delete\')

States: ANY
valid options: type
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
shutdown \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Shuts down the given VM\.

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
reboot \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Reboots the given VM, this is equivalent to execute the reboot command
from the VM console\.

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
deploy \fIrange|vmid_list\fR \fIhostid\fR
.
.IP "" 4
.
.nf

Deploys the given VM in the specified Host\. This command forces the
deployment, in a standard installation the Scheduler is in charge
of this decision

States: PENDING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
livemigrate \fIrange|vmid_list\fR \fIhostid\fR
.
.IP "" 4
.
.nf

Migrates the given running VM to another Host without downtime

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
migrate \fIrange|vmid_list\fR \fIhostid\fR
.
.IP "" 4
.
.nf

Saves the given running VM and starts it again in the specified Host

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
restart \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Forces a re\-deployment of the given VM, issuing a boot action\.

States: UNKNOWN, BOOT
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
resubmit \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Resubmits the VM to PENDING state\. This is intented for VMs stuck in a
transient state\. To re\-deploy a fresh copy of the same VM, create a
Template and instantiante it, see \'onetemplate instantiate\'

States: ANY, except SUSPENDED or DONE
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
cancel \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Cancels the given VM\. The process is checked by OpenNebula, so
if the process fails the VM remains in running state\. If the action
succeeds the VMDIR in the remote machine is not deleted

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
stop \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Stops a running VM\. The VM state is saved and transferred back to the
front\-end along with the disk files

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
suspend \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Saves a running VM\. It is the same as \'onevm stop\', but the files
are left in the remote machine to later restart the VM there
(i\.e\. the resources are not freed and there is no need to
re\-schedule the VM)\.

States: RUNNING
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
resume \fIrange|vmid_list\fR
.
.IP "" 4
.
.nf

Resumes the execution of the a saved VM

States: STOPPED, SUSPENDED
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chgrp \fIrange|vmid_list\fR \fIgroupid\fR
.
.IP "" 4
.
.nf

Changes the VM group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chown \fIrange|vmid_list\fR \fIuserid\fR [\fIgroupid\fR]
.
.IP "" 4
.
.nf

Changes the VM owner and group
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
chmod \fIrange|vmid_list\fR \fIoctet\fR
.
.IP "" 4
.
.nf

Changes the VM permissions
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
list [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists VMs in the pool
valid options: list, delay, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
show \fIvmid\fR
.
.IP "" 4
.
.nf

Shows information for the given VM
valid options: xml
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
top [\fIfilterflag\fR]
.
.IP "" 4
.
.nf

Lists Images continuously
valid options: list, delay, xml, numeric, kilobytes
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "ARGUMENT FORMATS"
.
.IP "\(bu" 4
file
.
.IP "" 4
.
.nf

Path to a file
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
range
.
.IP "" 4
.
.nf

List of id\'s in the form 1,8\.\.15
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
text
.
.IP "" 4
.
.nf

String
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
hostid
.
.IP "" 4
.
.nf

OpenNebula HOST name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
groupid
.
.IP "" 4
.
.nf

OpenNebula GROUP name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
userid
.
.IP "" 4
.
.nf

OpenNebula USER name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vmid
.
.IP "" 4
.
.nf

OpenNebula VM name or id
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
vmid_list
.
.IP "" 4
.
.nf

Comma\-separated list of OpenNebula VM names or ids
.
.fi
.
.IP "" 0

.
.IP "\(bu" 4
filterflag
.
.IP "" 4
.
.nf

a, all       all the known VMs
m, mine      the VM belonging to the user in ONE_AUTH
g, group     \'mine\' plus the VM belonging to the groups
             the user is member of
uid          VM of the user identified by this uid
user         VM of the user identified by the username
.
.fi
.
.IP "" 0

.
.IP "" 0
.
.SH "LICENSE"
OpenNebula 3\.5\.0 Copyright 2002\-2012, OpenNebula Project Leads (OpenNebula\.org)
.
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\. You may obtain a copy of the License at http://www\.apache\.org/licenses/LICENSE\-2\.0
