{
 "title": "Hosts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "one_host_id", "label": "Host ID", "query": { "query": "label_values(one_host_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Allocated VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_host_vms{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{one_host_id=\"$one_host_id\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',one_host_id=\"$one_host_id\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{one_host_id=\"$one_host_id\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{one_host_id=\"$one_host_id\"}) /  count(count(node_cpu_seconds_total{one_host_id=\"$one_host_id\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{one_host_id=\"$one_host_id\"}) /  count(count(node_cpu_seconds_total{one_host_id=\"$one_host_id\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{one_host_id=\"$one_host_id\"} * 100) / node_memory_MemTotal_bytes{one_host_id=\"$one_host_id\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{one_host_id=\"$one_host_id\"} - node_memory_SwapFree_bytes{one_host_id=\"$one_host_id\"}) / (node_memory_SwapTotal_bytes{one_host_id=\"$one_host_id\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{one_host_id=\"$one_host_id\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{one_host_id=\"$one_host_id\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{one_host_id=\"$one_host_id\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{one_host_id=\"$one_host_id\"} - node_boot_time_seconds{one_host_id=\"$one_host_id\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_host_mem_total_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_host_mem_maximum_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_host_mem_usage_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (one_host_id)(rate(node_cpu_seconds_total{mode=\"system\",one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (one_host_id)(rate(node_cpu_seconds_total{mode='user',one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (one_host_id)(rate(node_cpu_seconds_total{mode='iowait',one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (one_host_id)(rate(node_cpu_seconds_total{mode=~\".*irq\",one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',one_host_id=\"$one_host_id\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{one_host_id=\"$one_host_id\"} - node_memory_MemAvailable_bytes{one_host_id=\"$one_host_id\"} - (node_memory_Cached_bytes{one_host_id=\"$one_host_id\"} + node_memory_Buffers_bytes{one_host_id=\"$one_host_id\"} + node_memory_SReclaimable_bytes{one_host_id=\"$one_host_id\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{one_host_id=\"$one_host_id\"} + node_memory_Buffers_bytes{one_host_id=\"$one_host_id\"} + node_memory_SReclaimable_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{one_host_id=\"$one_host_id\"}",
     "legendFormat": "RAM Available"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{one_host_id=\"$one_host_id\"} - node_memory_SwapFree_bytes{one_host_id=\"$one_host_id\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opennebula_host_cpu_total_ratio{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_host_cpu_maximum_ratio{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "opennebula_host_cpu_usage_ratio{one_host_id=\"$one_host_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{one_host_id=\"$one_host_id\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{one_host_id=\"$one_host_id\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{one_host_id=\"$one_host_id\",device!~'rootfs',mountpoint!~\"/run.*\",mountpoint!~\"/boot.*\"} * 100) / node_filesystem_size_bytes{one_host_id=\"$one_host_id\",device!~'rootfs',mountpoint!~\"/run.*\",mountpoint!~\"/boot.*\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}