# SConstruct for src/im

Import('env')

lib_name='nebula_im'

# Sources to generate the library
source_files=[
	'InformationManager.cc',
	'InformationManagerDriver.cc'
]

test_names=[]

# Build library
env.StaticLibrary(lib_name, source_files)

