name: Slack Push Notifier

on:
  push:
    branches:
      - master
  workflow_dispatch:
        
jobs:
  notify_slack_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" --> *New Commit:* <${{ github.event.commit[0].html_url }}|${{ github.event.commit[0].messsage }}>\n\"}}]}' 
        if: success()
