#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2
VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------
DST_PATH=$(arg_path $DST)
DST_HOST=$(arg_host $DST)
DST_DIR=$(dirname $DST_PATH)

SRC_ARG_PATH=$(arg_path $SRC)

DST_DS_PATH="$(dirname "$(dirname "$(dirname "$DST_PATH")")")"
SRC_DS_PATH="$(dirname "$(dirname "$SRC_ARG_PATH")")"

SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID="$(basename "${DST_PATH}" | cut -d. -f2)"

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
                    /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/SIZE \
                    /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/FORMAT \
                    /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/ORIGINAL_SIZE \
                    /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/QCOW2_STANDALONE \
                    /VM/TEMPLATE/DISK\[DISK_ID=$DISK_ID\]/SPARSE)

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DSID| $XPATH \
                    /DATASTORE/TEMPLATE/NFS_AUTO_ENABLE \
                    /DATASTORE/TEMPLATE/NFS_AUTO_HOST \
                    /DATASTORE/TEMPLATE/NFS_AUTO_PATH \
                    /DATASTORE/TEMPLATE/NFS_AUTO_OPTS)

SIZE="${XPATH_ELEMENTS[j++]}"
FORMAT="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"
QCOW2_STANDALONE="${XPATH_ELEMENTS[j++]}"
SPARSE="${XPATH_ELEMENTS[j++]}"

ANFS_ENABLE="${XPATH_ELEMENTS[j++]}"
ANFS_HOST="${XPATH_ELEMENTS[j++]}"
ANFS_PATH="${XPATH_ELEMENTS[j++]}"
ANFS_OPTS="${XPATH_ELEMENTS[j++]}"

DS_SYS_ID="$(basename "$DST_DIR")"

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DS_SYS_ID| $XPATH \
                    /DATASTORE/TEMPLATE/NFS_AUTO_ENABLE \
                    /DATASTORE/TEMPLATE/NFS_AUTO_HOST \
                    /DATASTORE/TEMPLATE/NFS_AUTO_PATH \
                    /DATASTORE/TEMPLATE/NFS_AUTO_OPTS)

SYS_ANFS_ENABLE="${XPATH_ELEMENTS[j++]}"
SYS_ANFS_HOST="${XPATH_ELEMENTS[j++]}"
SYS_ANFS_PATH="${XPATH_ELEMENTS[j++]}"
SYS_ANFS_OPTS="${XPATH_ELEMENTS[j++]}"

#-------------------------------------------------------------------------------
# Clone (cp) SRC into DST
#-------------------------------------------------------------------------------

if [ -n "$ORIGINAL_SIZE" ] && [ "$SIZE" -gt "$ORIGINAL_SIZE" ]; then
    if [[ "${SPARSE}" =~ ^(no|NO)$ ]]; then
        RESIZE_CMD="qemu-img resize --preallocation=falloc ${DST_PATH} ${SIZE}M"
    else
        RESIZE_CMD="qemu-img resize ${DST_PATH} ${SIZE}M"
    fi
fi

if [ "$FORMAT" = "qcow2" ] && is_yes "${QCOW2_STANDALONE}"; then
    CLONE_CMD=$(qcow_dir_cmd "$SRC_PATH" "$DST_PATH" "convert")
    [[ "${SPARSE}" =~ ^(no|NO)$ ]] && CLONE_CMD="${CLONE_CMD/-O qcow2/-O qcow2 -S 0}"
elif [ "$FORMAT" = "qcow2" ]; then
    CLONE_CMD=$(qcow_dir_cmd $SRC_PATH $DST_PATH "create")
else
    CLONE_CMD="cp $SRC_PATH $DST_PATH"
fi

NFS_MOUNT_CMD=$(cat <<EOF
    `autonfs_mount_command "$DSID" "$ANFS_ENABLE" "$ANFS_HOST" "$ANFS_PATH" "$ANFS_OPTS"`
    `autonfs_mount_command "$DS_SYS_ID" "$SYS_ANFS_ENABLE" "$SYS_ANFS_HOST" "$SYS_ANFS_PATH" "$SYS_ANFS_OPTS"`
EOF
)

ssh_exec_and_log "$DST_HOST" "$NFS_MOUNT_CMD" "Error setting up NFS mounts"
ssh_make_path $DST_HOST $DST_DIR
disable_local_monitoring $DST_HOST $DST_DIR

CLONE_RESIZE_CMD=$(cat <<EOF
    $CLONE_CMD
    $RESIZE_CMD
EOF
)

log "Cloning $SRC_PATH in $DST"
ssh_exec_and_log "$DST_HOST" "$CLONE_RESIZE_CMD" "Error copying $SRC to $DST"

exit 0
