#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2024, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
require_relative '../lib/tm_action'
require_relative '../lib/datastore'

#-------------------------------------------------------------------------------
# BACKUP tm_mad host:remote_dir DISK_ID:...:DISK_ID deploy_id bjid vmid dsid
#-------------------------------------------------------------------------------
TransferManager::Datastore.load_env

_vm_xml = STDIN.read

dir        = ARGV[0].split ':'
disks      = ARGV[1]
_deploy_id = ARGV[2]
_bjid      = ARGV[3]
vmid       = ARGV[4]
_dsid      = ARGV[5]

rhost     = dir[0]
rdir      = dir[1]

base_path = ENV['BACKUP_BASE_PATH']

tmp_dir = "#{rdir}/tmp"
bck_dir = if base_path
              "#{base_path}/#{vmid}/backup"
          else
              "#{rdir}/backup"
          end

qcow2_util = '/var/tmp/one/tm/lib/backup_qcow2.rb'

post_script = <<~EOS
    set -ex -o pipefail

    # --------------------------------------------------------------------
    # Commit changes, pivot disks and delete libvirt snapshot (only full)
    # --------------------------------------------------------------------
    #{qcow2_util} -s -l -d "#{disks}" -x #{bck_dir}/vm.xml -p #{rdir}

    # ----------------------
    # Cleanup backup folders
    # ----------------------
    rm -rf #{tmp_dir}
    rm -rf #{bck_dir}
EOS

post_script << "    rm -rf #{base_path}/#{vmid}\n" if base_path

rc = TransferManager::Action.ssh('postbackup_live',
                                 :host => rhost,
                                 :cmds => post_script,
                                 :nostdout => false,
                                 :nostderr => false)

if rc.code != 0
    STDERR.puts "Error cleaning backup temporal files: #{rc.stdout} #{rc.stderr}"
end

# Error is logged, tmp files will be removed in next backup, or VM termination
exit(0)
