#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2025, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
# PREMIGRATE SOURCE DST remote_system_dir vmid dsid template system_ds_mad
# POSTMIGRATE SOURCE DST remote_system_dir vmid dsid template system_ds_mad
#  - SOURCE is the host where the VM is running
#  - DST is the host where the VM is to be migrated
#  - remote_system_dir is the path for the VM home in the system datastore
#  - vmid is the id of the VM
#  - dsid is the target datastore
#  - template is the template of the VM in XML and base64 encoded
#  - system_ds_mad flag if called by other SYSTEM_DS TM_MAD

SRC_HOST="$1"
DST_HOST="$2"
DST_PATH="$3"
VM_ID="$4"
DS_ID="$5"
TEMPLATE_64=$(cat)

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

source $TMCOMMON

# Obtain original system directory (srcpath) for system DS migrations
DRIVER_PATH=$(dirname $0)
XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
unset i j XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VM_ID | $XPATH \
    /VM/HISTORY_RECORDS/HISTORY[last\(\)-1]/DS_ID)

ORIG_DS_ID="${XPATH_ELEMENTS[j++]}"

if [ "$ORIG_DS_ID" != "$DS_ID" ]; then
    SRC_PATH="${DST_PATH}/../../${ORIG_DS_ID}/${VM_ID}"

    CMD=$(cat <<EOF
        set -ex -o pipefail
        # Remove origin VM folder
        rm -rf "${SRC_PATH}"
EOF
)

    ssh_exec_and_log "$SRC_HOST" "$CMD" "Error running qcow2 postmigrate"

elif [ "$SRC_HOST" == "$DST_HOST" ]; then
    log "Not moving $SRC_HOST to $DST_HOST, they are the same host"
    exit 0
fi

#--------------------------------------------------------------------------------

migrate_other "$@"
